<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EAnnotation source="ModellingUnit">
    <details key="require" value="kermeta|platform:/resource/SmartAdapters/metamodel/generic/genericSmartAdapters.kmt|platform:/resource/SmartAdapters/metamodel/domain/FSMMM.ecore|platform:/resource/SmartAdapters/metamodel/domain/FSMMMPattern.ecore|"/>
    <details key="using" value="kermeta::standard|kermeta::utils|patternframework|org::smartadapters::core|org::smartadapters::extension|ecore|org::smartadapters::utils|org|org::smartadapters|org::smartadapters::core::adaptations|"/>
  </ecore:EAnnotation>
  <ecore:EPackage name="org" nsURI="platform:/resource/SmartAdapters/metamodel/specific/FSM_AOM_Framework.ecore#/" nsPrefix="org">
    <eClassifiers xsi:type="ecore:EDataType" name="_KermetaSpecialTypesAlias_" instanceClassName="java.lang.Object"/>
    <eSubpackages name="smartadapters" nsURI="platform:/resource/SmartAdapters/metamodel/specific/FSM_AOM_Framework.ecore#/org/smartadapters" nsPrefix="smartadapters">
      <eSubpackages name="core" nsURI="platform:/resource/SmartAdapters/metamodel/specific/FSM_AOM_Framework.ecore#/org/smartadapters/core" nsPrefix="core">
        <eClassifiers xsi:type="ecore:EClass" name="Adapter">
          <eAnnotations source="kermeta">
            <details key="aspect" value="true"/>
          </eAnnotations>
          <eSuperTypes href="../../../../plugin/fr.irisa.triskell.kermeta.io/src/kermeta/language/structure.ecore#/1/language/structure/Object"/>
          <eOperations name="initConvert">
            <eAnnotations source="kermeta">
              <details key="body" value="do&#xA;&#x9;stdio.write(&quot;Mapping MM\' to MM...&quot;)&#xA;&#x9;converter := org::smartadapters::utils::Converter.new&#xA;&#x9;convert := kermeta::utils::Hashtable&lt;kermeta::reflection::Class, kermeta::reflection::Class>.new&#xA;&#x9;convert.put(pattern::FSM::State, FSM::State)&#xA;&#x9;convert.put(pattern::FSM::Transition, FSM::Transition)&#xA;&#x9;convert.put(pattern::FSM::Fsm, FSM::Fsm)&#xA;&#x9;converter.initConverter(convert)&#xA;&#x9;stdio.writeln(&quot;OK!&quot;)&#xA;end"/>
            </eAnnotations>
          </eOperations>
        </eClassifiers>
        <eSubpackages name="adaptations" nsURI="platform:/resource/SmartAdapters/metamodel/specific/FSM_AOM_Framework.ecore#/org/smartadapters/core/adaptations" nsPrefix="adaptations">
          <eClassifiers xsi:type="ecore:EClass" name="CreateState">
            <eSuperTypes href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/createAdaptation"/>
            <eOperations name="check">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;result := newState.isNotEqual(void)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/check"/>
              </eAnnotations>
              <eType xsi:type="ecore:EClass" href="../../../../plugin/fr.irisa.triskell.kermeta.io/src/kermeta/standard/primitive_types.ecore#/1/standard/Boolean"/>
            </eOperations>
            <eOperations name="execute">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;adapter.cloneAgain(newState, void, isUnique)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/execute"/>
              </eAnnotations>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="newState" containment="true">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/State"/>
            </eStructuralFeatures>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="CloneState">
            <eSuperTypes href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/cloneAdaptation"/>
            <eOperations name="check">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;result := StateToClone.isNotEqual(void)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/check"/>
              </eAnnotations>
              <eType xsi:type="ecore:EClass" href="../../../../plugin/fr.irisa.triskell.kermeta.io/src/kermeta/standard/primitive_types.ecore#/1/standard/Boolean"/>
            </eOperations>
            <eOperations name="execute">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;adapter.cloneAgain(clonedState, StateToClone, isUnique)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/execute"/>
              </eAnnotations>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="StateToClone">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/State"/>
            </eStructuralFeatures>
            <eStructuralFeatures xsi:type="ecore:EReference" name="clonedState" containment="true">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/State"/>
            </eStructuralFeatures>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="SetState">
            <eSuperTypes href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/setAdaptation"/>
            <eOperations name="check">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;result := StateToSet.isNotEqual(void)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/check"/>
              </eAnnotations>
              <eType xsi:type="ecore:EClass" href="../../../../plugin/fr.irisa.triskell.kermeta.io/src/kermeta/standard/primitive_types.ecore#/1/standard/Boolean"/>
            </eOperations>
            <eOperations name="execute">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;var tempState : FSM::State&#xA;&#x9;tempState ?= adapter.getRealObject(StateToSet, false)&#xA;&#x9;tempState.name ?= adapter.setSingleProperty(refname, tempState.name)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/execute"/>
              </eAnnotations>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="StateToSet">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/State"/>
            </eStructuralFeatures>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="refname">
              <eAnnotations source="kermeta">
                <details key="isComposite" value="false"/>
              </eAnnotations>
              <eType xsi:type="ecore:EClass" href="../../../../plugin/fr.irisa.triskell.kermeta.io/src/kermeta/standard/primitive_types.ecore#/1/standard/String"/>
            </eStructuralFeatures>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="UnsetState">
            <eSuperTypes href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/unsetAdaptation"/>
            <eOperations name="check">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;result := StateToUnset.isNotEqual(void)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/check"/>
              </eAnnotations>
              <eType xsi:type="ecore:EClass" href="../../../../plugin/fr.irisa.triskell.kermeta.io/src/kermeta/standard/primitive_types.ecore#/1/standard/Boolean"/>
            </eOperations>
            <eOperations name="execute">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;var tempState : FSM::State&#xA;&#x9;tempState ?= adapter.getRealObject(StateToUnset, false)&#xA;&#x9;tempState.name ?= adapter.unsetSingleProperty(refname, tempState.name)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/execute"/>
              </eAnnotations>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="StateToUnset">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/State"/>
            </eStructuralFeatures>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="refname">
              <eAnnotations source="kermeta">
                <details key="isComposite" value="false"/>
              </eAnnotations>
              <eType xsi:type="ecore:EClass" href="../../../../plugin/fr.irisa.triskell.kermeta.io/src/kermeta/standard/primitive_types.ecore#/1/standard/String"/>
            </eStructuralFeatures>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="CreateTransition">
            <eSuperTypes href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/createAdaptation"/>
            <eOperations name="check">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;result := newTransition.isNotEqual(void)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/check"/>
              </eAnnotations>
              <eType xsi:type="ecore:EClass" href="../../../../plugin/fr.irisa.triskell.kermeta.io/src/kermeta/standard/primitive_types.ecore#/1/standard/Boolean"/>
            </eOperations>
            <eOperations name="execute">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;adapter.cloneAgain(newTransition, void, isUnique)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/execute"/>
              </eAnnotations>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="newTransition" containment="true">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/Transition"/>
            </eStructuralFeatures>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="CloneTransition">
            <eSuperTypes href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/cloneAdaptation"/>
            <eOperations name="check">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;result := TransitionToClone.isNotEqual(void)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/check"/>
              </eAnnotations>
              <eType xsi:type="ecore:EClass" href="../../../../plugin/fr.irisa.triskell.kermeta.io/src/kermeta/standard/primitive_types.ecore#/1/standard/Boolean"/>
            </eOperations>
            <eOperations name="execute">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;adapter.cloneAgain(clonedTransition, TransitionToClone, isUnique)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/execute"/>
              </eAnnotations>
              <eAnnotations source="kermeta.pre">
                <details key="isChecked" value="check"/>
              </eAnnotations>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="TransitionToClone">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/Transition"/>
            </eStructuralFeatures>
            <eStructuralFeatures xsi:type="ecore:EReference" name="clonedTransition" containment="true">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/Transition"/>
            </eStructuralFeatures>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="SetTransition">
            <eSuperTypes href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/setAdaptation"/>
            <eOperations name="check">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;result := TransitionToSet.isNotEqual(void)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/check"/>
              </eAnnotations>
              <eType xsi:type="ecore:EClass" href="../../../../plugin/fr.irisa.triskell.kermeta.io/src/kermeta/standard/primitive_types.ecore#/1/standard/Boolean"/>
            </eOperations>
            <eOperations name="execute">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;var tempTransition : FSM::Transition&#xA;&#x9;tempTransition ?= adapter.getRealObject(TransitionToSet, false)&#xA;&#x9;tempTransition.source ?= adapter.setSingleProperty(refsource, tempTransition.source)&#xA;&#x9;tempTransition.target ?= adapter.setSingleProperty(reftarget, tempTransition.target)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/execute"/>
              </eAnnotations>
              <eAnnotations source="kermeta.pre">
                <details key="isChecked" value="check"/>
              </eAnnotations>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="TransitionToSet">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/Transition"/>
            </eStructuralFeatures>
            <eStructuralFeatures xsi:type="ecore:EReference" name="refsource">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/State"/>
            </eStructuralFeatures>
            <eStructuralFeatures xsi:type="ecore:EReference" name="reftarget">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/State"/>
            </eStructuralFeatures>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="UnsetTransition">
            <eSuperTypes href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/unsetAdaptation"/>
            <eOperations name="check">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;result := TransitionToUnset.isNotEqual(void)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/check"/>
              </eAnnotations>
              <eType xsi:type="ecore:EClass" href="../../../../plugin/fr.irisa.triskell.kermeta.io/src/kermeta/standard/primitive_types.ecore#/1/standard/Boolean"/>
            </eOperations>
            <eOperations name="execute">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;var tempTransition : FSM::Transition&#xA;&#x9;tempTransition ?= adapter.getRealObject(TransitionToUnset, false)&#xA;&#x9;tempTransition.source ?= adapter.unsetSingleProperty(refsource, tempTransition.source)&#xA;&#x9;tempTransition.target ?= adapter.unsetSingleProperty(reftarget, tempTransition.target)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/execute"/>
              </eAnnotations>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="TransitionToUnset">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/Transition"/>
            </eStructuralFeatures>
            <eStructuralFeatures xsi:type="ecore:EReference" name="refsource">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/State"/>
            </eStructuralFeatures>
            <eStructuralFeatures xsi:type="ecore:EReference" name="reftarget">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/State"/>
            </eStructuralFeatures>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="CreateFsm">
            <eSuperTypes href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/createAdaptation"/>
            <eOperations name="check">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;result := newFsm.isNotEqual(void)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/check"/>
              </eAnnotations>
              <eType xsi:type="ecore:EClass" href="../../../../plugin/fr.irisa.triskell.kermeta.io/src/kermeta/standard/primitive_types.ecore#/1/standard/Boolean"/>
            </eOperations>
            <eOperations name="execute">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;adapter.cloneAgain(newFsm, void, isUnique)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/execute"/>
              </eAnnotations>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="newFsm" containment="true">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/Fsm"/>
            </eStructuralFeatures>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="CloneFsm">
            <eSuperTypes href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/cloneAdaptation"/>
            <eOperations name="check">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;result := FsmToClone.isNotEqual(void)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/check"/>
              </eAnnotations>
              <eType xsi:type="ecore:EClass" href="../../../../plugin/fr.irisa.triskell.kermeta.io/src/kermeta/standard/primitive_types.ecore#/1/standard/Boolean"/>
            </eOperations>
            <eOperations name="execute">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;adapter.cloneAgain(clonedFsm, FsmToClone, isUnique)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/execute"/>
              </eAnnotations>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="FsmToClone">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/Fsm"/>
            </eStructuralFeatures>
            <eStructuralFeatures xsi:type="ecore:EReference" name="clonedFsm" containment="true">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/Fsm"/>
            </eStructuralFeatures>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="SetFsm">
            <eSuperTypes href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/setAdaptation"/>
            <eOperations name="check">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;result := FsmToSet.isNotEqual(void)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/check"/>
              </eAnnotations>
              <eType xsi:type="ecore:EClass" href="../../../../plugin/fr.irisa.triskell.kermeta.io/src/kermeta/standard/primitive_types.ecore#/1/standard/Boolean"/>
            </eOperations>
            <eOperations name="execute">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;var tempFsm : FSM::Fsm&#xA;&#x9;tempFsm ?= adapter.getRealObject(FsmToSet, false)&#xA;&#x9;adapter.setMultipleProperty(tempFsm.states, refstates)&#xA;&#x9;adapter.setMultipleProperty(tempFsm.transitions, reftransitions)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/execute"/>
              </eAnnotations>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="FsmToSet">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/Fsm"/>
            </eStructuralFeatures>
            <eStructuralFeatures xsi:type="ecore:EReference" name="refstates" upperBound="-1">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/State"/>
            </eStructuralFeatures>
            <eStructuralFeatures xsi:type="ecore:EReference" name="reftransitions" upperBound="-1">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/Transition"/>
            </eStructuralFeatures>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="UnsetFsm">
            <eSuperTypes href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/unsetAdaptation"/>
            <eOperations name="check">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;result := FsmToUnset.isNotEqual(void)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/check"/>
              </eAnnotations>
              <eType xsi:type="ecore:EClass" href="../../../../plugin/fr.irisa.triskell.kermeta.io/src/kermeta/standard/primitive_types.ecore#/1/standard/Boolean"/>
            </eOperations>
            <eOperations name="execute">
              <eAnnotations source="kermeta">
                <details key="body" value="do&#xA;&#x9;var tempFsm : FSM::Fsm&#xA;&#x9;tempFsm ?= adapter.getRealObject(FsmToUnset, false)&#xA;&#x9;adapter.unsetMultipleProperty(tempFsm.states, refstates)&#xA;&#x9;adapter.unsetMultipleProperty(tempFsm.transitions, reftransitions)&#xA;end"/>
                <details key="superOperation" value="org::smartadapters::core::Adaptation"/>
                <references href="../generic/genericSmartAdaptersBase.ecore#/1/smartadapters/core/Adaptation/execute"/>
              </eAnnotations>
            </eOperations>
            <eStructuralFeatures xsi:type="ecore:EReference" name="FsmToUnset">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/Fsm"/>
            </eStructuralFeatures>
            <eStructuralFeatures xsi:type="ecore:EReference" name="refstates" upperBound="-1">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/State"/>
            </eStructuralFeatures>
            <eStructuralFeatures xsi:type="ecore:EReference" name="reftransitions" upperBound="-1">
              <eType xsi:type="ecore:EClass" href="../domain/FSMMMPattern.ecore#/1/FSM/Transition"/>
            </eStructuralFeatures>
          </eClassifiers>
        </eSubpackages>
      </eSubpackages>
    </eSubpackages>
  </ecore:EPackage>
  <ecore:EAnnotation source="dependentResource">
    <references href="../generic/genericSmartAdapters.ecore#/0"/>
    <references href="../generic/genericSmartAdapters.ecore#/1"/>
    <references href="../generic/genericSmartAdapters.ecore#/2"/>
    <references href="../generic/genericSmartAdaptersBase.ecore#/0"/>
    <references href="../generic/genericSmartAdaptersBase.ecore#/1"/>
    <references href="../../../fr.irisa.triskell.kermeta.patternmatching/src/kermeta/pattern/metamodel/PatternFramework.ecore#/0"/>
    <references href="../../../fr.irisa.triskell.kermeta.patternmatching/src/kermeta/pattern/metamodel/PatternFramework.ecore#/1"/>
    <references href="../domain/runtime/runtimePattern.ecore#/0"/>
    <references href="../domain/runtime/runtimePattern.ecore#/1"/>
    <references href="../domain/runtime/typePattern.ecore#/"/>
    <references href="../domain/FSMMMPattern.ecore#/0"/>
    <references href="../domain/FSMMMPattern.ecore#/1"/>
    <references href="../../program/weaving/converter.ecore#/0"/>
    <references href="../../program/weaving/converter.ecore#/1"/>
    <references href="../domain/FSMMM.ecore#/0"/>
    <references href="../domain/FSMMM.ecore#/1"/>
    <references href="../../../../plugin/fr.irisa.triskell.kermeta.io/src/kermeta/utils/utils.ecore#/0"/>
    <references href="../../../../plugin/fr.irisa.triskell.kermeta.io/src/kermeta/utils/utils.ecore#/1"/>
    <references href="../../../../plugin/fr.irisa.triskell.kermeta.io/src/kermeta/utils/Stack.ecore#/0"/>
    <references href="../../../../plugin/fr.irisa.triskell.kermeta.io/src/kermeta/utils/Stack.ecore#/1"/>
  </ecore:EAnnotation>
</xmi:XMI>
