/**
 * Copyright: IRISA/INRIA/Universite de Rennes 1 - License: EPL - Web site: http://www.kermeta.org
 *
 * $Id: ClassDefinitionValidator.java,v 1.1 2008-06-24 14:23:24 cfaucher Exp $
 */
package kermeta.language.structure.validation;

import kermeta.language.structure.Constraint;
import kermeta.language.structure.Operation;
import kermeta.language.structure.Property;
import kermeta.language.structure.Type;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link kermeta.language.structure.ClassDefinition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClassDefinitionValidator
{
  boolean validate();

  boolean validateOwnedOperation(EList<Operation> value);
  boolean validateIsAbstract(boolean value);
  boolean validateSuperType(EList<Type> value);
  boolean validateInv(EList<Constraint> value);
  boolean validateAllOperation(EList<Operation> value);
  boolean validateAllAttribute(EList<Property> value);
  boolean validateOwnedAttribute(EList<Property> value);
}
