/**
 * Copyright: IRISA/INRIA/Universite de Rennes 1 - License: EPL - Web site: http://www.kermeta.org
 *
 * $Id: OperationValidator.java,v 1.1 2008-06-24 14:23:24 cfaucher Exp $
 */
package kermeta.language.structure.validation;

import kermeta.language.behavior.Expression;

import kermeta.language.structure.ClassDefinition;
import kermeta.language.structure.Constraint;
import kermeta.language.structure.Operation;
import kermeta.language.structure.Parameter;
import kermeta.language.structure.Type;
import kermeta.language.structure.TypeVariable;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link kermeta.language.structure.Operation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OperationValidator
{
  boolean validate();

  boolean validateTypeParameter(EList<TypeVariable> value);
  boolean validateBody(Expression value);
  boolean validateOwnedParameter(EList<Parameter> value);
  boolean validateIsAbstract(boolean value);
  boolean validatePost(EList<Constraint> value);
  boolean validateRaisedException(EList<Type> value);
  boolean validatePre(EList<Constraint> value);
  boolean validateSuperOperation(Operation value);
  boolean validateOwningClass(ClassDefinition value);
}
