/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package art.resource.artext.mopp;

// A CodeCompletionHelper can be used to derive completion proposals for partial
// documents. It runs the parser generated by EMFText in a special mode (i.e., the
// rememberExpectedElements mode). Based on the elements that are expected by the
// parser for different regions in the document, valid proposals are computed.
public class ArtextCodeCompletionHelper {
	
	// Computes a set of proposals for the given document assuming the cursor is
	// at 'cursorOffset'. The proposals are derived using the meta information, i.e.,
	// the generated language plug-in.
	//
	// @param metaInformation
	// @param content the documents content
	// @param cursorOffset
	// @return
	public art.resource.artext.mopp.ArtextCompletionProposal[] computeCompletionProposals(art.resource.artext.IArtextTextResource originalResource, String content, int cursorOffset) {
		org.eclipse.emf.ecore.resource.ResourceSet resourceSet = new org.eclipse.emf.ecore.resource.impl.ResourceSetImpl();
		// the shadow resource needs the same URI because reference resolvers may use the URI to resolve external references
		art.resource.artext.IArtextTextResource resource = (art.resource.artext.IArtextTextResource) resourceSet.createResource(originalResource.getURI());
		java.io.ByteArrayInputStream inputStream = new java.io.ByteArrayInputStream(content.getBytes());
		art.resource.artext.mopp.ArtextMetaInformation metaInformation = resource.getMetaInformation();
		art.resource.artext.IArtextTextParser parser = metaInformation.createParser(inputStream, null);
		art.resource.artext.mopp.ArtextExpectedTerminal[] expectedElements = parseToExpectedElements(parser, resource);
		if (expectedElements == null) {
			return new art.resource.artext.mopp.ArtextCompletionProposal[0];
		}
		if (expectedElements.length == 0) {
			return new art.resource.artext.mopp.ArtextCompletionProposal[0];
		}
		java.util.List<art.resource.artext.mopp.ArtextExpectedTerminal> expectedAfterCursor = java.util.Arrays.asList(getElementsExpectedAt(expectedElements, cursorOffset));
		java.util.List<art.resource.artext.mopp.ArtextExpectedTerminal> expectedBeforeCursor = java.util.Arrays.asList(getElementsExpectedAt(expectedElements, cursorOffset - 1));
		setPrefixes(expectedAfterCursor, content, cursorOffset);
		setPrefixes(expectedBeforeCursor, content, cursorOffset);
		// first we derive all possible proposals from the set of elements that are expected at the cursor position
		java.util.Collection<art.resource.artext.mopp.ArtextCompletionProposal> allProposals = new java.util.LinkedHashSet<art.resource.artext.mopp.ArtextCompletionProposal>();
		java.util.Collection<art.resource.artext.mopp.ArtextCompletionProposal> rightProposals = deriveProposals(expectedAfterCursor, content, resource, cursorOffset);
		java.util.Collection<art.resource.artext.mopp.ArtextCompletionProposal> leftProposals = deriveProposals(expectedBeforeCursor, content, resource, cursorOffset);
		// second, the set of left proposals (i.e., the ones before the cursor) is
		// checked for emptiness. if the set is empty, the right proposals (i.e., 
		// the ones after the cursor are removed, because it does not make sense to
		// propose them until the element before the cursor was completed
		allProposals.addAll(leftProposals);
		if (leftProposals.isEmpty()) {
			allProposals.addAll(rightProposals);
		}
		// third, the proposals are sorted according to their relevance
		// proposals that matched the prefix are preferred over ones that did not
		// afterward proposals are sorted alphabetically
		final java.util.List<art.resource.artext.mopp.ArtextCompletionProposal> sortedProposals = new java.util.ArrayList<art.resource.artext.mopp.ArtextCompletionProposal>(allProposals);
		java.util.Collections.sort(sortedProposals);
		return sortedProposals.toArray(new art.resource.artext.mopp.ArtextCompletionProposal[sortedProposals.size()]);
	}
	
	public art.resource.artext.mopp.ArtextExpectedTerminal[] parseToExpectedElements(art.resource.artext.IArtextTextParser parser, art.resource.artext.IArtextTextResource resource) {
		final java.util.List<art.resource.artext.mopp.ArtextExpectedTerminal> expectedElements = parser.parseToExpectedElements(null, resource);
		if (expectedElements == null) {
			return new art.resource.artext.mopp.ArtextExpectedTerminal[0];
		}
		removeDuplicateEntries(expectedElements);
		removeInvalidEntriesAtEnd(expectedElements);
		return expectedElements.toArray(new art.resource.artext.mopp.ArtextExpectedTerminal[expectedElements.size()]);
	}
	
	private void removeDuplicateEntries(java.util.List<art.resource.artext.mopp.ArtextExpectedTerminal> expectedElements) {
		for (int i = 0; i < expectedElements.size() - 1; i++) {
			art.resource.artext.mopp.ArtextExpectedTerminal elementAtIndex = expectedElements.get(i);
			for (int j = i + 1; j < expectedElements.size();) {
				art.resource.artext.mopp.ArtextExpectedTerminal elementAtNext = expectedElements.get(j);
				if (elementAtIndex.equals(elementAtNext) && elementAtIndex.getStartExcludingHiddenTokens() == elementAtNext.getStartExcludingHiddenTokens()) {
					expectedElements.remove(j);
				} else {
					j++;
				}
			}
		}
	}
	
	private void removeInvalidEntriesAtEnd(java.util.List<art.resource.artext.mopp.ArtextExpectedTerminal> expectedElements) {
		for (int i = 0; i < expectedElements.size() - 1;) {
			art.resource.artext.mopp.ArtextExpectedTerminal elementAtIndex = expectedElements.get(i);
			art.resource.artext.mopp.ArtextExpectedTerminal elementAtNext = expectedElements.get(i + 1);
			if (elementAtIndex.getStartExcludingHiddenTokens() == elementAtNext.getStartExcludingHiddenTokens() && shouldRemove(elementAtIndex.getFollowSetID(), elementAtNext.getFollowSetID())) {
				expectedElements.remove(i + 1);
			} else {
				i++;
			}
		}
	}
	
	public boolean shouldRemove(int followSetID1, int followSetID2) {
		return followSetID1 != followSetID2;
	}
	
	private String findPrefix(java.util.List<art.resource.artext.mopp.ArtextExpectedTerminal> expectedElements, art.resource.artext.mopp.ArtextExpectedTerminal expectedAtCursor, String content, int cursorOffset) {
		if (cursorOffset < 0) {
			return "";
		}
		int end = 0;
		for (art.resource.artext.mopp.ArtextExpectedTerminal expectedElement : expectedElements) {
			if (expectedElement == expectedAtCursor) {
				final int start = expectedElement.getStartExcludingHiddenTokens();
				if (start >= 0  && start < Integer.MAX_VALUE) {
					end = start;
				}
				break;
			}
		}
		end = Math.min(end, cursorOffset);
		final String prefix = content.substring(end, Math.min(content.length(), cursorOffset));
		return prefix;
	}
	
	private java.util.Collection<art.resource.artext.mopp.ArtextCompletionProposal> deriveProposals(java.util.List<art.resource.artext.mopp.ArtextExpectedTerminal> expectedElements, String content, art.resource.artext.IArtextTextResource resource, int cursorOffset) {
		java.util.Collection<art.resource.artext.mopp.ArtextCompletionProposal> resultSet = new java.util.HashSet<art.resource.artext.mopp.ArtextCompletionProposal>();
		for (art.resource.artext.mopp.ArtextExpectedTerminal expectedElement : expectedElements) {
			resultSet.addAll(deriveProposals(expectedElement, content, resource, cursorOffset));
		}
		return resultSet;
	}
	
	private java.util.Collection<art.resource.artext.mopp.ArtextCompletionProposal> deriveProposals(art.resource.artext.mopp.ArtextExpectedTerminal expectedTerminal, String content, art.resource.artext.IArtextTextResource resource, int cursorOffset) {
		art.resource.artext.mopp.ArtextMetaInformation metaInformation = resource.getMetaInformation();
		art.resource.artext.IArtextLocationMap locationMap = resource.getLocationMap();
		art.resource.artext.IArtextExpectedElement expectedElement = (art.resource.artext.IArtextExpectedElement) expectedTerminal.getTerminal();
		if (expectedElement instanceof art.resource.artext.mopp.ArtextExpectedCsString) {
			art.resource.artext.mopp.ArtextExpectedCsString csString = (art.resource.artext.mopp.ArtextExpectedCsString) expectedElement;
			return deriveProposal(csString, content, expectedTerminal.getPrefix(), cursorOffset);
		} else if (expectedElement instanceof art.resource.artext.mopp.ArtextExpectedStructuralFeature) {
			art.resource.artext.mopp.ArtextExpectedStructuralFeature expectedFeature = (art.resource.artext.mopp.ArtextExpectedStructuralFeature) expectedElement;
			org.eclipse.emf.ecore.EStructuralFeature feature = expectedFeature.getFeature();
			org.eclipse.emf.ecore.EClassifier featureType = feature.getEType();
			java.util.List<org.eclipse.emf.ecore.EObject> elementsAtCursor = locationMap.getElementsAt(cursorOffset);
			org.eclipse.emf.ecore.EObject container = null;
			// we need to skip the proxy elements at the cursor, because they are not the container for the reference we try to complete
			for (int i = 0; i < elementsAtCursor.size(); i++) {
				container = elementsAtCursor.get(i);
				if (!container.eIsProxy()) {
					break;
				}
			}
			if (feature instanceof org.eclipse.emf.ecore.EReference) {
				org.eclipse.emf.ecore.EReference reference = (org.eclipse.emf.ecore.EReference) feature;
				if (featureType instanceof org.eclipse.emf.ecore.EClass) {
					if (reference.isContainment()) {
						// the FOLLOW set should contain only non-containment references
						assert false;
					} else {
						return handleNCReference(metaInformation, container, reference, expectedTerminal.getPrefix());
					}
				}
			} else if (feature instanceof org.eclipse.emf.ecore.EAttribute) {
				org.eclipse.emf.ecore.EAttribute attribute = (org.eclipse.emf.ecore.EAttribute) feature;
				if (featureType instanceof org.eclipse.emf.ecore.EEnum) {
					org.eclipse.emf.ecore.EEnum enumType = (org.eclipse.emf.ecore.EEnum) featureType;
					return deriveProposals(expectedTerminal, enumType, content, cursorOffset);
				} else {
					// handle EAttributes (derive default value depending on
					// the type of the attribute, figure out token resolver, and
					// call deResolve())
					return handleAttribute(metaInformation, expectedFeature, container, attribute, expectedTerminal.getPrefix());
				}
			} else {
				// there should be no other subclass of EStructuralFeature
				assert false;
			}
		} else {
			// there should be no other class implementing IExpectedElement
			assert false;
		}
		return java.util.Collections.emptyList();
	}
	
	private java.util.Collection<art.resource.artext.mopp.ArtextCompletionProposal> deriveProposals(art.resource.artext.mopp.ArtextExpectedTerminal expectedElement, org.eclipse.emf.ecore.EEnum enumType, String content, int cursorOffset) {
		java.util.Collection<org.eclipse.emf.ecore.EEnumLiteral> enumLiterals = enumType.getELiterals();
		java.util.Collection<art.resource.artext.mopp.ArtextCompletionProposal> result = new java.util.HashSet<art.resource.artext.mopp.ArtextCompletionProposal>();
		for (org.eclipse.emf.ecore.EEnumLiteral literal : enumLiterals) {
			String proposal = literal.getLiteral();
			String prefix = expectedElement.getPrefix();
			if (matches(proposal, prefix)) {
				result.add(new art.resource.artext.mopp.ArtextCompletionProposal(proposal, prefix, !"".equals(prefix), true));
			}
		}
		return result;
	}
	
	private java.util.Collection<art.resource.artext.mopp.ArtextCompletionProposal> handleNCReference(art.resource.artext.mopp.ArtextMetaInformation metaInformation, org.eclipse.emf.ecore.EObject container, org.eclipse.emf.ecore.EReference reference, java.lang.String prefix) {
		// proposals for non-containment references are derived by calling the
		// reference resolver switch in fuzzy mode.
		art.resource.artext.IArtextReferenceResolverSwitch resolverSwitch = metaInformation.getReferenceResolverSwitch();
		art.resource.artext.IArtextReferenceResolveResult<org.eclipse.emf.ecore.EObject> result = new art.resource.artext.mopp.ArtextReferenceResolveResult<org.eclipse.emf.ecore.EObject>(true);
		resolverSwitch.resolveFuzzy(prefix, container, reference, 0, result);
		java.util.Collection<art.resource.artext.IArtextReferenceMapping<org.eclipse.emf.ecore.EObject>> mappings = result.getMappings();
		if (mappings != null) {
			java.util.Collection<art.resource.artext.mopp.ArtextCompletionProposal> resultSet = new java.util.HashSet<art.resource.artext.mopp.ArtextCompletionProposal>();
			for (art.resource.artext.IArtextReferenceMapping<org.eclipse.emf.ecore.EObject> mapping : mappings) {
				final String identifier = mapping.getIdentifier();
				// the proposal can be added without checking the prefix because this is
				// performed by the reference resolvers
				resultSet.add(new art.resource.artext.mopp.ArtextCompletionProposal(identifier, prefix, true, true));
			}
			return resultSet;
		}
		return java.util.Collections.emptyList();
	}
	
	private java.util.Collection<art.resource.artext.mopp.ArtextCompletionProposal> handleAttribute(art.resource.artext.mopp.ArtextMetaInformation metaInformation, art.resource.artext.mopp.ArtextExpectedStructuralFeature expectedFeature, org.eclipse.emf.ecore.EObject container, org.eclipse.emf.ecore.EAttribute attribute, java.lang.String prefix) {
		java.lang.Object defaultValue = getDefaultValue(attribute);
		if (defaultValue != null) {
			art.resource.artext.IArtextTokenResolverFactory tokenResolverFactory = metaInformation.getTokenResolverFactory();
			String tokenName = expectedFeature.getTokenName();
			if (tokenName != null) {
				art.resource.artext.IArtextTokenResolver tokenResolver = tokenResolverFactory.createTokenResolver(tokenName);
				if (tokenResolver != null) {
					String defaultValueAsString = tokenResolver.deResolve(defaultValue, attribute, container);
					java.util.Collection<art.resource.artext.mopp.ArtextCompletionProposal> resultSet = new java.util.HashSet<art.resource.artext.mopp.ArtextCompletionProposal>();
					if (matches(defaultValueAsString, prefix)) {
						resultSet.add(new art.resource.artext.mopp.ArtextCompletionProposal(defaultValueAsString, prefix, !"".equals(prefix), true));
					}
					return resultSet;
				}
			}
		}
		return java.util.Collections.emptyList();
	}
	
	private java.lang.Object getDefaultValue(org.eclipse.emf.ecore.EAttribute attribute) {
		String typeName = attribute.getEType().getName();
		if ("EString".equals(typeName)) {
			return "some" + art.resource.artext.util.ArtextStringUtil.capitalize(attribute.getName());
		}
		return attribute.getDefaultValue();
	}
	
	private java.util.Collection<art.resource.artext.mopp.ArtextCompletionProposal> deriveProposal(art.resource.artext.mopp.ArtextExpectedCsString csString, String content, String prefix, int cursorOffset) {
		String proposal = csString.getValue();
		java.util.Collection<art.resource.artext.mopp.ArtextCompletionProposal> result = new java.util.HashSet<art.resource.artext.mopp.ArtextCompletionProposal>();
		if (matches(proposal, prefix)) {
			result.add(new art.resource.artext.mopp.ArtextCompletionProposal(proposal, prefix, !"".equals(prefix), false));
		}
		return result;
	}
	
	// for each given expected elements the prefix is calculated
	// the prefix depends on the current document content, the cursor position, and
	// the position where the element is expected
	private void setPrefixes(java.util.List<art.resource.artext.mopp.ArtextExpectedTerminal> expectedElements, String content, int cursorOffset) {
		if (cursorOffset < 0) {
			return;
		}
		for (art.resource.artext.mopp.ArtextExpectedTerminal expectedElement : expectedElements) {
			java.lang.String prefix = findPrefix(expectedElements, expectedElement, content, cursorOffset);
			expectedElement.setPrefix(prefix);
		}
	}
	
	public art.resource.artext.mopp.ArtextExpectedTerminal[] getElementsExpectedAt(art.resource.artext.mopp.ArtextExpectedTerminal[] allExpectedElements, int cursorOffset) {
		java.util.List<art.resource.artext.mopp.ArtextExpectedTerminal> expectedAtCursor = new java.util.ArrayList<art.resource.artext.mopp.ArtextExpectedTerminal>();
		for (int i = 0; i < allExpectedElements.length; i++) {
			art.resource.artext.mopp.ArtextExpectedTerminal expectedElement = allExpectedElements[i];
			int startIncludingHidden = expectedElement.getStartIncludingHiddenTokens();
			int end = getEnd(allExpectedElements, i);
			if (cursorOffset >= startIncludingHidden && cursorOffset <= end) {
				expectedAtCursor.add(expectedElement);
			}
		}
		return expectedAtCursor.toArray(new art.resource.artext.mopp.ArtextExpectedTerminal[expectedAtCursor.size()]);
	}
	
	private int getEnd(art.resource.artext.mopp.ArtextExpectedTerminal[] allExpectedElements, int indexInList) {
		art.resource.artext.mopp.ArtextExpectedTerminal elementAtIndex = allExpectedElements[indexInList];
		int startIncludingHidden = elementAtIndex.getStartIncludingHiddenTokens();
		int startExcludingHidden = elementAtIndex.getStartExcludingHiddenTokens();
		for (int i = indexInList + 1; i < allExpectedElements.length; i++) {
			art.resource.artext.mopp.ArtextExpectedTerminal elementAtI = allExpectedElements[i];
			int startIncludingHiddenForI = elementAtI.getStartIncludingHiddenTokens();
			int startExcludingHiddenForI = elementAtI.getStartExcludingHiddenTokens();
			if (startIncludingHidden != startIncludingHiddenForI || startExcludingHidden != startExcludingHiddenForI) {
				return startIncludingHiddenForI - 1;
			}
		}
		return Integer.MAX_VALUE;
	}
	
	private boolean matches(java.lang.String proposal, java.lang.String prefix) {
		return (proposal.startsWith(prefix) || art.resource.artext.util.ArtextStringUtil.matchCamelCase(prefix, proposal) != null) && !proposal.equals(prefix);
	}
	
}
