/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package fr.tm.elibel.smartqvt.qvt.imperativeocl.validation;

import fr.tm.elibel.smartqvt.qvt.essentialocl.OclExpression;

import fr.tm.elibel.smartqvt.qvt.imperativeocl.LogExp;
import fr.tm.elibel.smartqvt.qvt.imperativeocl.SeverityKind;

/**
 * A sample validator interface for {@link fr.tm.elibel.smartqvt.qvt.imperativeocl.AssertExp}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AssertExpValidator {
	boolean validate();

	boolean validateAssertion(OclExpression value);
	boolean validateLog(LogExp value);
	boolean validateSeverity(SeverityKind value);
}
