/**
 * <copyright>
 * </copyright>
 *
 * $Id: ConcernValidator.java,v 1.1 2008-02-04 10:40:25 ftanguy Exp $
 */
package org.kermeta.model.interest.validation;

import org.eclipse.emf.common.util.EList;
import org.kermeta.model.interest.WorriedObject;

/**
 * A sample validator interface for {@link org.kermeta.model.interest.Concern}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConcernValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateListeners(EList<WorriedObject> value);
}
