/**
 * <copyright>
 * </copyright>
 *
 * $Id: WorriedObjectValidator.java,v 1.1 2008-02-04 10:40:25 ftanguy Exp $
 */
package org.kermeta.model.interest.validation;

import org.kermeta.interest.InterestedObject;

/**
 * A sample validator interface for {@link org.kermeta.model.interest.WorriedObject}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WorriedObjectValidator {
	boolean validate();

	boolean validateTarget(InterestedObject value);
}
