<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MARTE_Library"
    nsURI="http:///MARTE_Library.ecore" nsPrefix="MARTE_Library">
  <eSubpackages name="GRM_BasicTypes" nsURI="http:///MARTE_Library/GRM_BasicTypes.ecore"
      nsPrefix="MARTE_Library.GRM_BasicTypes">
    <eClassifiers xsi:type="ecore:EClass" name="TableEntryType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="entryKey" ordered="false"
          eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//OpaqueExpression"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
