<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test"
    nsURI="http://test" nsPrefix="test">
  <eClassifiers xsi:type="ecore:EClass" name="MustBeGenerated1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mustBeGenRef1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MustBeGenerated2" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="MustBeGenerated3">
    <eOperations name="op1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eParameters name="p1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="p2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MustBeGenerated5">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MustBeGenerated4">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref1">
      <eGenericType eClassifier="#//MustBeGenerated5">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref2">
      <eGenericType eClassifier="#//MustBeGenerated5">
        <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref3" eType="#//MustBeGenerated1"/>
  </eClassifiers>
</ecore:EPackage>
