/**
 * <copyright>
 * </copyright>
 *
 * $Id: BooleanLiteralValidator.java,v 1.1.1.1 2008-11-04 08:27:29 mclavreu Exp $
 */
package kompose.validation;


/**
 * A sample validator interface for {@link kompose.BooleanLiteral}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BooleanLiteralValidator {
	boolean validate();

	boolean validateValue(boolean value);
}
