<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ftm">
  <eSubpackages name="behavior">
    <eClassifiers xsi:type="ecore:EClass" name="JavaStaticCall" eSuperTypes="#//behavior/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//behavior/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="jclass" eType="#//structure/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="jmethod" eType="#//structure/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  </eSubpackages>
  <eSubpackages name="structure">
    <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
  </eSubpackages>
</ecore:EPackage>
