<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="org"
    nsURI="org" nsPrefix="org">
  <eSubpackages name="kermeta" nsURI="kermeta" nsPrefix="kermeta">
    <eSubpackages name="trek" nsURI="trek" nsPrefix="trek">
      <eClassifiers xsi:type="ecore:EClass" name="UseKaseModel">
        <eStructuralFeatures xsi:type="ecore:EReference" name="kuseCases" upperBound="-1"
            eType="#//kermeta/trek/KUseCase" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="ktestCases" upperBound="-1"
            eType="#//kermeta/trek/KTestCase" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="ktags" upperBound="-1"
            eType="#//kermeta/trek/KTestCase" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="KuserStories" upperBound="-1"
            eType="#//kermeta/trek/KUserStory" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="KUseCase">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            iD="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="summary" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortSummary" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="use" upperBound="-1"
            eType="#//kermeta/trek/KUseCase" eOpposite="#//kermeta/trek/KUseCase/usedBy"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="usedBy" upperBound="-1"
            eType="#//kermeta/trek/KUseCase" eOpposite="#//kermeta/trek/KUseCase/use"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="verifiedBy" upperBound="-1"
            eType="#//kermeta/trek/KTestCase"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="refines" eType="#//kermeta/trek/KUseCase"
            eOpposite="#//kermeta/trek/KUseCase/refinedBy"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="refinedBy" upperBound="-1"
            eType="#//kermeta/trek/KUseCase" eOpposite="#//kermeta/trek/KUseCase/refines"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="covers" upperBound="-1"
            eType="#//kermeta/trek/KUserStory" eOpposite="#//kermeta/trek/KUserStory/coveredBy"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" lowerBound="1"
            eType="#//kermeta/trek/KUseLevel"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="tags" upperBound="-1"
            eType="#//kermeta/trek/KTagElement"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="KTestCase">
        <eStructuralFeatures xsi:type="ecore:EReference" name="verifies" eType="#//kermeta/trek/KUseCase"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="testCase" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="KUserStory">
        <eStructuralFeatures xsi:type="ecore:EReference" name="coveredBy" upperBound="-1"
            eType="#//kermeta/trek/KUseCase" eOpposite="#//kermeta/trek/KUseCase/covers"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            iD="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="summary" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortSummary" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="KUseLevel">
        <eLiterals name="Implementation" value="1"/>
        <eLiterals name="Unknown"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="KTagElement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="concept" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
