<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ftm">
  <eSubpackages name="structure">
    <eClassifiers xsi:type="ecore:EClass" name="Object">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tag" upperBound="-1"
          eType="#//structure/Tag" eOpposite="#//structure/Tag/object"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTags" upperBound="-1"
          eType="#//structure/Tag" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Tag">
      <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1"
          upperBound="-1" eType="#//structure/Object" eOpposite="#//structure/Object/tag"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
