<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ftm"
    nsURI="http://ftm" nsPrefix="ftm">
  <eSubpackages name="structure">
    <eClassifiers xsi:type="ecore:EClass" name="Object"/>
    <eClassifiers xsi:type="ecore:EClass" name="GenericTypeDefinition" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClassDefinition" eSuperTypes="#//structure/GenericTypeDefinition"/>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterizedType" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="virtualTypeBinding" upperBound="-1"
          eType="#//structure/TypeVariableBinding" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="To be written"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeVariable" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectTypeVariable" eSuperTypes="#//structure/TypeVariable"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypeVariableBinding"/>
    <eClassifiers xsi:type="ecore:EClass" name="ModelType" eSuperTypes="#//structure/Type #//structure/TypeDefinition">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Type of a model, consisting of a set of included type definitions"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="includedTypeDefinition"
          upperBound="-1" eType="#//structure/TypeDefinition">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="To be written"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelTypeVariable" eSuperTypes="#//structure/TypeVariable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="To be written"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="virtualType" upperBound="-1"
          eType="#//structure/VirtualType" containment="true" eOpposite="#//structure/VirtualType/modelType">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="To be written"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VirtualType" eSuperTypes="#//structure/ObjectTypeVariable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="To be written"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="classDefinition" lowerBound="1"
          eType="#//structure/ClassDefinition">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="To be written"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="modelType" lowerBound="1"
          eType="#//structure/ModelTypeVariable" eOpposite="#//structure/ModelTypeVariable/virtualType">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="To be written"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeParamBinding" upperBound="-1"
          eType="#//structure/TypeVariableBinding" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="To be written"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//structure/Object">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Is the holder of a set of model elements (Object) that are compatible with the ModelType that has &#xA;instantiated this Model."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
          eType="#//structure/Object" changeable="false">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Contents of this model..."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="boolean"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypeDefinition"/>
  </eSubpackages>
</ecore:EPackage>
