<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ftm"
    nsURI="http://ftm" nsPrefix="ftm">
  <eSubpackages name="structure" nsPrefix="ftm/structure">
    <eClassifiers xsi:type="ecore:EClass" name="TypeContainer" abstract="true" eSuperTypes="#//structure/Object">
      <eStructuralFeatures xsi:type="ecore:EReference" name="containedType" upperBound="-1"
          eType="#//structure/Type" containment="true" eOpposite="#//structure/Type/typeContainer">
        <eAnnotations source="kermeta">
          <details key="documentation" value="/**&#xA; * Contained types&#xA; */"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ClassDefinition" eSuperTypes="#//structure/TypeContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypedElement" eSuperTypes="#//structure/TypeContainer #//structure/NamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypeVariable" eSuperTypes="#//structure/TypeContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="ProductType" eSuperTypes="#//structure/TypeContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="FunctionType" eSuperTypes="#//structure/TypeContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="Object"/>
    <eClassifiers xsi:type="ecore:EClass" name="Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeContainer" eType="#//structure/TypeContainer"
          eOpposite="#//structure/TypeContainer/containedType">
        <eAnnotations source="kermeta">
          <details key="documentation" value="/**&#xA; * Owning TypeContainer, if any&#xA; */"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeVariableBinding" eSuperTypes="#//structure/TypeContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" eSuperTypes="#//structure/TypeContainer"/>
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement"/>
  </eSubpackages>
</ecore:EPackage>
