package fr.irisa.triskell.kermeta.ast;

import antlr.Token;

/**
 *
 * @generated by Gymnast from kermeta.ast on 28 juin 2007 17:24:33
 */
public class PropertyKind extends KermetaTokenNode {

	public static final String KW_ATTRIBUTE = "attribute";
	public static final String KW_REFERENCE = "reference";
	public static final String KW_PROPERTY = "property";

	
	/**
	 * Construct a new PropertyKind.
	 */
	public PropertyKind(Token token) {
		super(token);
	}

	/**
	 * This method overrides the superclass <code>acceptImpl</code> providing
	 * the same implementation.  Here <code>this</code> refers to this specific node
	 * class, so the <code>beginVisit</code> and <code>endVisit</code> methods
	 * specific to this type in the visitor will be invoked.
	 */
	public void acceptImpl(KermetaASTNodeVisitor visitor) {
		boolean visitChildren = visitor.beginVisit(this);
		if (visitChildren) visitChildren(visitor);
		visitor.endVisit(this);
	}

}