/**
 * <copyright>
 * </copyright>
 *
 * $Id: LogValidator.java,v 1.1 2008-07-02 09:43:57 ftanguy Exp $
 */
package kermeta.kunit.validation;

import kermeta.kunit.Failure;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link kermeta.kunit.Log}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LogValidator {
	boolean validate();

	boolean validateFailures(EList<Failure> value);
	boolean validateErrors(EList<kermeta.kunit.Error> value);
	boolean validateRuntests(int value);
	boolean validateHarnessErrors(EList<kermeta.kunit.Error> value);
}
