<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fsm"
    nsURI="platform:/resource/fr.irisa.triskell.kermeta.tests/test/interpreter/emf_testcases/metamodels/055_MT_FSM_basic_fsm_type.ecore"
    nsPrefix="fsm">
  <eAnnotations source="kermeta">
    <details key="mainClass" value="fsm::FSM"/>
    <details key="mainOperation" value=""/>
  </eAnnotations>
  <eAnnotations source="kermeta.req">
    <details key="platform:/plugin/fr.irisa.triskell.kermeta/lib/framework.km" value="platform:/plugin/fr.irisa.triskell.kermeta/lib/framework.km"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="FSMException" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NonDeterminism" eSuperTypes="#//FSMException"/>
  <eClassifiers xsi:type="ecore:EClass" name="NoTransition" eSuperTypes="#//FSMException"/>
  <eClassifiers xsi:type="ecore:EClass" name="NoInitialStateException" eSuperTypes="#//FSMException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
  <eSubpackages name="basic_fsm" nsURI="platform:/resource/fr.irisa.triskell.kermeta.tests/test/interpreter/emf_testcases/metamodels/055_MT_FSM_basic_fsm_type.ecore#/"
      nsPrefix="basic_fsm">
    <eAnnotations source="kermeta">
      <details key="isModelTypeDefinition" value="true"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="FSM">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="alphabet" ordered="false"
          upperBound="-1" eType="#//String">
        <eAnnotations source="kermeta">
          <details key="isComposite" value="true"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedState" ordered="false"
          upperBound="-1" eType="#//basic_fsm/State" containment="true" eOpposite="#//basic_fsm/State/owningFSM"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTransition" ordered="false"
          upperBound="-1" eType="#//basic_fsm/Transition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initialState" eType="#//basic_fsm/State"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="finalState" ordered="false"
          upperBound="-1" eType="#//basic_fsm/State"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="State">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//String">
        <eAnnotations source="kermeta">
          <details key="isComposite" value="true"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningFSM" eType="#//basic_fsm/FSM"
          eOpposite="#//basic_fsm/FSM/ownedState"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingTransition" upperBound="-1"
          eType="#//basic_fsm/Transition" eOpposite="#//basic_fsm/Transition/target"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingTransition" upperBound="-1"
          eType="#//basic_fsm/Transition" eOpposite="#//basic_fsm/Transition/source"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Transition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="input" eType="#//String">
        <eAnnotations source="kermeta">
          <details key="isComposite" value="true"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="#//String">
        <eAnnotations source="kermeta">
          <details key="isComposite" value="true"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//basic_fsm/State"
          eOpposite="#//basic_fsm/State/outgoingTransition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//basic_fsm/State"
          eOpposite="#//basic_fsm/State/incomingTransition"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
