/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package fr.tm.elibel.smartqvt.qvt.qvtrelation.validation;

import fr.tm.elibel.smartqvt.qvt.emof.Operation;

import fr.tm.elibel.smartqvt.qvt.qvtbase.TypedModel;

import fr.tm.elibel.smartqvt.qvt.qvtrelation.Relation;

/**
 * A sample validator interface for {@link fr.tm.elibel.smartqvt.qvt.qvtrelation.RelationImplementation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RelationImplementationValidator {
	boolean validate();

	boolean validateImpl(Operation value);
	boolean validateInDirectionOf(TypedModel value);
	boolean validateRelation(Relation value);
}
