/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package fr.tm.elibel.smartqvt.qvt.qvtrelation.validation;

import fr.tm.elibel.smartqvt.qvt.qvtbase.Pattern;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link fr.tm.elibel.smartqvt.qvt.qvtrelation.Relation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RelationValidator {
	boolean validate();

	boolean validateIsTopLevel(Boolean value);
	boolean validateOperationalImpl(EList value);
	boolean validateVariable(EList value);
	boolean validateWhen(Pattern value);
	boolean validateWhere(Pattern value);
}
