<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="persistence" nsURI="fr.irisa.triskell.kermeta.io.persistence" nsPrefix="fr.irisa.triskell.kermeta.io.persistence">
  <eClassifiers xsi:type="ecore:EClass" name="Resource" abstract="true">
    <eOperations name="save">
      <eAnnotations source="blablabla" references="//Resource/save"/>
    </eOperations>
    <eOperations name="load"/>
    <eOperations name="getContents">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
    </eOperations>
    <eOperations name="manageInstance">
      <eParameters name="instance" eType="//Object"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaModelURI" eType="//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includedResources" eType="//URICollection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFResource" eSuperTypes="//Resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="KMResource" eSuperTypes="//Resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="Repository" abstract="true">
    <eOperations name="createResource" eType="//Resource">
      <eParameters name="pUri" eType="//String"/>
    </eOperations>
    <eOperations name="getResource" eType="//Resource">
      <eParameters name="pUri" eType="//String"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resources" eType="//ResourceHashtable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFRepository" eSuperTypes="//Repository"/>
  <eClassifiers xsi:type="ecore:EClass" name="KMRepository" eSuperTypes="//Repository"/>
  <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="kermeta::standard::String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="URICollection" instanceClassName="kermeta::standard::Collection&lt;String>"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ResourceHashtable" instanceClassName="kermeta::utils::Hashtable&lt;String, Resource>">
    <eAnnotations source="String, Resource" references="//ResourceHashtable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Object" instanceClassName="kermeta::language::structure::Object"/>
</ecore:EPackage>
