/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package fr.tm.elibel.smartqvt.qvt.qvtoperational.validation;

import fr.tm.elibel.smartqvt.qvt.essentialocl.Variable;

import fr.tm.elibel.smartqvt.qvt.qvtoperational.ConstructorBody;

/**
 * A sample validator interface for {@link fr.tm.elibel.smartqvt.qvt.qvtoperational.ObjectExp}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ObjectExpValidator {
	boolean validate();

	boolean validateBody(ConstructorBody value);
	boolean validateReferredObject(Variable value);
}
