/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package fr.tm.elibel.smartqvt.qvt.qvtoperational.validation;

import fr.tm.elibel.smartqvt.qvt.qvtrelation.RelationalTransformation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link fr.tm.elibel.smartqvt.qvt.qvtoperational.OperationalTransformation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OperationalTransformationValidator {
	boolean validate();

	boolean validateIntermediateClass(EList value);
	boolean validateIntermediateProperty(EList value);
	boolean validateModelParameter(EList value);
	boolean validateRefined(RelationalTransformation value);
	boolean validateRelation(EList value);
}
