/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package fr.tm.elibel.smartqvt.qvt.qvtoperational.validation;

import fr.tm.elibel.smartqvt.qvt.qvtoperational.DirectionKind;
import fr.tm.elibel.smartqvt.qvt.qvtoperational.ImperativeOperation;

/**
 * A sample validator interface for {@link fr.tm.elibel.smartqvt.qvt.qvtoperational.VarParameter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VarParameterValidator {
	boolean validate();

	boolean validateCtxOwner(ImperativeOperation value);
	boolean validateKind(DirectionKind value);
	boolean validateResOwner(ImperativeOperation value);
}
