<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EAnnotation source="ModelingUnit">
    <details key="require" value="../Standard.kmt|"/>
    <details key="using" value="kermeta::standard|kermeta::language::structure|kermeta::exceptions|"/>
  </ecore:EAnnotation>
  <ecore:EPackage name="kermeta" nsURI="file:/C:/eclipse3.3M5/eclipse/workspace/fr.irisa.triskell.kermeta.framework/dist/standard/primitive_types.ecore#/" nsPrefix="kermeta">
    <eSubpackages name="standard" nsURI="http://www.kermeta.org/kermeta/standard" nsPrefix="standard">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/**&#xD;&#xA; * Defines primitive types &#xD;&#xA; * &lt;img src=&quot;platform:/plugin/fr.irisa.triskell.kermeta.documentation/src/figures/primitive_types_view.png&quot;>&#xD;&#xA; */"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EClass" name="Void">
        <eAnnotations source="kermeta">
          <details key="documentation" value="/**&#xD;&#xA; * The class Void &#xD;&#xA; * By convention it is a sub-type of everything&#xD;&#xA; */"/>
        </eAnnotations>
        <eSuperTypes href="../language/structure.ecore#/1/language/structure/Object"/>
        <eOperations name="isVoid">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result := true&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Return true&#xD;&#xA;  */"/>
          </eAnnotations>
        </eOperations>
        <eOperations name="toString">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result := &quot;&lt;void>&quot;&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Returns the String identifier '&lt;void>'&#xD;&#xA;  */"/>
          </eAnnotations>
        </eOperations>
        <eOperations name="isInstanceOf">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result := true&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Returns true&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="type">
            <eType xsi:type="ecore:EClass" href="../language/structure.ecore#/1/language/structure/Type"/>
          </eParameters>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" abstract="true">
        <eAnnotations source="kermeta">
          <details key="documentation" value="/**&#xD;&#xA; * Used for PrimitiveTypes like Integer,String, boolean&#xD;&#xA; */"/>
        </eAnnotations>
        <eSuperTypes href="../language/structure.ecore#/1/language/structure/Object"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ValueType" abstract="true">
        <eAnnotations source="kermeta">
          <details key="documentation" value="/**&#xD;&#xA; * The abstract class ValueType does not contain any feature.&#xD;&#xA; * However, any instance of a sub-class of ValueType will be passed by value &#xD;&#xA; * instead of by reference for any other objects.&#xD;&#xA; * that means that each time you := such object it will call the clone function associated to it (Not implemented yet except for Integer, String and boolean!!!)&#xD;&#xA; * &#xD;&#xA; */"/>
        </eAnnotations>
        <eSuperTypes href="#/1/standard/PrimitiveType"/>
        <eSuperTypes href="../language/structure.ecore#/1/language/structure/Object"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Comparable" abstract="true">
        <eAnnotations source="kermeta">
          <details key="documentation" value="/**&#xD;&#xA; * The abstract class Comparable defines a set of operation&#xD;&#xA; * to compare instances of a class.&#xD;&#xA; * Sub-classes only has to implement abstract operation compareTo.&#xD;&#xA; * All other methods are defined w.r.t. the compareTo operation&#xD;&#xA; */"/>
        </eAnnotations>
        <eSuperTypes href="../language/structure.ecore#/1/language/structure/Object"/>
        <eOperations name="compareTo">
          <eAnnotations source="kermeta">
            <details key="isAbstract" value="true"/>
            <details key="documentation" value="/**&#xD;&#xA;  * This method should be implemented by any class that inherits&#xD;&#xA;  * from Comparable.&#xD;&#xA;  * returns 0 if self = other&#xD;&#xA;  * returns > 0 if  self > other&#xD;&#xA;  * returns &lt; 0 if  self &lt; other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other">
            <eType xsi:type="ecore:EDataType" href="collections.ecore#/1/standard/Object"/>
          </eParameters>
        </eOperations>
        <eOperations name="isGreater">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result := ((self.compareTo(other)) > (0))&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * return true if self > other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other">
            <eType xsi:type="ecore:EDataType" href="collections.ecore#/1/standard/Object"/>
          </eParameters>
        </eOperations>
        <eOperations name="isLower">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result := ((self.compareTo(other)) &lt; (0))&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * return true if self &lt; other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other">
            <eType xsi:type="ecore:EDataType" href="collections.ecore#/1/standard/Object"/>
          </eParameters>
        </eOperations>
        <eOperations name="isLowerOrEqual">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result := ((self.compareTo(other)) &lt;= (0))&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * return true if self &lt;= other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other">
            <eType xsi:type="ecore:EDataType" href="collections.ecore#/1/standard/Object"/>
          </eParameters>
        </eOperations>
        <eOperations name="isGreaterOrEqual">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result := ((self.compareTo(other)) >= (0))&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * return true if self >= other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other">
            <eType xsi:type="ecore:EDataType" href="collections.ecore#/1/standard/Object"/>
          </eParameters>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Summable" abstract="true">
        <eAnnotations source="kermeta">
          <details key="documentation" value="/**&#xD;&#xA; * The abstract class Summable defines a set of operation&#xD;&#xA; * to sum instances of a class.&#xD;&#xA; * Sub-classes only has to implement abstract operation plus.&#xD;&#xA;  */"/>
        </eAnnotations>
        <eTypeParameters name="G"/>
        <eSuperTypes href="../language/structure.ecore#/1/language/structure/Object"/>
        <eOperations name="plus">
          <eAnnotations source="kermeta">
            <details key="isAbstract" value="true"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Summarization method to be implemented by any summable class.&#xD;&#xA;  * The parameter must have the same type (or one of its subtypes)&#xD;&#xA;  *  than the current object .&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other">
            <eGenericType eTypeParameter="/1/standard/Summable/G"/>
          </eParameters>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="NotComparableException">
        <eAnnotations source="kermeta">
          <details key="documentation" value="/**&#xD;&#xA; * raised when two objects are not comparable&#xD;&#xA; */"/>
        </eAnnotations>
        <eSuperTypes href="../exceptions/exceptions.ecore#/1/exceptions/Exception"/>
        <eSuperTypes href="../language/structure.ecore#/1/language/structure/Object"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Boolean">
        <eAnnotations source="kermeta">
          <details key="documentation" value="/**&#xD;&#xA; * The Boolean type&#xD;&#xA; */"/>
        </eAnnotations>
        <eSuperTypes href="#/1/standard/PrimitiveType"/>
        <eSuperTypes href="../language/structure.ecore#/1/language/structure/Object"/>
        <eOperations name="equals">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.getMetaClass.isNotEqual(kermeta::standard::Boolean) then&#xA;&#x9;&#x9;result := false&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Boolean.equals(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Returns true if &lt;code>other&lt;/code> type is Boolean&#xD;&#xA;  * and has the same boolean value than current object.&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other">
            <eType xsi:type="ecore:EDataType" href="collections.ecore#/1/standard/Object"/>
          </eParameters>
        </eOperations>
        <eOperations name="and">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Boolean.~and(self, other)&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * return self and other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other" eType="/1/standard/Boolean"/>
        </eOperations>
        <eOperations name="not">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Boolean.~not(self)&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * return not self&#xD;&#xA;  */"/>
          </eAnnotations>
        </eOperations>
        <eOperations name="or">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Boolean.~or(self, other)&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * return self or other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other" eType="/1/standard/Boolean"/>
        </eOperations>
        <eOperations name="implies">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result := not (((not (((self) and (other)))) and (self)))&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * return self implies other&#xD;&#xA;  * meaning : not( (not (self and other)) and self)&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other" eType="/1/standard/Boolean"/>
        </eOperations>
        <eOperations name="xor">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result := ((((self) and (not (other)))) or (((not (self)) and (other))))&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * return self xor other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other" eType="/1/standard/Boolean"/>
        </eOperations>
        <eOperations name="nand">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result := not (((self) and (other)))&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * return self nand other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other" eType="/1/standard/Boolean"/>
        </eOperations>
        <eOperations name="toString">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result := if self then&#xA;&#x9;&#x9;&quot;true&quot;&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;&quot;false&quot;&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Returns 'true' or 'false', depending on self  value&#xD;&#xA;  */"/>
          </eAnnotations>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Numeric" abstract="true">
        <eAnnotations source="kermeta">
          <details key="documentation" value="/**&#xD;&#xA; * The abstract class Numeric is the root class for all&#xD;&#xA; * numeric types&#xD;&#xA; */"/>
        </eAnnotations>
        <eSuperTypes href="#/1/standard/Comparable"/>
        <eSuperTypes href="#/1/standard/ValueType"/>
        <eSuperTypes href="../language/structure.ecore#/1/language/structure/Object"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Integer">
        <eAnnotations source="kermeta">
          <details key="documentation" value="/**&#xD;&#xA; * The class Integer&#xD;&#xA; */"/>
        </eAnnotations>
        <eSuperTypes href="#/1/standard/Numeric"/>
        <eSuperTypes href="#/1/standard/Summable"/>
        <eSuperTypes href="../language/structure.ecore#/1/language/structure/Object"/>
        <eOperations name="times">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;from var i : kermeta::standard::Integer init 0&#xA;&#x9;until i.equals(self)&#xA;&#x9;loop&#xA;&#x9;&#x9;body(i)&#xA;&#x9;&#x9;i := ((i) + (1))&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Iteration&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="body">
            <eAnnotations source="kermeta.functionType">
              <details key="0" value="kermeta::standard::Integer"/>
              <details key="1" value="alias Object : kermeta::language::structure::Object;"/>
            </eAnnotations>
            <eType xsi:type="ecore:EDataType" href="../Standard.ecore#/1/_KermetaSpecialTypesAlias_"/>
          </eParameters>
        </eOperations>
        <eOperations name="compareTo">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.getMetaClass.isNotEqual(kermeta::standard::Integer) then&#xA;&#x9;&#x9;if other.getMetaClass.equals(kermeta::standard::Real) then&#xA;&#x9;&#x9;&#x9;result := self.toReal.compareTo(other)&#xA;&#xA;&#x9;&#x9;else&#xA;&#x9;&#x9;&#x9;raise kermeta::standard::NotComparableException.new&#xA;&#xA;&#x9;&#x9;end&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Integer.compareTo(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Comparison&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other">
            <eType xsi:type="ecore:EDataType" href="collections.ecore#/1/standard/Object"/>
          </eParameters>
        </eOperations>
        <eOperations name="equals">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.getMetaClass.isNotEqual(kermeta::standard::Integer) then&#xA;&#x9;&#x9;if other.getMetaClass.equals(kermeta::standard::Real) then&#xA;&#x9;&#x9;&#x9;result := self.toReal.equals(other)&#xA;&#xA;&#x9;&#x9;else&#xA;&#x9;&#x9;&#x9;result := false&#xA;&#xA;&#x9;&#x9;end&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Integer.equals(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Returns true if &lt;code>other&lt;/code> type is Integer or Real&#xD;&#xA;  * and has the same numeric value than current object.&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other">
            <eType xsi:type="ecore:EDataType" href="collections.ecore#/1/standard/Object"/>
          </eParameters>
        </eOperations>
        <eOperations name="plus">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.isVoid then&#xA;&#x9;&#x9;raise kermeta::exceptions::VoidOperandError.new&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Integer.plus(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * returns self + other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other" eType="/1/standard/Integer"/>
        </eOperations>
        <eOperations name="minus">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.isVoid then&#xA;&#x9;&#x9;raise kermeta::exceptions::VoidOperandError.new&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Integer.minus(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * returns self - other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other" eType="/1/standard/Integer"/>
        </eOperations>
        <eOperations name="mult">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.isVoid then&#xA;&#x9;&#x9;raise kermeta::exceptions::VoidOperandError.new&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Integer.times(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * returns self * other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other" eType="/1/standard/Integer"/>
        </eOperations>
        <eOperations name="div">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.equals(0) then&#xA;&#x9;&#x9;raise kermeta::exceptions::DivisionByZero.new&#xA;&#xA;&#x9;end&#xA;&#x9;if other.isVoid then&#xA;&#x9;&#x9;raise kermeta::exceptions::VoidOperandError.new&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Integer.div(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * returns self / other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other" eType="/1/standard/Integer"/>
        </eOperations>
        <eOperations name="mod">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.equals(0) then&#xA;&#x9;&#x9;raise kermeta::exceptions::DivisionByZero.new&#xA;&#xA;&#x9;end&#xA;&#x9;if other.isVoid then&#xA;&#x9;&#x9;raise kermeta::exceptions::VoidOperandError.new&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Integer.mod(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * returns self modulo other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other" eType="/1/standard/Integer"/>
        </eOperations>
        <eOperations name="uminus">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result := ((0) - (self))&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * returns -self&#xD;&#xA;  */"/>
          </eAnnotations>
        </eOperations>
        <eOperations name="toReal">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Integer.toReal(self)&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Convert self as a Real&#xD;&#xA;  */"/>
          </eAnnotations>
        </eOperations>
        <eOperations name="isGreater">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.getMetaClass.isNotEqual(kermeta::standard::Integer) then&#xA;&#x9;&#x9;if other.getMetaClass.equals(kermeta::standard::Real) then&#xA;&#x9;&#x9;&#x9;result := ((self.toReal) > (other))&#xA;&#xA;&#x9;&#x9;else&#xA;&#x9;&#x9;&#x9;result := false&#xA;&#xA;&#x9;&#x9;end&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Integer.isGreater(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * return true if self > other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other">
            <eType xsi:type="ecore:EDataType" href="collections.ecore#/1/standard/Object"/>
          </eParameters>
        </eOperations>
        <eOperations name="isLower">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.getMetaClass.isNotEqual(kermeta::standard::Integer) then&#xA;&#x9;&#x9;if other.getMetaClass.equals(kermeta::standard::Real) then&#xA;&#x9;&#x9;&#x9;result := ((self.toReal) &lt; (other))&#xA;&#xA;&#x9;&#x9;else&#xA;&#x9;&#x9;&#x9;result := false&#xA;&#xA;&#x9;&#x9;end&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Integer.isLower(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * return true if self &lt; other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other">
            <eType xsi:type="ecore:EDataType" href="collections.ecore#/1/standard/Object"/>
          </eParameters>
        </eOperations>
        <eOperations name="isLowerOrEqual">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.getMetaClass.isNotEqual(kermeta::standard::Integer) then&#xA;&#x9;&#x9;if other.getMetaClass.equals(kermeta::standard::Real) then&#xA;&#x9;&#x9;&#x9;result := ((self.toReal) &lt;= (other))&#xA;&#xA;&#x9;&#x9;else&#xA;&#x9;&#x9;&#x9;result := false&#xA;&#xA;&#x9;&#x9;end&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Integer.isLowerOrEqual(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * return true if self &lt;= other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other">
            <eType xsi:type="ecore:EDataType" href="collections.ecore#/1/standard/Object"/>
          </eParameters>
        </eOperations>
        <eOperations name="isGreaterOrEqual">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.getMetaClass.isNotEqual(kermeta::standard::Integer) then&#xA;&#x9;&#x9;if other.getMetaClass.equals(kermeta::standard::Real) then&#xA;&#x9;&#x9;&#x9;result := ((self.toReal) >= (other))&#xA;&#xA;&#x9;&#x9;else&#xA;&#x9;&#x9;&#x9;result := false&#xA;&#xA;&#x9;&#x9;end&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Integer.isGreaterOrEqual(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * return true if self >= other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other">
            <eType xsi:type="ecore:EDataType" href="collections.ecore#/1/standard/Object"/>
          </eParameters>
        </eOperations>
        <eOperations name="toString">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Integer.toString(self)&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Numeric value in string format&#xD;&#xA;  */"/>
          </eAnnotations>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Real">
        <eAnnotations source="kermeta">
          <details key="documentation" value="/**&#xD;&#xA; * class Real&#xD;&#xA; */"/>
        </eAnnotations>
        <eSuperTypes href="#/1/standard/Numeric"/>
        <eSuperTypes href="#/1/standard/Summable"/>
        <eSuperTypes href="../language/structure.ecore#/1/language/structure/Object"/>
        <eOperations name="plus">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.isVoid then&#xA;&#x9;&#x9;raise kermeta::exceptions::VoidOperandError.new&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Real.plus(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * returns self + other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other" eType="/1/standard/Real"/>
        </eOperations>
        <eOperations name="minus">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.isVoid then&#xA;&#x9;&#x9;raise kermeta::exceptions::VoidOperandError.new&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Real.minus(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * returns self - other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other" eType="/1/standard/Real"/>
        </eOperations>
        <eOperations name="mult">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.isVoid then&#xA;&#x9;&#x9;raise kermeta::exceptions::VoidOperandError.new&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Real.times(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * returns self * other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other" eType="/1/standard/Real"/>
        </eOperations>
        <eOperations name="div">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.equals(0) then&#xA;&#x9;&#x9;raise kermeta::exceptions::DivisionByZero.new&#xA;&#xA;&#x9;end&#xA;&#x9;if other.isVoid then&#xA;&#x9;&#x9;raise kermeta::exceptions::VoidOperandError.new&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Real.div(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * returns self / other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other" eType="/1/standard/Real"/>
        </eOperations>
        <eOperations name="toInteger">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Real.toInteger(self)&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Convert self as an Integer&#xD;&#xA;  */"/>
          </eAnnotations>
        </eOperations>
        <eOperations name="compareTo">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.getMetaClass.isNotEqual(kermeta::standard::Real) then&#xA;&#x9;&#x9;if other.getMetaClass.equals(kermeta::standard::Integer) then&#xA;&#x9;&#x9;&#x9;result := self.compareTo(other.asType(kermeta::standard::Integer).toReal)&#xA;&#xA;&#x9;&#x9;else&#xA;&#x9;&#x9;&#x9;raise kermeta::standard::NotComparableException.new&#xA;&#xA;&#x9;&#x9;end&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Real.compareTo(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Comparison&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other">
            <eType xsi:type="ecore:EDataType" href="collections.ecore#/1/standard/Object"/>
          </eParameters>
        </eOperations>
        <eOperations name="equals">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.getMetaClass.isNotEqual(kermeta::standard::Real) then&#xA;&#x9;&#x9;if other.getMetaClass.equals(kermeta::standard::Integer) then&#xA;&#x9;&#x9;&#x9;result := self.equals(other.asType(kermeta::standard::Integer).toReal)&#xA;&#xA;&#x9;&#x9;else&#xA;&#x9;&#x9;&#x9;result := false&#xA;&#xA;&#x9;&#x9;end&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Real.equals(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Returns true if &lt;code>other&lt;/code> type is Integer or Real&#xD;&#xA;  * and has the same numeric value than current object.&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other">
            <eType xsi:type="ecore:EDataType" href="collections.ecore#/1/standard/Object"/>
          </eParameters>
        </eOperations>
        <eOperations name="uminus">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result := ((0.toReal) - (self))&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * returns -self&#xD;&#xA;  */"/>
          </eAnnotations>
        </eOperations>
        <eOperations name="toString">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Real.toString(self)&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Returns numeric value in string format&#xD;&#xA;  */"/>
          </eAnnotations>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Character">
        <eAnnotations source="kermeta">
          <details key="documentation" value="/**&#xD;&#xA; * The class Character&#xD;&#xA; */"/>
        </eAnnotations>
        <eSuperTypes href="#/1/standard/ValueType"/>
        <eSuperTypes href="#/1/standard/Comparable"/>
        <eSuperTypes href="../language/structure.ecore#/1/language/structure/Object"/>
        <eOperations name="compareTo">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.isVoid then&#xA;&#x9;&#x9;raise kermeta::exceptions::CallOnVoidTarget.new&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Character.compareTo(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Comparaison&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other">
            <eType xsi:type="ecore:EDataType" href="collections.ecore#/1/standard/Object"/>
          </eParameters>
        </eOperations>
        <eOperations name="equals">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.getMetaClass.isNotEqual(kermeta::standard::Character) then&#xA;&#x9;&#x9;result := false&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Character.equals(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Returns true if &lt;code>other&lt;/code> type is Character&#xD;&#xA;  * and has the same letter value than current object.&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other">
            <eType xsi:type="ecore:EDataType" href="collections.ecore#/1/standard/Object"/>
          </eParameters>
        </eOperations>
        <eOperations name="toString">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::Character.toString(self)&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Conversion from Character to String&#xD;&#xA;  */"/>
          </eAnnotations>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="String">
        <eAnnotations source="kermeta">
          <details key="documentation" value="/**&#xD;&#xA; * The class String&#xD;&#xA; */"/>
        </eAnnotations>
        <eSuperTypes href="#/1/standard/ValueType"/>
        <eSuperTypes href="#/1/standard/Comparable"/>
        <eSuperTypes href="#/1/standard/Summable"/>
        <eSuperTypes href="../language/structure.ecore#/1/language/structure/Object"/>
        <eOperations name="compareTo">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.isVoid then&#xA;&#x9;&#x9;raise kermeta::exceptions::CallOnVoidTarget.new&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::String.compareTo(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Comparaison&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other">
            <eType xsi:type="ecore:EDataType" href="collections.ecore#/1/standard/Object"/>
          </eParameters>
        </eOperations>
        <eOperations name="equals">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.getMetaClass.isNotEqual(kermeta::standard::String) then&#xA;&#x9;&#x9;result := false&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::String.equals(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Returns true if &lt;code>other&lt;/code> type is String&#xD;&#xA;  * and has the same string value than current object.&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other">
            <eType xsi:type="ecore:EDataType" href="collections.ecore#/1/standard/Object"/>
          </eParameters>
        </eOperations>
        <eOperations name="plus">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.isVoid then&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::String.plus(self, other.toString)&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::String.plus(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * returns a new string self + other&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other" eType="/1/standard/String"/>
        </eOperations>
        <eOperations name="append">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if other.isVoid then&#xA;&#x9;&#x9;raise kermeta::exceptions::CallOnVoidTarget.new&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;extern fr::irisa::triskell::kermeta::runtime::basetypes::String.append(self, other)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Appends other at the end of self&#xD;&#xA;  * A more efficient method is kermeta::utils::StringBuffer::append(other)&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="other" eType="/1/standard/String"/>
        </eOperations>
        <eOperations name="elementAt">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if ((((index) &lt; (0))) or (((index) > (((size) - (1)))))) then&#xA;&#x9;&#x9;raise kermeta::exceptions::StringIndexOutOfBound.new&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::String.elementAt(self, index)&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * returns the character at index in the String&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="index" eType="/1/standard/Integer"/>
        </eOperations>
        <eOperations name="indexOf">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::String.indexOf(self, str)&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * returns the index within this string of the first &#xD;&#xA;  * occurrence of the specified substring&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="str" eType="/1/standard/String"/>
        </eOperations>
        <eOperations name="substring">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;if ((((((((startIndex) >= (0))) and (((startIndex) &lt;= (size))))) and (((endIndex) &lt;= (size))))) and (((endIndex) >= (startIndex)))) then&#xA;&#x9;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::String.substring(self, startIndex, endIndex)&#xA;&#xA;&#x9;else&#xA;&#x9;&#x9;raise kermeta::exceptions::StringIndexOutOfBound.new&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * returns a new string that is a substring of this string&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="startIndex" eType="/1/standard/Integer"/>
          <eParameters name="endIndex" eType="/1/standard/Integer"/>
        </eOperations>
        <eOperations name="size">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::String.size(self)&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * returns the number of characters in the current String&#xD;&#xA;  */"/>
          </eAnnotations>
        </eOperations>
        <eOperations name="toString">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result := self&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * returns the string itself&#xD;&#xA;  */"/>
          </eAnnotations>
        </eOperations>
        <eOperations name="replace">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::String.replace(self, str1, str2)&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Replaces all occurences of str1 in the current string by the string str2&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="str1" eType="/1/standard/String"/>
          <eParameters name="str2" eType="/1/standard/String"/>
        </eOperations>
        <eOperations name="toLowerCase">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::String.toLowerCase(self)&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Return the current string in lower case&#xD;&#xA;  */"/>
          </eAnnotations>
        </eOperations>
        <eOperations name="toUpperCase">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::String.toUpperCase(self)&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Return the current string in upper case&#xD;&#xA;  */"/>
          </eAnnotations>
        </eOperations>
        <eOperations name="contains" eType="/1/standard/Boolean">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::String.contains(self, str1)&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Return if a string is contained by another string&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="str1" eType="/1/standard/String"/>
        </eOperations>
        <eOperations name="split">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::String.split(self, delimiter)&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Return of an ordered set of the splitted string&#xD;&#xA;  */"/>
          </eAnnotations>
          <eParameters name="delimiter" eType="/1/standard/String"/>
        </eOperations>
        <eOperations name="toBoolean">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::String.toBoolean(self)&#xA;&#x9;if result.isVoid then&#xA;&#x9;&#x9;raise kermeta::exceptions::StringFormatException.new&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Parses the current string and returns true if the string is &quot;true&quot; and false if the string is &quot;false&quot;&#xD;&#xA;  * The parsing is not case sensitive and if no boolean value is recognized then a StringFormatException is raised.&#xD;&#xA;  */"/>
          </eAnnotations>
        </eOperations>
        <eOperations name="toInteger">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::String.toInteger(self)&#xA;&#x9;if result.isVoid then&#xA;&#x9;&#x9;raise kermeta::exceptions::StringFormatException.new&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Parses the current string into an integer.&#xD;&#xA;  * if no integer value is recognized then a StringFormatException is raised.&#xD;&#xA;  */"/>
          </eAnnotations>
        </eOperations>
        <eOperations name="toReal">
          <eAnnotations source="kermeta">
            <details key="body" value="do&#xA;&#x9;result ?= extern fr::irisa::triskell::kermeta::runtime::basetypes::String.toReal(self)&#xA;&#x9;if result.isVoid then&#xA;&#x9;&#x9;raise kermeta::exceptions::StringFormatException.new&#xA;&#xA;&#x9;end&#xA;end"/>
            <details key="documentation" value="/**&#xD;&#xA;  * Parses the current string into a real.&#xD;&#xA;  * if no real value is recognized then a StringFormatException is raised.&#xD;&#xA;  */"/>
          </eAnnotations>
        </eOperations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EDataType" name="UnlimitedNatural" instanceClassName="java.lang.Object">
        <eAnnotations source="kermeta">
          <details key="alias" value="kermeta::standard::Integer"/>
          <details key="documentation" value="/**&#xD;&#xA; * Unlimited natural is used for reflection.&#xD;&#xA; * It is mapped to integer.equals().&#xD;&#xA; * Any negative number is interpreted as '*'&#xD;&#xA; */"/>
        </eAnnotations>
      </eClassifiers>
    </eSubpackages>
  </ecore:EPackage>
  <ecore:EAnnotation source="dependentResource">
    <references href="../Standard.ecore#/0"/>
    <references href="../Standard.ecore#/1"/>
    <references href="collections.ecore#/0"/>
    <references href="collections.ecore#/1"/>
    <references href="../language/structure.ecore#/0"/>
    <references href="../language/structure.ecore#/1"/>
    <references href="../language/structure.ecore#/2"/>
    <references href="../kermeta_java.ecore#/0"/>
    <references href="../kermeta_java.ecore#/1"/>
    <references href="../language/reflective_collections.ecore#/0"/>
    <references href="../language/reflective_collections.ecore#/1"/>
    <references href="../kunit/kunit.ecore#/0"/>
    <references href="../kunit/kunit.ecore#/1"/>
    <references href="../kunit/kunit.ecore#/2"/>
    <references href="../kunit/assert.ecore#/0"/>
    <references href="../kunit/assert.ecore#/1"/>
    <references href="../kunit/assert.ecore#/2"/>
    <references href="../utils/utils.ecore#/0"/>
    <references href="../utils/utils.ecore#/1"/>
    <references href="../utils/utils.ecore#/2"/>
    <references href="../utils/StringBuffer.ecore#/0"/>
    <references href="../utils/StringBuffer.ecore#/1"/>
    <references href="../utils/hashtable.ecore#/0"/>
    <references href="../utils/hashtable.ecore#/1"/>
    <references href="../utils/hashtable.ecore#/2"/>
    <references href="../utils/stack.ecore#/0"/>
    <references href="../utils/stack.ecore#/1"/>
    <references href="../utils/stack.ecore#/2"/>
    <references href="../io/std_io.ecore#/0"/>
    <references href="../io/std_io.ecore#/1"/>
    <references href="../io/std_io.ecore#/2"/>
    <references href="../io/file_io.ecore#/0"/>
    <references href="../io/file_io.ecore#/1"/>
    <references href="../io/file_io.ecore#/2"/>
    <references href="../exceptions/exceptions.ecore#/0"/>
    <references href="../exceptions/exceptions.ecore#/1"/>
    <references href="../exceptions/exceptions.ecore#/2"/>
    <references href="../language/dynamic_expression.ecore#/0"/>
    <references href="../language/dynamic_expression.ecore#/1"/>
    <references href="../language/dynamic_expression.ecore#/2"/>
    <references href="../persistence/resource.ecore#/0"/>
    <references href="../persistence/resource.ecore#/1"/>
    <references href="../persistence/resource.ecore#/2"/>
    <references href="java.ecore#/0"/>
    <references href="java.ecore#/1"/>
    <references href="../ecore/ecore_compatibility.ecore#/0"/>
    <references href="../ecore/ecore_compatibility.ecore#/1"/>
    <references href="../ecore/ecore_compatibility.ecore#/2"/>
  </ecore:EAnnotation>
</xmi:XMI>
