<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TopPackage" nsURI="http://prePatterns" nsPrefix="prePatterns">
  <eAnnotations source="http://www.topcased.org/uuid">
    <details key="uuid" value="11437899611380"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="AClass" abstract="true" eSuperTypes="//visitors/Visitable">
    <eAnnotations source="http://www.topcased.org/uuid">
      <details key="uuid" value="11437899611411"/>
    </eAnnotations>
    <eOperations name="aOperation">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="11437899611422"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="accept">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="visitor.visitAClass(this);"/>
      </eAnnotations>
      <eAnnotations source="kermeta">
        <details key="body" value="result := visitor.visitAClass(self)"/>
      </eAnnotations>
      <eParameters name="visitor" eType="//visitors/Visitor"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aAttribute">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="11437899611423"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uses" eType="//CClass">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="11437899611434"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CClass" eSuperTypes="//visitors/Visitable">
    <eAnnotations source="http://www.topcased.org/uuid">
      <details key="uuid" value="11437899611445"/>
    </eAnnotations>
    <eOperations name="accept">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="visitor.visitCClass(this);"/>
      </eAnnotations>
      <eAnnotations source="kermeta">
        <details key="body" value="result := visitor.visitCClass(self)"/>
      </eAnnotations>
      <eParameters name="visitor" eType="//visitors/Visitor"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BClass" eSuperTypes="//AClass">
    <eAnnotations source="http://www.topcased.org/uuid">
      <details key="uuid" value="11437899611446"/>
    </eAnnotations>
    <eOperations name="accept">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="visitor.visitBClass(this);"/>
      </eAnnotations>
      <eAnnotations source="kermeta">
        <details key="body" value="result := visitor.visitBClass(self)"/>
      </eAnnotations>
      <eParameters name="visitor" eType="//visitors/Visitor"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composition" lowerBound="1" eType="//DClass" containment="true">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="11437899611457"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DClass" eSuperTypes="//visitors/Visitable">
    <eAnnotations source="http://www.topcased.org/uuid">
      <details key="uuid" value="11437899611468"/>
    </eAnnotations>
    <eOperations name="accept">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="visitor.visitDClass(this);"/>
      </eAnnotations>
      <eAnnotations source="kermeta">
        <details key="body" value="result := visitor.visitDClass(self)"/>
      </eAnnotations>
      <eParameters name="visitor" eType="//visitors/Visitor"/>
    </eOperations>
  </eClassifiers>
  <eSubpackages name="SubPackage">
    <eAnnotations source="http://www.topcased.org/uuid">
      <details key="uuid" value="11437899611479"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="EClass" eSuperTypes="//DClass">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="114379038882030"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="has" eType="//SubPackage/FClass" defaultValueLiteral="" containment="true">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="114379038882131"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FClass">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="114379038882232"/>
      </eAnnotations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="visitors">
    <eClassifiers xsi:type="ecore:EClass" name="Visitable" abstract="true" interface="true">
      <eOperations name="accept">
        <eParameters name="visitor" eType="//visitors/Visitor"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Visitor" abstract="true">
      <eOperations name="visit">
        <eParameters name="visitable" eType="//visitors/Visitable"/>
      </eOperations>
      <eOperations name="visitAClass">
        <eAnnotations source="kermeta">
          <details key="isAbstract" value="true"/>
        </eAnnotations>
        <eParameters name="visitable" eType="//AClass"/>
      </eOperations>
      <eOperations name="visitCClass">
        <eAnnotations source="kermeta">
          <details key="isAbstract" value="true"/>
        </eAnnotations>
        <eParameters name="visitable" eType="//CClass"/>
      </eOperations>
      <eOperations name="visitBClass">
        <eAnnotations source="kermeta">
          <details key="isAbstract" value="true"/>
        </eAnnotations>
        <eParameters name="visitable" eType="//BClass"/>
      </eOperations>
      <eOperations name="visitDClass">
        <eAnnotations source="kermeta">
          <details key="isAbstract" value="true"/>
        </eAnnotations>
        <eParameters name="visitable" eType="//DClass"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TopDownVisitor" abstract="true" eSuperTypes="//visitors/Visitable">
      <eOperations name="visitAClass">
        <eParameters name="visitable" eType="//AClass"/>
      </eOperations>
      <eOperations name="visitCClass">
        <eParameters name="visitable" eType="//CClass"/>
      </eOperations>
      <eOperations name="visitBClass">
        <eAnnotations source="kermeta">
          <details key="body" value="eAllReferences.each{ eRef | &#xA; if eRef.eType.name == &quot;DClass&quot; then accept(self) end&#xA;}"/>
        </eAnnotations>
        <eParameters name="visitable" eType="//BClass"/>
      </eOperations>
      <eOperations name="visitDClass">
        <eParameters name="visitable" eType="//DClass"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
