/**
 * <copyright>
 * </copyright>
 *
 * $Id: ErrorMessageValidator.java,v 1.3 2008-04-28 11:50:11 ftanguy Exp $
 */
package org.kermeta.io.validation;


/**
 * A sample validator interface for {@link org.kermeta.io.ErrorMessage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ErrorMessageValidator {
	boolean validate();

}
