/**
 * <copyright>
 * </copyright>
 *
 * $Id: KermetaUnitRequireValidator.java,v 1.1 2007-10-04 07:22:15 ftanguy Exp $
 */
package org.kermeta.io.validation;

import fr.irisa.triskell.kermeta.language.structure.Require;

import org.kermeta.io.KermetaUnit;

/**
 * A sample validator interface for {@link org.kermeta.io.KermetaUnitRequire}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface KermetaUnitRequireValidator {
	boolean validate();

	boolean validateKermetaUnit(KermetaUnit value);
	boolean validateRequire(Require value);
}
