/**
 * <copyright>
 * </copyright>
 *
 * $Id: KermetaUnitStorerValidator.java,v 1.4 2007-12-06 14:10:53 ftanguy Exp $
 */
package org.kermeta.io.validation;

import org.eclipse.emf.common.util.EList;
import org.kermeta.io.KermetaUnit;

/**
 * A sample validator interface for {@link org.kermeta.io.KermetaUnitStorer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface KermetaUnitStorerValidator {
	boolean validate();

	boolean validateKermetaUnits(EList value);

	boolean validateKermetaUnitsBeingLoaded(EList<KermetaUnit> value);

	boolean validateKermetaUnitsBeingUnloaded(EList<KermetaUnit> value);

	boolean validateKermetaUnitsBeginLoaded(EList<KermetaUnit> value);

	boolean validateKermetaUnitsBeginUnloaded(EList<KermetaUnit> value);
}
