/**
 * <copyright>
 * </copyright>
 *
 * $Id: KermetaUnitValidator.java,v 1.11 2008-06-12 07:18:49 ftanguy Exp $
 */
package org.kermeta.io.validation;

import java.util.Map;

import org.eclipse.emf.common.util.EList;
import org.kermeta.io.IBuildingState;
import org.kermeta.io.KermetaUnit;
import org.kermeta.io.KermetaUnitRequire;
import org.kermeta.io.KermetaUnitStorer;
import org.kermeta.io.Message;
import org.kermeta.io.PackageEntry;
import org.kermeta.io.TypeDefinitionCache;

import fr.irisa.triskell.kermeta.language.structure.ModelingUnit;
import fr.irisa.triskell.kermeta.language.structure.TypeDefinition;
import fr.irisa.triskell.traceability.helper.Tracer;

/**
 * A sample validator interface for {@link org.kermeta.io.KermetaUnit}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface KermetaUnitValidator {
	boolean validate();

	boolean validateStorer(KermetaUnitStorer value);
	boolean validateUri(String value);
	boolean validateModelingUnit(ModelingUnit value);

	boolean validateInternalPackageEntries(EList value);
	boolean validateExternalPackageEntries(EList value);
	boolean validateImportedKermetaUnits(EList value);
	boolean validateImporters(EList value);
	boolean validateBuildingState(IBuildingState value);
	boolean validateMessages(EList value);
	boolean validateNeedASTTraces(boolean value);
	boolean validateTypeChecked(boolean value);
	boolean validateFramework(boolean value);
	boolean validateTracer(Tracer value);
	boolean validateConstraintChecked(boolean value);

	boolean validateAspects(Map<TypeDefinition, TypeDefinition> value);

	boolean validateIsBeingTypechecked(boolean value);

	boolean validateTypeDefinitionCache(TypeDefinitionCache value);

	boolean validateKermetaUnitRequires(EList<KermetaUnitRequire> value);

	boolean validateLocked(boolean value);

	boolean validateBaseAspects(Map<TypeDefinition, EList<TypeDefinition>> value);

	boolean validateKermetaUnitRequired(EList<KermetaUnit> value);
}
