/**
 * <copyright>
 * </copyright>
 *
 * $Id: KermetaUnitLoaderValidator.java,v 1.7 2008-06-12 07:18:49 ftanguy Exp $
 */
package org.kermeta.io.validation;

import org.eclipse.emf.common.util.EList;
import org.kermeta.io.KermetaUnit;

/**
 * A sample validator interface for {@link org.kermeta.io.KermetaUnitLoader}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface KermetaUnitLoaderValidator {
	boolean validate();

	boolean validateKermetaUnits(EList value);
}
