/**
 * <copyright>
 * </copyright>
 *
 * $Id: PackageEntryValidator.java,v 1.2 2007-07-20 15:08:05 ftanguy Exp $
 */
package org.kermeta.io.validation;


/**
 * A sample validator interface for {@link org.kermeta.io.PackageEntry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PackageEntryValidator {
	boolean validate();

	boolean validateQualifiedName(String value);
	boolean validatePackage(fr.irisa.triskell.kermeta.language.structure.Package value);
}
