/**
 * <copyright>
 * </copyright>
 *
 * $Id: ParseErrorMessageValidator.java,v 1.3 2008-01-04 14:20:07 dvojtise Exp $
 */
package org.kermeta.io.validation;

import org.eclipse.gymnast.runtime.core.ast.ASTNode;

/**
 * A sample validator interface for {@link org.kermeta.io.ParseErrorMessage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParseErrorMessageValidator {
	boolean validate();

	boolean validateNode(ASTNode value);
}
