/**
 * <copyright>
 * </copyright>
 *
 * $Id: TypeDefinitionCacheValidator.java,v 1.2 2008-04-28 11:50:11 ftanguy Exp $
 */
package org.kermeta.io.validation;

import java.util.Map;
import org.eclipse.emf.common.util.EList;

import org.kermeta.io.KermetaUnit;
import org.kermeta.io.TypeDefinitionCacheEntry;

/**
 * A sample validator interface for {@link org.kermeta.io.TypeDefinitionCache}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TypeDefinitionCacheValidator {
	boolean validate();

	boolean validateEntries(EList<TypeDefinitionCacheEntry> value);
	boolean validateKermetaUnit(KermetaUnit value);

	boolean validateEntries(Map<String, TypeDefinitionCacheEntry> value);

	boolean validateExternalSearchAuthorized(boolean value);

	boolean validateKermetaUnitProcessed(EList<KermetaUnit> value);
}
