<?xml version="1.0" encoding="ISO-8859-1"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="interest"
    nsURI="http://interest" nsPrefix="interest">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="This metamodel describes in a simple manner the interest that objects can have for specific resources.&#xA;Objects can subscribe or unsubscribe to a resource. When the resource changes, those objects are told to update with the new value of that resource.&#xA;A resource can be anything (files, objects in memory) for the moment they have an id."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="InterestHost">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The interest host is an holder for concerns. So some specific hosts can be created for specifics resources. "/>
    </eAnnotations>
    <eOperations name="updateValue" eExceptions="#//IdNotFoundException">
      <eParameters name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="beConcernedAbout">
      <eParameters name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="target" eType="#//InterestedObject"/>
    </eOperations>
    <eOperations name="beUnconcernedAbout">
      <eParameters name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="target" eType="#//InterestedObject"/>
    </eOperations>
    <eOperations name="getConcern" eType="#//Concern">
      <eParameters name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concerns" upperBound="-1"
        eType="#//Concern" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Concern">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A concern object holds two things :&#xA;- the id of a resource&#xA;- a list of worried objects that must be warned as soon as the resource has changed"/>
    </eAnnotations>
    <eOperations name="updateValue">
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="beConcernedAbout">
      <eParameters name="target" eType="#//InterestedObject"/>
    </eOperations>
    <eOperations name="beUnconcernedAbout">
      <eParameters name="target" eType="#//InterestedObject"/>
    </eOperations>
    <eOperations name="getWorriedObject" eType="#//WorriedObject">
      <eParameters name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listeners" upperBound="-1"
        eType="#//WorriedObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorriedObject">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A worried object holds an object that is concerned for a resource.&#xA;When the resource changes, the worried object is asked to update the value of the targeted object.&#xA;The targeted object must implement an interface so that any kind of classes can be used through the interest mechanism. &#xA;"/>
    </eAnnotations>
    <eOperations name="updateValue">
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" lowerBound="1"
        eType="#//InterestedObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IdNotFoundException" instanceClassName="org.kermeta.interest.exception.IdNotFoundException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="InterestedObject" instanceClassName="org.kermeta.interest.InterestedObject"/>
</ecore:EPackage>
