<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="traceability"
    nsURI="http://www.kermeta.org/Traceability/2.0.0" nsPrefix="traceability">
  <eAnnotations source="kermeta.req">
    <details key="platform:/plugin/fr.irisa.triskell.kermeta/lib/framework.km" value="platform:/plugin/fr.irisa.triskell.kermeta/lib/framework.km"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TraceModel">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * This class represents a trace model.&#xD;&#xA; * This is a set of traces, references and messages.&#xD;&#xA; */"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traces" ordered="false"
        upperBound="-1" eType="#//Trace" containment="true" eOpposite="#//Trace/traceMdl">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** Set of traces contained by the trace model */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" ordered="false"
        upperBound="-1" eType="#//Reference" containment="true" eOpposite="#//Reference/traceMdl">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** Set of references to the traced objects of the trace model */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" ordered="false"
        upperBound="-1" eType="#//Message" containment="true" eOpposite="#//Message/traceMdl">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** Set of messages contained by the trace model */"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * This class represents a trace message, used to add some information to traces.&#xD;&#xA; * Typically, in order to known what had generated a given trace or provide a user&#xD;&#xA; * friendly message to the user.&#xD;&#xA; */"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="#//String">
      <eAnnotations source="kermeta">
        <details key="isComposite" value="true"/>
        <details key="documentation" value="/** Language of the message (english, french, etc.) */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//String">
      <eAnnotations source="kermeta">
        <details key="isComposite" value="true"/>
        <details key="documentation" value="/** Message kind */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="#//String">
      <eAnnotations source="kermeta">
        <details key="isComposite" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traces" upperBound="-1"
        eType="#//Trace" eOpposite="#//Trace/description">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** Link to the traces the message is associated with */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceMdl" lowerBound="1"
        eType="#//TraceModel" eOpposite="#//TraceModel/messages">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** Link to the containing trace model */"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trace">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * This class represents a trace element&#xD;&#xA; */"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceReferences" upperBound="-1"
        eType="#//Reference" eOpposite="#//Reference/targetTraces">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** Link to the references to the trace incoming elements */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetReferences" upperBound="-1"
        eType="#//Reference" eOpposite="#//Reference/sourceTraces">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** Link to the references to the trace outgoing elements */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" upperBound="-1"
        eType="#//Message" eOpposite="#//Message/traces">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** Link to the messages describing the trace */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceMdl" lowerBound="1"
        eType="#//TraceModel" eOpposite="#//TraceModel/traces">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** Link to the containing trace model */"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" abstract="true">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * This abstract class represents a reference to a concrete object&#xD;&#xA; */"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetTraces" upperBound="-1"
        eType="#//Trace" eOpposite="#//Trace/sourceReferences">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** Link to the reference target traces */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceTraces" upperBound="-1"
        eType="#//Trace" eOpposite="#//Trace/targetReferences">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** Link to the reference source traces */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceMdl" lowerBound="1"
        eType="#//TraceModel" eOpposite="#//TraceModel/references">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** Link to the containing trace model */"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileReference" abstract="true" eSuperTypes="#//Reference">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * This class represents a reference to a concrete object contained by a file&#xD;&#xA; */"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileURI" lowerBound="1"
        eType="#//String">
      <eAnnotations source="kermeta">
        <details key="isComposite" value="true"/>
        <details key="documentation" value="/** URI of the file containing the referred concrete object */"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextReference" eSuperTypes="#//FileReference">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * This class represents a reference to a textual file concrete object&#xD;&#xA; */"/>
    </eAnnotations>
    <eAnnotations source="kermeta.inv">
      <details key="validTextRef" value="do&#xA;&#x9;lineEndAt.isGreater(lineBeginAt).~or(lineBeginAt.equals(lineEndAt).~and(charEndAt.isGreaterOrEqual(charBeginAt)))&#xA;end"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineBeginAt" lowerBound="1"
        eType="#//Integer">
      <eAnnotations source="kermeta">
        <details key="isComposite" value="true"/>
        <details key="documentation" value="/** Starting line number */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="charBeginAt" lowerBound="1"
        eType="#//Integer">
      <eAnnotations source="kermeta">
        <details key="isComposite" value="true"/>
        <details key="documentation" value="/** Starting character number */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineEndAt" lowerBound="1"
        eType="#//Integer">
      <eAnnotations source="kermeta">
        <details key="isComposite" value="true"/>
        <details key="documentation" value="/** Ending line number */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="charEndAt" lowerBound="1"
        eType="#//Integer">
      <eAnnotations source="kermeta">
        <details key="isComposite" value="true"/>
        <details key="documentation" value="/** Ending character number */"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLReference" eSuperTypes="#//FileReference">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * This class represents a reference to a XML concrete object&#xD;&#xA; */"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xPointer" lowerBound="1"
        eType="#//String">
      <eAnnotations source="kermeta">
        <details key="isComposite" value="true"/>
        <details key="documentation" value="/** XML link to the referred XML concrete object */"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelReference" eSuperTypes="#//Reference">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * This class represents a reference to a model element&#xD;&#xA; */"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refObject" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="java.lang.Integer"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Object" instanceClassName="java.lang.Object"/>
  <eClassifiers xsi:type="ecore:EClass" name="QualifiedNameReference" eSuperTypes="#//Reference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" lowerBound="1"
        eType="#//String"/>
  </eClassifiers>
</ecore:EPackage>
