<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fsm"
    nsURI="platform:/resource/fr.irisa.triskell.kermeta.samples/fsm/metamodels/fsm.ecore"
    nsPrefix="fsm">
  <eClassifiers xsi:type="ecore:EClass" name="FSM">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedState" upperBound="-1"
        eType="#//State" containment="true" eOpposite="#//State/owningFSM">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="11491501338094"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialState" lowerBound="1"
        eType="#//State">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="11491501338095"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finalState" lowerBound="1"
        upperBound="-1" eType="#//State">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="11491501338097"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningFSM" lowerBound="1"
        eType="#//FSM" eOpposite="#//FSM/ownedState">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="114915013380911"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//String">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="114915013382412"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingTransition" upperBound="-1"
        eType="#//Transition" containment="true" eOpposite="#//Transition/source">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="114915013382413"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingTransition" upperBound="-1"
        eType="#//Transition" eOpposite="#//Transition/target">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="114915013382414"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//State" eOpposite="#//State/outgoingTransition">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="114915013382417"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//State" eOpposite="#//State/incomingTransition">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="114915013382418"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="input" eType="#//String">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="114915013382419"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="#//String">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="114915013382420"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
</ecore:EPackage>
