<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="art2"
    nsURI="http://art/2.0" nsPrefix="art2">
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInstance" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentType" lowerBound="1"
        eType="#//ComponentType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hostedPorts" upperBound="-1"
        eType="#//Port" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dictionary" eType="#//Dictionary"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirePorts" upperBound="-1"
        eType="#//Port" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" eType="#//Namespace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentType" eSuperTypes="#//DeployUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hostedPortTypes" upperBound="-1"
        eType="#//PortType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dictionary" eType="#//DictionaryType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bean" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="neededPortTypes" upperBound="-1"
        eType="#//PortTypeRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="integrationPatterns" upperBound="-1"
        eType="#//IntegrationPattern" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extraFonctionalProperties"
        eType="#//ExtraFonctionalProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="offeredPortTypes" upperBound="-1"
        eType="#//PortTypeRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerNode" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//ComponentInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="#//Binding" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//ContainerNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentTypes" upperBound="-1"
        eType="#//ComponentType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repositories" upperBound="-1"
        eType="#//Repository" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypes" upperBound="-1"
        eType="#//DataType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="availablePortImpl" upperBound="-1"
        eType="#//AbstractPortImpl" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortType" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="impl" lowerBound="1" eType="#//AbstractPortImpl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" lowerBound="1"
        eType="#//AbstractDataType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="synchrone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bean" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="portTypeRef" lowerBound="1"
        eType="#//PortTypeRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="childs" upperBound="-1"
        eType="#//Namespace" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Namespace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractPortImpl" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractDataType" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PortServiceImpl" eSuperTypes="#//AbstractPortImpl"/>
  <eClassifiers xsi:type="ecore:EClass" name="PortActorImpl" eSuperTypes="#//AbstractPortImpl"/>
  <eClassifiers xsi:type="ecore:EClass" name="PortMessageImpl" eSuperTypes="#//AbstractPortImpl"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dictionary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//DictionaryValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DictionaryType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//DictionaryAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValues" upperBound="-1"
        eType="#//DictionaryValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DictionaryAttribute" eSuperTypes="#//TypedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DictionaryValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
        eType="#//DictionaryAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" lowerBound="2" upperBound="2"
        eType="#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeType" eSuperTypes="#//ComponentType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="childs" upperBound="-1"
        eType="#//ComponentType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childPortTypes" upperBound="-1"
        eType="#//PortTypeRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wires" eType="#//Wire"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortTypeRef" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="#//PortType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wire">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" lowerBound="2" upperBound="2"
        eType="#//PortTypeRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceDataType" eSuperTypes="#//AbstractDataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//TypedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//TypedElement #//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" lowerBound="1"
        eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageDataType" eSuperTypes="#//AbstractDataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Repository" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="units" upperBound="-1"
        eType="#//DeployUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeployUnit" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unitName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentTypeLibrary" eSuperTypes="#//DeployUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subComponentTypes" upperBound="-1"
        eType="#//ComponentType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegrationPattern" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extraFonctionalProperties"
        upperBound="-1" eType="#//ExtraFonctionalProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portTypes" upperBound="-1"
        eType="#//PortTypeRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtraFonctionalProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="portTypes" upperBound="-1"
        eType="#//PortTypeRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OSGiScrDataType" eSuperTypes="#//ServiceDataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interfaceImpl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
