<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kermetaStart"
    nsPrefix="kermetaStart">
  <eClassifiers xsi:type="ecore:EClass" name="Run"/>
  <eClassifiers xsi:type="ecore:EClass" name="KMMetaBuilder"/>
  <eClassifiers xsi:type="ecore:EClass" name="KMBuilder"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaseInterpreter"/>
  <eClassifiers xsi:type="ecore:EClass" name="KermetaUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeObjectFactory"/>
</ecore:EPackage>
