/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.irisa.osgi.manifest.parser.node;

import java.util.*;
import fr.irisa.osgi.manifest.parser.analysis.*;

@SuppressWarnings("nls")
public final class ABundleVendorEntry extends PBundleVendorEntry {
	private TBundleVendor _bundleVendor_;
	private TAllString _allString_;
	private final LinkedList<PParameter> _parameter_ = new LinkedList<PParameter>();

	public ABundleVendorEntry() {
		// Constructor
	}

	public ABundleVendorEntry(@SuppressWarnings("hiding")
	TBundleVendor _bundleVendor_, @SuppressWarnings("hiding")
	TAllString _allString_, @SuppressWarnings("hiding")
	List<PParameter> _parameter_) {
		// Constructor
		setBundleVendor(_bundleVendor_);

		setAllString(_allString_);

		setParameter(_parameter_);

	}

	@Override
	public Object clone() {
		return new ABundleVendorEntry(cloneNode(this._bundleVendor_),
				cloneNode(this._allString_), cloneList(this._parameter_));
	}

	public void apply(Switch sw) {
		((Analysis) sw).caseABundleVendorEntry(this);
	}

	public TBundleVendor getBundleVendor() {
		return this._bundleVendor_;
	}

	public void setBundleVendor(TBundleVendor node) {
		if (this._bundleVendor_ != null) {
			this._bundleVendor_.parent(null);
		}

		if (node != null) {
			if (node.parent() != null) {
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		this._bundleVendor_ = node;
	}

	public TAllString getAllString() {
		return this._allString_;
	}

	public void setAllString(TAllString node) {
		if (this._allString_ != null) {
			this._allString_.parent(null);
		}

		if (node != null) {
			if (node.parent() != null) {
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		this._allString_ = node;
	}

	public LinkedList<PParameter> getParameter() {
		return this._parameter_;
	}

	public void setParameter(List<PParameter> list) {
		this._parameter_.clear();
		this._parameter_.addAll(list);
		for (PParameter e : list) {
			if (e.parent() != null) {
				e.parent().removeChild(e);
			}

			e.parent(this);
		}
	}

	@Override
	public String toString() {
		return "" + toString(this._bundleVendor_) + toString(this._allString_)
				+ toString(this._parameter_);
	}

	@Override
	void removeChild(@SuppressWarnings("unused")
	Node child) {
		// Remove child
		if (this._bundleVendor_ == child) {
			this._bundleVendor_ = null;
			return;
		}

		if (this._allString_ == child) {
			this._allString_ = null;
			return;
		}

		if (this._parameter_.remove(child)) {
			return;
		}

		throw new RuntimeException("Not a child.");
	}

	@Override
	void replaceChild(@SuppressWarnings("unused")
	Node oldChild, @SuppressWarnings("unused")
	Node newChild) {
		// Replace child
		if (this._bundleVendor_ == oldChild) {
			setBundleVendor((TBundleVendor) newChild);
			return;
		}

		if (this._allString_ == oldChild) {
			setAllString((TAllString) newChild);
			return;
		}

		for (ListIterator<PParameter> i = this._parameter_.listIterator(); i
				.hasNext();) {
			if (i.next() == oldChild) {
				if (newChild != null) {
					i.set((PParameter) newChild);
					newChild.parent(this);
					oldChild.parent(null);
					return;
				}

				i.remove();
				oldChild.parent(null);
				return;
			}
		}

		throw new RuntimeException("Not a child.");
	}
}
