/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.irisa.osgi.manifest.parser.node;

import fr.irisa.osgi.manifest.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ABundleCategoryEntryManifestentry extends PManifestentry {
	private PBundleCategoryEntry _bundleCategoryEntry_;

	public ABundleCategoryEntryManifestentry() {
		// Constructor
	}

	public ABundleCategoryEntryManifestentry(@SuppressWarnings("hiding")
	PBundleCategoryEntry _bundleCategoryEntry_) {
		// Constructor
		setBundleCategoryEntry(_bundleCategoryEntry_);

	}

	@Override
	public Object clone() {
		return new ABundleCategoryEntryManifestentry(
				cloneNode(this._bundleCategoryEntry_));
	}

	public void apply(Switch sw) {
		((Analysis) sw).caseABundleCategoryEntryManifestentry(this);
	}

	public PBundleCategoryEntry getBundleCategoryEntry() {
		return this._bundleCategoryEntry_;
	}

	public void setBundleCategoryEntry(PBundleCategoryEntry node) {
		if (this._bundleCategoryEntry_ != null) {
			this._bundleCategoryEntry_.parent(null);
		}

		if (node != null) {
			if (node.parent() != null) {
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		this._bundleCategoryEntry_ = node;
	}

	@Override
	public String toString() {
		return "" + toString(this._bundleCategoryEntry_);
	}

	@Override
	void removeChild(@SuppressWarnings("unused")
	Node child) {
		// Remove child
		if (this._bundleCategoryEntry_ == child) {
			this._bundleCategoryEntry_ = null;
			return;
		}

		throw new RuntimeException("Not a child.");
	}

	@Override
	void replaceChild(@SuppressWarnings("unused")
	Node oldChild, @SuppressWarnings("unused")
	Node newChild) {
		// Replace child
		if (this._bundleCategoryEntry_ == oldChild) {
			setBundleCategoryEntry((PBundleCategoryEntry) newChild);
			return;
		}

		throw new RuntimeException("Not a child.");
	}
}
