/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.irisa.osgi.manifest.parser.node;

import fr.irisa.osgi.manifest.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AOsnameWindowsvistaOsnameValue extends POsnameValue {
	private TOsnameWindowsvista _osnameWindowsvista_;

	public AOsnameWindowsvistaOsnameValue() {
		// Constructor
	}

	public AOsnameWindowsvistaOsnameValue(@SuppressWarnings("hiding")
	TOsnameWindowsvista _osnameWindowsvista_) {
		// Constructor
		setOsnameWindowsvista(_osnameWindowsvista_);

	}

	@Override
	public Object clone() {
		return new AOsnameWindowsvistaOsnameValue(
				cloneNode(this._osnameWindowsvista_));
	}

	public void apply(Switch sw) {
		((Analysis) sw).caseAOsnameWindowsvistaOsnameValue(this);
	}

	public TOsnameWindowsvista getOsnameWindowsvista() {
		return this._osnameWindowsvista_;
	}

	public void setOsnameWindowsvista(TOsnameWindowsvista node) {
		if (this._osnameWindowsvista_ != null) {
			this._osnameWindowsvista_.parent(null);
		}

		if (node != null) {
			if (node.parent() != null) {
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		this._osnameWindowsvista_ = node;
	}

	@Override
	public String toString() {
		return "" + toString(this._osnameWindowsvista_);
	}

	@Override
	void removeChild(@SuppressWarnings("unused")
	Node child) {
		// Remove child
		if (this._osnameWindowsvista_ == child) {
			this._osnameWindowsvista_ = null;
			return;
		}

		throw new RuntimeException("Not a child.");
	}

	@Override
	void replaceChild(@SuppressWarnings("unused")
	Node oldChild, @SuppressWarnings("unused")
	Node newChild) {
		// Replace child
		if (this._osnameWindowsvista_ == oldChild) {
			setOsnameWindowsvista((TOsnameWindowsvista) newChild);
			return;
		}

		throw new RuntimeException("Not a child.");
	}
}
