/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.irisa.osgi.manifest.parser.node;

import fr.irisa.osgi.manifest.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AResolutionMandatoryResolutionValue extends PResolutionValue {
	private TResolutionMandatory _resolutionMandatory_;

	public AResolutionMandatoryResolutionValue() {
		// Constructor
	}

	public AResolutionMandatoryResolutionValue(@SuppressWarnings("hiding")
	TResolutionMandatory _resolutionMandatory_) {
		// Constructor
		setResolutionMandatory(_resolutionMandatory_);

	}

	@Override
	public Object clone() {
		return new AResolutionMandatoryResolutionValue(
				cloneNode(this._resolutionMandatory_));
	}

	public void apply(Switch sw) {
		((Analysis) sw).caseAResolutionMandatoryResolutionValue(this);
	}

	public TResolutionMandatory getResolutionMandatory() {
		return this._resolutionMandatory_;
	}

	public void setResolutionMandatory(TResolutionMandatory node) {
		if (this._resolutionMandatory_ != null) {
			this._resolutionMandatory_.parent(null);
		}

		if (node != null) {
			if (node.parent() != null) {
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		this._resolutionMandatory_ = node;
	}

	@Override
	public String toString() {
		return "" + toString(this._resolutionMandatory_);
	}

	@Override
	void removeChild(@SuppressWarnings("unused")
	Node child) {
		// Remove child
		if (this._resolutionMandatory_ == child) {
			this._resolutionMandatory_ = null;
			return;
		}

		throw new RuntimeException("Not a child.");
	}

	@Override
	void replaceChild(@SuppressWarnings("unused")
	Node oldChild, @SuppressWarnings("unused")
	Node newChild) {
		// Replace child
		if (this._resolutionMandatory_ == oldChild) {
			setResolutionMandatory((TResolutionMandatory) newChild);
			return;
		}

		throw new RuntimeException("Not a child.");
	}
}
