/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.irisa.osgi.manifest.parser.node;

import fr.irisa.osgi.manifest.parser.analysis.*;

@SuppressWarnings("nls")
public final class TBundleRequiredexecutionenvironment extends Token
{
    public TBundleRequiredexecutionenvironment(String text)
    {
        setText(text);
    }

    public TBundleRequiredexecutionenvironment(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TBundleRequiredexecutionenvironment(getText(), getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBundleRequiredexecutionenvironment(this);
    }
}
