/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.irisa.osgi.manifest.parser.node;

import fr.irisa.osgi.manifest.parser.analysis.*;

@SuppressWarnings("nls")
public final class TBundleContactaddress extends Token {
	public TBundleContactaddress() {
		super.setText("Bundle-ContactAddress: ");
	}

	public TBundleContactaddress(int line, int pos) {
		super.setText("Bundle-ContactAddress: ");
		setLine(line);
		setPos(pos);
	}

	@Override
	public Object clone() {
		return new TBundleContactaddress(getLine(), getPos());
	}

	public void apply(Switch sw) {
		((Analysis) sw).caseTBundleContactaddress(this);
	}

	@Override
	public void setText(@SuppressWarnings("unused")
	String text) {
		throw new RuntimeException("Cannot change TBundleContactaddress text.");
	}
}
