/**
 * <copyright>
 * </copyright>
 *
 * $Id: ResourceValidator.java,v 1.1 2008-07-02 09:43:40 ftanguy Exp $
 */
package kermeta.persistence.validation;

import kermeta.persistence.Repository;
import kermeta.persistence.Resource;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link kermeta.persistence.Resource}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResourceValidator {
	boolean validate();

	boolean validateDependentResources(EList<Resource> value);
	boolean validateRepository(Repository value);
	boolean validateContents(EList<kermeta.language.structure.Object> value);
	boolean validateIsReadOnly(boolean value);
	boolean validateMetaModelURI(String value);
	boolean validateUri(String value);
}
