<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ex"
    nsURI="platform:/resource/org.kermeta.ki.pruning.examples/src/kermeta/fullClassModel/FullClassModel.ecore#/"
    nsPrefix="ex">
  <eSubpackages name="fullClassModel" nsURI="platform:/resource/org.kermeta.ki.pruning.examples/src/kermeta/fullClassModel/FullClassModel.ecore#/ex/fullClassModel"
      nsPrefix="fullClassModel">
    <eClassifiers xsi:type="ecore:EClass" name="ClassModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
          eType="#//fullClassModel/Clazz" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Clazz">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="kermeta">
          <details key="isComposite" value="true"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="superClasses" upperBound="-1"
          eType="#//fullClassModel/Clazz"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//fullClassModel/Property" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Property">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="kermeta">
          <details key="isComposite" value="true"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1"
          eType="#//fullClassModel/Clazz"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//fullClassModel/Clazz"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="#//fullClassModel/Property"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
