<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="org"
    nsURI="http://SmartAdapters4ART" nsPrefix="org">
  <eSubpackages name="smartadapters" nsURI="http://SmartAdapters4ART/smartadapters"
      nsPrefix="smartadapters">
    <eSubpackages name="core" nsURI="http://SmartAdapters4ART/smartadapters/core"
        nsPrefix="core">
      <eClassifiers xsi:type="ecore:EClass" name="Adapter">
        <eStructuralFeatures xsi:type="ecore:EReference" name="aspect" lowerBound="1"
            eType="#//smartadapters/core/Aspect" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="adapt" upperBound="-1"
            eType="#//smartadapters/core/Adaptation" containment="true" eOpposite="#//smartadapters/core/Adaptation/adapter"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/String">
          <eAnnotations source="kermeta">
            <details key="isComposite" value="true"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Aspect">
        <eStructuralFeatures xsi:type="ecore:EReference" name="template" eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/PatternFramework.ecore#//ModelPattern"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="structure" lowerBound="1"
            eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/PatternFramework.ecore#//PModel"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="persistent" upperBound="-1"
            eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/PatternFramework.ecore#//PObject">
          <eAnnotations source="kermeta">
            <details key="documentation" value="/**&#xD;&#xA;   persistent refers to aspectual PObject that must not be&#xD;&#xA;   cloned between two bindings&#xD;&#xA;   TODO : contraints...&#xD;&#xA;   */"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Adaptation" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="adapter" lowerBound="1"
            eType="#//smartadapters/core/Adapter" eOpposite="#//smartadapters/core/Adapter/adapt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="cloneAdaptation" abstract="true"
          eSuperTypes="#//smartadapters/core/Adaptation">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" eType="#//smartadapters/core/uniqueType">
          <eAnnotations source="kermeta">
            <details key="isComposite" value="true"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="createAdaptation" abstract="true"
          eSuperTypes="#//smartadapters/core/Adaptation">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" eType="#//smartadapters/core/uniqueType">
          <eAnnotations source="kermeta">
            <details key="isComposite" value="true"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="setAdaptation" abstract="true" eSuperTypes="#//smartadapters/core/Adaptation"/>
      <eClassifiers xsi:type="ecore:EClass" name="unsetAdaptation" abstract="true"
          eSuperTypes="#//smartadapters/core/Adaptation"/>
      <eClassifiers xsi:type="ecore:EClass" name="makeUnique" eSuperTypes="#//smartadapters/core/Adaptation">
        <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
            eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/PatternFramework.ecore#//PObject"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="uniqueType">
        <eLiterals name="unique" literal="unique"/>
        <eLiterals name="non_unique" value="1" literal="non_unique"/>
        <eLiterals name="onDemand" value="2" literal="onDemand"/>
      </eClassifiers>
      <eSubpackages name="adaptations" nsURI="http://SmartAdapters4ART/smartadapters/core/adaptations"
          nsPrefix="adaptations">
        <eClassifiers xsi:type="ecore:EClass" name="SetruntimeSystem" eSuperTypes="#//smartadapters/core/setAdaptation">
          <eStructuralFeatures xsi:type="ecore:EReference" name="SystemToSet" eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/System"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="refroot" eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/instance/CompositeInstance"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="refservices" upperBound="-1"
              eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/type/Service"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="reftypes" upperBound="-1"
              eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/type/ComponentType"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="refdataTypes" upperBound="-1"
              eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/DataType"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="refname" eType="ecore:EDataType ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/String">
            <eAnnotations source="kermeta">
              <details key="isComposite" value="false"/>
            </eAnnotations>
          </eStructuralFeatures>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="SetruntimeinstanceComponentInstance"
            eSuperTypes="#//smartadapters/core/setAdaptation">
          <eStructuralFeatures xsi:type="ecore:EReference" name="ComponentInstanceToSet"
              eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/instance/ComponentInstance"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="reftype" eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/type/ComponentType"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="refstate" eType="ecore:EDataType ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/String">
            <eAnnotations source="kermeta">
              <details key="isComposite" value="false"/>
            </eAnnotations>
          </eStructuralFeatures>
          <eStructuralFeatures xsi:type="ecore:EReference" name="refsuperComponent"
              eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/instance/CompositeInstance"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="refattribute" upperBound="-1"
              eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/instance/ValuedAttribute"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="refbinding" upperBound="-1"
              eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/instance/TransmissionBinding"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="refname" eType="ecore:EDataType ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/String">
            <eAnnotations source="kermeta">
              <details key="isComposite" value="false"/>
            </eAnnotations>
          </eStructuralFeatures>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="SetruntimeinstancePrimitiveInstance"
            eSuperTypes="#//smartadapters/core/setAdaptation">
          <eStructuralFeatures xsi:type="ecore:EReference" name="PrimitiveInstanceToSet"
              eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/instance/PrimitiveInstance"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="reftype" eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/type/ComponentType"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="refstate" eType="ecore:EDataType ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/String">
            <eAnnotations source="kermeta">
              <details key="isComposite" value="false"/>
            </eAnnotations>
          </eStructuralFeatures>
          <eStructuralFeatures xsi:type="ecore:EReference" name="refsuperComponent"
              eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/instance/CompositeInstance"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="refattribute" upperBound="-1"
              eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/instance/ValuedAttribute"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="refbinding" upperBound="-1"
              eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/instance/TransmissionBinding"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="refname" eType="ecore:EDataType ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/String">
            <eAnnotations source="kermeta">
              <details key="isComposite" value="false"/>
            </eAnnotations>
          </eStructuralFeatures>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="SetruntimeinstanceCompositeInstance"
            eSuperTypes="#//smartadapters/core/setAdaptation">
          <eStructuralFeatures xsi:type="ecore:EReference" name="CompositeInstanceToSet"
              eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/instance/CompositeInstance"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="refsubComponent"
              upperBound="-1" eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/instance/ComponentInstance"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="refdelegation" upperBound="-1"
              eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/instance/DelegationBinding"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="reftype" eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/type/ComponentType"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="refstate" eType="ecore:EDataType ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/String">
            <eAnnotations source="kermeta">
              <details key="isComposite" value="false"/>
            </eAnnotations>
          </eStructuralFeatures>
          <eStructuralFeatures xsi:type="ecore:EReference" name="refsuperComponent"
              eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/instance/CompositeInstance"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="refattribute" upperBound="-1"
              eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/instance/ValuedAttribute"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="refbinding" upperBound="-1"
              eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/instance/TransmissionBinding"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="refname" eType="ecore:EDataType ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/String">
            <eAnnotations source="kermeta">
              <details key="isComposite" value="false"/>
            </eAnnotations>
          </eStructuralFeatures>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="SetruntimeinstanceTransmissionBinding"
            eSuperTypes="#//smartadapters/core/setAdaptation">
          <eStructuralFeatures xsi:type="ecore:EReference" name="TransmissionBindingToSet"
              eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/instance/TransmissionBinding"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="refclient" eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/type/AbstractPort"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="refserver" eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/type/AbstractPort"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="refserverInstance"
              eType="ecore:EClass ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/instance/ComponentInstance"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="refId" eType="ecore:EDataType ../../org.kermeta.art.model.pattern/model/metamodel@runtimePattern.ecore#//art/String"/>
        </eClassifiers>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
