<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EAnnotation source="ModellingUnit">
    <details key="require" value="http://www.eclipse.org/emf/2002/Ecore|"/>
    <details key="using" value="aPackage|"/>
  </ecore:EAnnotation>
  <ecore:EPackage name="aPackage" nsURI="http://aPackage" nsPrefix="aPackage">
    <eClassifiers xsi:type="ecore:EClass" name="aClass">
      <eOperations name="anOperation" eType="/1/anEnum">
        <eAnnotations source="kermeta">
          <details key="isAbstract" value="true"/>
        </eAnnotations>
        <eParameters name="aParameter">
          <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="anAttribute">
        <eAnnotations source="kermeta">
          <details key="isComposite" value="true"/>
        </eAnnotations>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="aReference" upperBound="-1" eType="/1/aClass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="kermeta::standard::Object" instanceClassName="java.lang.Object"/>
    <eClassifiers xsi:type="ecore:EEnum" name="anEnum">
      <eLiterals name="aEnemLiteral" literal="aEnemLiteral"/>
      <eLiterals name="anotherEnumLiteral" value="1" literal="anotherEnumLiteral"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="_KermetaSpecialTypesAlias_" instanceClassName="java.lang.Object"/>
  </ecore:EPackage>
  <ecore:EAnnotation source="dependentResource"/>
</xmi:XMI>
