<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Fractal"
    nsURI="platform:/resource/SmartAdapters/metamodel/domain/Fractal" nsPrefix="Fractal">
  <eAnnotations source="kermeta">
    <details key="documentation" value="/**&#xD;&#xA; * Requires all the Fractal, Fractal basic type system, Java and Julia concepts.&#xD;&#xA; *&#xD;&#xA; * This file can be used to generate the Ecore model for all Fractal, Java, Julia concepts.&#xD;&#xA; */"/>
  </eAnnotations>
  <eAnnotations source="kermeta.req">
    <details key="platform:/resource/fractal/sandbox/merle/Fractal-Kermeta/metamodel/Fractal/Core/concepts.kmt"
        value="platform:/resource/fractal/sandbox/merle/Fractal-Kermeta/metamodel/Fractal/Core/concepts.kmt"/>
    <details key="platform:/resource/fractal/sandbox/merle/Fractal-Kermeta/metamodel/Fractal/BasicTypeSystem/concepts.kmt"
        value="platform:/resource/fractal/sandbox/merle/Fractal-Kermeta/metamodel/Fractal/BasicTypeSystem/concepts.kmt"/>
    <details key="platform:/resource/fractal/sandbox/merle/Fractal-Kermeta/metamodel/Fractal/Control/concepts.kmt"
        value="platform:/resource/fractal/sandbox/merle/Fractal-Kermeta/metamodel/Fractal/Control/concepts.kmt"/>
    <details key="platform:/resource/fractal/sandbox/merle/Fractal-Kermeta/metamodel/Fractal/Java/concepts.kmt"
        value="platform:/resource/fractal/sandbox/merle/Fractal-Kermeta/metamodel/Fractal/Java/concepts.kmt"/>
    <details key="platform:/resource/fractal/sandbox/merle/Fractal-Kermeta/metamodel/Fractal/Julia/concepts.kmt"
        value="platform:/resource/fractal/sandbox/merle/Fractal-Kermeta/metamodel/Fractal/Julia/concepts.kmt"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * A Fractal system is composed of a set of Fractal components and types.&#xD;&#xA; */"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//Component" containment="true">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** All the Fractal components of a given Fractal system. */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" upperBound="-1" eType="#//Type"
        containment="true">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** All the Fractal types of a given Fractal system. */"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * Abstract base class for any Fractal types.&#xD;&#xA; */"/>
    </eAnnotations>
    <eOperations name="isSubTypeOf" eType="#//Boolean">
      <eAnnotations source="kermeta">
        <details key="isAbstract" value="true"/>
        <details key="documentation" value="/**&#xD;&#xA;   * Is this type instance sub type of a given type instance.&#xD;&#xA;   */"/>
      </eAnnotations>
      <eParameters name="type" eType="#//Type"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * A Fractal component:&#xD;&#xA; * - has a Fractal type,&#xD;&#xA; * - owns a Fractal membrane and a Fractal content,&#xD;&#xA; * - has super components,&#xD;&#xA; */"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** This type of a component. */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="membrane" lowerBound="1"
        eType="#//Membrane" containment="true" eOpposite="#//Membrane/owner">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** The membrane of a component. */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" lowerBound="1"
        eType="#//Content" containment="true" eOpposite="#//Content/owner">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** The content of a component. */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superComponent" upperBound="-1"
        eType="#//Component">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** Super components of a component. */"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Membrane">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * A Fractal membrane owns a set of controllers.&#xD;&#xA; */"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//Component"
        eOpposite="#//Component/membrane">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** The component owning this membrane. */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="externalInterface" upperBound="-1"
        eType="#//Interface" containment="true">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** The external interfaces of the membrane. */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalInterface" upperBound="-1"
        eType="#//Interface" containment="true">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** The internal interfaces of the membrane. */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controller" upperBound="-1"
        eType="#//Controller" containment="true" eOpposite="#//Controller/owner">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** Controllers owned by a membrane. */"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Content">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * A Fractal content has sub components and owns bindings.&#xD;&#xA; */"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//Component"
        eOpposite="#//Component/content">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** The component owning this content. */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subComponent" upperBound="-1"
        eType="#//Component">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** All the sub components contained by this content. */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="binding" upperBound="-1"
        eType="#//Binding" containment="true">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** All the bindings of this content. */"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Name" instanceClassName="java.lang.String">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/** Name type for Interface names. */"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Visibility">
    <eLiterals name="EXTERNAL" literal="EXTERNAL"/>
    <eLiterals name="INTERNAL" value="1" literal="INTERNAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * A Fractal interface is owned by a component and&#xD;&#xA; * has a type, a name, and a visibility.&#xD;&#xA; */"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//Component">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** The component owning this interface. */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** The type of this interface. */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="#//Name">
      <eAnnotations source="kermeta">
        <details key="isComposite" value="true"/>
        <details key="documentation" value="/** The name of this interface. */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" lowerBound="1"
        eType="#//Visibility">
      <eAnnotations source="kermeta">
        <details key="isComposite" value="true"/>
        <details key="documentation" value="/** The visibility of this interface. */"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binding">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * A Fractal binding is a communication path between two interfaces.&#xD;&#xA; */"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="client" lowerBound="1"
        eType="#//Interface">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** The interface source of the communication path. */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="server" lowerBound="1"
        eType="#//Interface">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** The interface target of the communication path. */"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Role">
    <eLiterals name="SERVER" literal="SERVER"/>
    <eLiterals name="CLIENT" value="1" literal="CLIENT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Cardinality">
    <eLiterals name="SINGLETON" literal="SINGLETON"/>
    <eLiterals name="COLLECTION" value="1" literal="COLLECTION"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Contingency">
    <eLiterals name="MANDATORY" literal="MANDATORY"/>
    <eLiterals name="OPTIONAL" value="1" literal="OPTIONAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentType" eSuperTypes="#//Type">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * ComponentType is a set of InterfaceType instances.&#xD;&#xA; */"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceType" upperBound="-1"
        eType="#//InterfaceType">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** Reference a set of InterfaceType instances. */"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceType" eSuperTypes="#//Type">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * InterfaceType has a name, a role, a cardinality, a contingency, and a signature.&#xD;&#xA; */"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="#//Name">
      <eAnnotations source="kermeta">
        <details key="isComposite" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" lowerBound="1" eType="#//Role">
      <eAnnotations source="kermeta">
        <details key="isComposite" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" lowerBound="1"
        eType="#//Cardinality">
      <eAnnotations source="kermeta">
        <details key="isComposite" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contingency" lowerBound="1"
        eType="#//Contingency">
      <eAnnotations source="kermeta">
        <details key="isComposite" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signature" lowerBound="1"
        eType="#//LanguageInterfaceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LanguageInterfaceType" abstract="true"
      eSuperTypes="#//Type">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * LanguageInterfaceType abstracts a programming language interface type.&#xD;&#xA; */"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controller" abstract="true">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * Abstract base class for any Fractal membrane controller.&#xD;&#xA; */"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//Membrane"
        eOpposite="#//Membrane/controller">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** The membrane owning this controller. */"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeController" abstract="true"
      eSuperTypes="#//Controller">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * The Fractal attribute controller.&#xD;&#xA; */"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BindingController" abstract="true" eSuperTypes="#//Controller">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * The Fractal binding controller.&#xD;&#xA; */"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentController" abstract="true" eSuperTypes="#//Controller">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * The Fractal content controller.&#xD;&#xA; */"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LifeCycleController" abstract="true"
      eSuperTypes="#//Controller">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * The Fractal lifecycle controller.&#xD;&#xA; */"/>
    </eAnnotations>
    <eOperations name="getStatus" eType="#//LifeCycleStatus">
      <eAnnotations source="kermeta">
        <details key="isAbstract" value="true"/>
        <details key="documentation" value="/**&#xD;&#xA;   * Get the lifecycle status of the component.&#xD;&#xA;   */"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="start" ordered="false">
      <eAnnotations source="kermeta">
        <details key="isAbstract" value="true"/>
        <details key="documentation" value="/**&#xD;&#xA;   * Start the component.&#xD;&#xA;   */"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="stop" ordered="false">
      <eAnnotations source="kermeta">
        <details key="isAbstract" value="true"/>
        <details key="documentation" value="/**&#xD;&#xA;   * Stop the component.&#xD;&#xA;   */"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LifeCycleStatus">
    <eLiterals name="STOPPED" literal="STOPPED"/>
    <eLiterals name="STARTED" value="1" literal="STARTED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NameController" abstract="true" eSuperTypes="#//Controller">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * The Fractal name controller.&#xD;&#xA; */"/>
    </eAnnotations>
    <eOperations name="getName" eType="#//String">
      <eAnnotations source="kermeta">
        <details key="isAbstract" value="true"/>
        <details key="documentation" value="/**&#xD;&#xA;   * Get the name associated to the component.&#xD;&#xA;   */"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="setName" ordered="false">
      <eAnnotations source="kermeta">
        <details key="isAbstract" value="true"/>
        <details key="documentation" value="/**&#xD;&#xA;   * Set the name associated to the component.&#xD;&#xA;   */"/>
      </eAnnotations>
      <eParameters name="name" eType="#//String"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuperController" abstract="true" eSuperTypes="#//Controller">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * The Fractal super controller.&#xD;&#xA; */"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicNameController" eSuperTypes="#//NameController">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * A basic and concrete name controller.&#xD;&#xA; */"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="#//String">
      <eAnnotations source="kermeta">
        <details key="isComposite" value="true"/>
        <details key="documentation" value="/** The component name. */"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicLifeCycleController" eSuperTypes="#//LifeCycleController">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * A basic and concrete lifecycle controller.&#xD;&#xA; */"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="#//LifeCycleStatus">
      <eAnnotations source="kermeta">
        <details key="isComposite" value="true"/>
        <details key="documentation" value="/** The component status. */"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericAttributeController" eSuperTypes="#//AttributeController">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * A generic attribute controller.&#xD;&#xA; */"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="#//String">
      <eAnnotations source="kermeta">
        <details key="isComposite" value="true"/>
        <details key="documentation" value="/** The name of the attribute. */"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="#//String">
      <eAnnotations source="kermeta">
        <details key="isComposite" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="java.lang.Boolean"/>
  <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
  <eSubpackages name="Java" nsURI="platform:/resource/SmartAdapters/metamodel/domain/Fractal/Java"
      nsPrefix="Java">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * This file contains all the concepts of the Java type system as&#xD;&#xA; * a specialisation of the Fractal basic type system.&#xD;&#xA; */"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//LanguageInterfaceType">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/**&#xD;&#xA; * A Java interface is a Fractal language interface type.&#xD;&#xA; * A Java interface has a name and could extend a set of other Java interfaces.&#xD;&#xA; */"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//String">
        <eAnnotations source="kermeta">
          <details key="isComposite" value="true"/>
          <details key="documentation" value="/** The full name of the Java interface. */"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extend" upperBound="-1"
          eType="#//Java/Interface">
        <eAnnotations source="kermeta">
          <details key="documentation" value="/** The Java interfaces extended by this Java interface. */"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//Type">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/**&#xD;&#xA; * A Java class is a specialisation of a Fractal type.&#xD;&#xA; * A Java class has a name, could extend another Java class,&#xD;&#xA; * and could inherit from a set of Java interfaces.&#xD;&#xA; */"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//String">
        <eAnnotations source="kermeta">
          <details key="isComposite" value="true"/>
          <details key="documentation" value="/** The full name of the Java class. */"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extend" eType="#//Java/Class">
        <eAnnotations source="kermeta">
          <details key="documentation" value="/** The Java class extended by this Java class. */"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implement" upperBound="-1"
          eType="#//Java/Interface">
        <eAnnotations source="kermeta">
          <details key="documentation" value="/** The Java interfaces implemented by this Java class. */"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Julia" nsURI="platform:/resource/SmartAdapters/metamodel/domain/Fractal/Julia"
      nsPrefix="Julia">
    <eAnnotations source="kermeta">
      <details key="documentation" value="/**&#xD;&#xA; * This file contains all the Julia concepts built on top of &#xD;&#xA; * Fractal and Java concepts.&#xD;&#xA; */"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Membrane" eSuperTypes="#//Membrane">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/**&#xD;&#xA; * A Julia membrane is a specialisation of a Fractal membrane.&#xD;&#xA; * A Julia membrane owns:&#xD;&#xA; * - a controller description.&#xD;&#xA; * - a set of interceptors.&#xD;&#xA; * - a content class.&#xD;&#xA; */"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="controllerDesc" lowerBound="1"
          eType="#//String">
        <eAnnotations source="kermeta">
          <details key="isComposite" value="true"/>
          <details key="documentation" value="/** The controller description, e.g. 'primitive', 'composite', etc. */"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interceptor" upperBound="-1"
          eType="#//Julia/Interceptor" containment="true">
        <eAnnotations source="kermeta">
          <details key="documentation" value="/** The set of interceptors of a Julia membrane. */"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//Java/Class">
        <eAnnotations source="kermeta">
          <details key="documentation" value="/** The Java class which could be associated to a Julia content. */"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interceptor">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/**&#xD;&#xA; * A Julia interceptor.&#xD;&#xA; *&#xD;&#xA; * TODO: Define the content of this class.&#xD;&#xA; */"/>
      </eAnnotations>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
