<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pattern" nsURI="platform:/resource/fr.irisa.triskell.kermeta.patternmatching.samples/SimpleFSM/metamodels/FSMMMPattern.ecore" nsPrefix="pattern">
  <eSubpackages name="FSM" nsURI="platform:/resource/fr.irisa.triskell.kermeta.patternmatching.samples/SimpleFSM/metamodels/FSMMMPattern.ecore/FSM" nsPrefix="FSM">
    <eClassifiers xsi:type="ecore:EClass" name="State">
      <eSuperTypes href="../../../fr.irisa.triskell.kermeta.patternmatching/src/kermeta/pattern/metamodel/PatternFramework.ecore#//PObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Transition">
      <eSuperTypes href="../../../fr.irisa.triskell.kermeta.patternmatching/src/kermeta/pattern/metamodel/PatternFramework.ecore#//PObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="//FSM/State"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="//FSM/State"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fsm">
      <eAnnotations source="kermeta">
        <details key="inv" value="templateConstraint is&#xD;&#xA;&#x9;do&#xD;&#xA;&#x9;&#x9;self.states.forAll{s | do&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;self.transitions.exists{t | do&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;t.target.equals(s)&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;end}&#xD;&#xA;&#x9;&#x9;&#x9;end}&#xD;&#xA;&#x9;end"/>
      </eAnnotations>
      <eSuperTypes href="../../../fr.irisa.triskell.kermeta.patternmatching/src/kermeta/pattern/metamodel/PatternFramework.ecore#//PObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1" eType="//FSM/State" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1" eType="//FSM/Transition" containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
