<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EAnnotation source="CompilationUnit">
    <details key="require" value="http://www.eclipse.org/emf/2002/Ecore|kermeta|"/>
  </ecore:EAnnotation>
  <ecore:EPackage name="FSM" nsURI="platform:/resource/SmartAdapters/metamodel/domain/FSMMM.ecore#/FSM" nsPrefix="FSM">
    <eClassifiers xsi:type="ecore:EClass" name="State">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
        <eAnnotations source="kermeta">
          <details key="isComposite" value="true"/>
        </eAnnotations>
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Transition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" eType="/1/State"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1" eType="/1/State"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fsm">
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1" upperBound="-1" eType="/1/State" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1" eType="/1/Transition" containment="true"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EAnnotation source="dependentResource"/>
</xmi:XMI>
