
//  Internal enum
final class OnInstanceCmd {
  public static final int _parentCmd = 0;
  public static final OnInstanceCmd parentCmd = new OnInstanceCmd(_parentCmd);
  public static final int _childrenCmd = 1;
  public static final OnInstanceCmd childrenCmd = new OnInstanceCmd(_childrenCmd);
  public static final int _getDefCmd = 2;
  public static final OnInstanceCmd getDefCmd = new OnInstanceCmd(_getDefCmd);
  public static final int _getUmlDefCmd = 3;
  public static final OnInstanceCmd getUmlDefCmd = new OnInstanceCmd(_getUmlDefCmd);
  public static final int _getCppDefCmd = 4;
  public static final OnInstanceCmd getCppDefCmd = new OnInstanceCmd(_getCppDefCmd);
  public static final int _getJavaDefCmd = 5;
  public static final OnInstanceCmd getJavaDefCmd = new OnInstanceCmd(_getJavaDefCmd);
  public static final int _getIdlDefCmd = 6;
  public static final OnInstanceCmd getIdlDefCmd = new OnInstanceCmd(_getIdlDefCmd);
  public static final int _isWritableCmd = 7;
  public static final OnInstanceCmd isWritableCmd = new OnInstanceCmd(_isWritableCmd);
  public static final int _supportFileCmd = 8;
  public static final OnInstanceCmd supportFileCmd = new OnInstanceCmd(_supportFileCmd);
  public static final int _isOpenCmd = 9;
  public static final OnInstanceCmd isOpenCmd = new OnInstanceCmd(_isOpenCmd);
  public static final int _setOpenCmd = 10;
  public static final OnInstanceCmd setOpenCmd = new OnInstanceCmd(_setOpenCmd);
  public static final int _assocComponentCmd = 11;
  public static final OnInstanceCmd assocComponentCmd = new OnInstanceCmd(_assocComponentCmd);
  public static final int _assocArtifactCmd = 12;
  public static final OnInstanceCmd assocArtifactCmd = new OnInstanceCmd(_assocArtifactCmd);
  public static final int _saveInCmd = 13;
  public static final OnInstanceCmd saveInCmd = new OnInstanceCmd(_saveInCmd);
  public static final int _formalsCmd = 14;
  public static final OnInstanceCmd formalsCmd = new OnInstanceCmd(_formalsCmd);
  public static final int _actualsCmd = 15;
  public static final OnInstanceCmd actualsCmd = new OnInstanceCmd(_actualsCmd);
  public static final int _cppBodyCmd = 16;
  public static final OnInstanceCmd cppBodyCmd = new OnInstanceCmd(_cppBodyCmd);
  public static final int _javaBodyCmd = 17;
  public static final OnInstanceCmd javaBodyCmd = new OnInstanceCmd(_javaBodyCmd);
  public static final int _applyCmd = 18;
  public static final OnInstanceCmd applyCmd = new OnInstanceCmd(_applyCmd);
  public static final int _referencedByCmd = 19;
  public static final OnInstanceCmd referencedByCmd = new OnInstanceCmd(_referencedByCmd);
  public static final int _sideCmd = 20;
  public static final OnInstanceCmd sideCmd = new OnInstanceCmd(_sideCmd);
  //  just a mark
  public static final int _firstSetCmd = 50;
  public static final OnInstanceCmd firstSetCmd = new OnInstanceCmd(_firstSetCmd);
  public static final int _createCmd = 51;
  public static final OnInstanceCmd createCmd = new OnInstanceCmd(_createCmd);
  public static final int _setCoupleValueCmd = 52;
  public static final OnInstanceCmd setCoupleValueCmd = new OnInstanceCmd(_setCoupleValueCmd);
  public static final int _setDescriptionCmd = 53;
  public static final OnInstanceCmd setDescriptionCmd = new OnInstanceCmd(_setDescriptionCmd);
  public static final int _setNameCmd = 54;
  public static final OnInstanceCmd setNameCmd = new OnInstanceCmd(_setNameCmd);
  public static final int _setStereotypeCmd = 55;
  public static final OnInstanceCmd setStereotypeCmd = new OnInstanceCmd(_setStereotypeCmd);
  public static final int _addAssocClassCmd = 56;
  public static final OnInstanceCmd addAssocClassCmd = new OnInstanceCmd(_addAssocClassCmd);
  public static final int _removeAssocClassCmd = 57;
  public static final OnInstanceCmd removeAssocClassCmd = new OnInstanceCmd(_removeAssocClassCmd);
  public static final int _setAssocClassesCmd = 58;
  public static final OnInstanceCmd setAssocClassesCmd = new OnInstanceCmd(_setAssocClassesCmd);
  public static final int _setAssocDiagramCmd = 59;
  public static final OnInstanceCmd setAssocDiagramCmd = new OnInstanceCmd(_setAssocDiagramCmd);
  public static final int _setAssocViewCmd = 60;
  public static final OnInstanceCmd setAssocViewCmd = new OnInstanceCmd(_setAssocViewCmd);
  public static final int _addGetOperCmd = 61;
  public static final OnInstanceCmd addGetOperCmd = new OnInstanceCmd(_addGetOperCmd);
  public static final int _addSetOperCmd = 62;
  public static final OnInstanceCmd addSetOperCmd = new OnInstanceCmd(_addSetOperCmd);
  public static final int _setIsClassMemberCmd = 63;
  public static final OnInstanceCmd setIsClassMemberCmd = new OnInstanceCmd(_setIsClassMemberCmd);
  public static final int _setVisibilityCmd = 64;
  public static final OnInstanceCmd setVisibilityCmd = new OnInstanceCmd(_setVisibilityCmd);
  public static final int _setCppDeclCmd = 65;
  public static final OnInstanceCmd setCppDeclCmd = new OnInstanceCmd(_setCppDeclCmd);
  public static final int _setCppDefCmd = 66;
  public static final OnInstanceCmd setCppDefCmd = new OnInstanceCmd(_setCppDefCmd);
  public static final int _setJavaDeclCmd = 67;
  public static final OnInstanceCmd setJavaDeclCmd = new OnInstanceCmd(_setJavaDeclCmd);
  public static final int _setIdlDeclCmd = 68;
  public static final OnInstanceCmd setIdlDeclCmd = new OnInstanceCmd(_setIdlDeclCmd);
  public static final int _setCppVisibilityCmd = 69;
  public static final OnInstanceCmd setCppVisibilityCmd = new OnInstanceCmd(_setCppVisibilityCmd);
  public static final int _setIsReadOnlyCmd = 70;
  public static final OnInstanceCmd setIsReadOnlyCmd = new OnInstanceCmd(_setIsReadOnlyCmd);
  public static final int _setDefaultValueCmd = 71;
  public static final OnInstanceCmd setDefaultValueCmd = new OnInstanceCmd(_setDefaultValueCmd);
  public static final int _setTypeCmd = 72;
  public static final OnInstanceCmd setTypeCmd = new OnInstanceCmd(_setTypeCmd);
  public static final int _setIsVolatileCmd = 73;
  public static final OnInstanceCmd setIsVolatileCmd = new OnInstanceCmd(_setIsVolatileCmd);
  public static final int _setIsCppMutableCmd = 74;
  public static final OnInstanceCmd setIsCppMutableCmd = new OnInstanceCmd(_setIsCppMutableCmd);
  public static final int _setIsJavaTransientCmd = 75;
  public static final OnInstanceCmd setIsJavaTransientCmd = new OnInstanceCmd(_setIsJavaTransientCmd);
  public static final int _setIdlCaseCmd = 76;
  public static final OnInstanceCmd setIdlCaseCmd = new OnInstanceCmd(_setIdlCaseCmd);
  public static final int _setIsCppInlineCmd = 77;
  public static final OnInstanceCmd setIsCppInlineCmd = new OnInstanceCmd(_setIsCppInlineCmd);
  public static final int _setIsAbstractCmd = 78;
  public static final OnInstanceCmd setIsAbstractCmd = new OnInstanceCmd(_setIsAbstractCmd);
  public static final int _setBaseTypeCmd = 79;
  public static final OnInstanceCmd setBaseTypeCmd = new OnInstanceCmd(_setBaseTypeCmd);
  public static final int _setIsCppExternalCmd = 80;
  public static final OnInstanceCmd setIsCppExternalCmd = new OnInstanceCmd(_setIsCppExternalCmd);
  public static final int _setIsJavaExternalCmd = 81;
  public static final OnInstanceCmd setIsJavaExternalCmd = new OnInstanceCmd(_setIsJavaExternalCmd);
  public static final int _setIsIdlExternalCmd = 82;
  public static final OnInstanceCmd setIsIdlExternalCmd = new OnInstanceCmd(_setIsIdlExternalCmd);
  public static final int _setIsJavaPublicCmd = 83;
  public static final OnInstanceCmd setIsJavaPublicCmd = new OnInstanceCmd(_setIsJavaPublicCmd);
  public static final int _setIsJavaFinalCmd = 84;
  public static final OnInstanceCmd setIsJavaFinalCmd = new OnInstanceCmd(_setIsJavaFinalCmd);
  public static final int _setIsIdlLocalCmd = 85;
  public static final OnInstanceCmd setIsIdlLocalCmd = new OnInstanceCmd(_setIsIdlLocalCmd);
  public static final int _setIsIdlCustomCmd = 86;
  public static final OnInstanceCmd setIsIdlCustomCmd = new OnInstanceCmd(_setIsIdlCustomCmd);
  public static final int _setSwitchTypeCmd = 87;
  public static final OnInstanceCmd setSwitchTypeCmd = new OnInstanceCmd(_setSwitchTypeCmd);
  public static final int _removeFormalCmd = 88;
  public static final OnInstanceCmd removeFormalCmd = new OnInstanceCmd(_removeFormalCmd);
  public static final int _addFormalCmd = 89;
  public static final OnInstanceCmd addFormalCmd = new OnInstanceCmd(_addFormalCmd);
  public static final int _replaceFormalCmd = 90;
  public static final OnInstanceCmd replaceFormalCmd = new OnInstanceCmd(_replaceFormalCmd);
  public static final int _replaceActualCmd = 91;
  public static final OnInstanceCmd replaceActualCmd = new OnInstanceCmd(_replaceActualCmd);
  public static final int _setCppHCmd = 92;
  public static final OnInstanceCmd setCppHCmd = new OnInstanceCmd(_setCppHCmd);
  public static final int _setCppSrcCmd = 93;
  public static final OnInstanceCmd setCppSrcCmd = new OnInstanceCmd(_setCppSrcCmd);
  public static final int _setJavaSrcCmd = 94;
  public static final OnInstanceCmd setJavaSrcCmd = new OnInstanceCmd(_setJavaSrcCmd);
  public static final int _setIdlSrcCmd = 95;
  public static final OnInstanceCmd setIdlSrcCmd = new OnInstanceCmd(_setIdlSrcCmd);
  public static final int _addAssocArtifactCmd = 96;
  public static final OnInstanceCmd addAssocArtifactCmd = new OnInstanceCmd(_addAssocArtifactCmd);
  public static final int _removeAssocArtifactCmd = 97;
  public static final OnInstanceCmd removeAssocArtifactCmd = new OnInstanceCmd(_removeAssocArtifactCmd);
  public static final int _removeAllAssocArtifactsCmd = 98;
  public static final OnInstanceCmd removeAllAssocArtifactsCmd = new OnInstanceCmd(_removeAllAssocArtifactsCmd);
  public static final int _setReturnTypeCmd = 99;
  public static final OnInstanceCmd setReturnTypeCmd = new OnInstanceCmd(_setReturnTypeCmd);
  public static final int _setIsCppConstCmd = 100;
  public static final OnInstanceCmd setIsCppConstCmd = new OnInstanceCmd(_setIsCppConstCmd);
  public static final int _setIsCppFriendCmd = 101;
  public static final OnInstanceCmd setIsCppFriendCmd = new OnInstanceCmd(_setIsCppFriendCmd);
  public static final int _setIsCppVirtualCmd = 102;
  public static final OnInstanceCmd setIsCppVirtualCmd = new OnInstanceCmd(_setIsCppVirtualCmd);
  public static final int _setIsIdlTruncatableCmd = 103;
  public static final OnInstanceCmd setIsIdlTruncatableCmd = new OnInstanceCmd(_setIsIdlTruncatableCmd);
  public static final int _setCppBodyCmd = 104;
  public static final OnInstanceCmd setCppBodyCmd = new OnInstanceCmd(_setCppBodyCmd);
  public static final int _setCppNameSpecCmd = 105;
  public static final OnInstanceCmd setCppNameSpecCmd = new OnInstanceCmd(_setCppNameSpecCmd);
  public static final int _setJavaFinalCmd = 106;
  public static final OnInstanceCmd setJavaFinalCmd = new OnInstanceCmd(_setJavaFinalCmd);
  public static final int _setJavaSynchronizedCmd = 107;
  public static final OnInstanceCmd setJavaSynchronizedCmd = new OnInstanceCmd(_setJavaSynchronizedCmd);
  public static final int _setJavaBodyCmd = 108;
  public static final OnInstanceCmd setJavaBodyCmd = new OnInstanceCmd(_setJavaBodyCmd);
  public static final int _setJavaNameSpecCmd = 109;
  public static final OnInstanceCmd setJavaNameSpecCmd = new OnInstanceCmd(_setJavaNameSpecCmd);
  public static final int _setIsIdlOnewayCmd = 110;
  public static final OnInstanceCmd setIsIdlOnewayCmd = new OnInstanceCmd(_setIsIdlOnewayCmd);
  public static final int _setIdlNameSpecCmd = 111;
  public static final OnInstanceCmd setIdlNameSpecCmd = new OnInstanceCmd(_setIdlNameSpecCmd);
  public static final int _addParameterCmd = 112;
  public static final OnInstanceCmd addParameterCmd = new OnInstanceCmd(_addParameterCmd);
  public static final int _removeParameterCmd = 113;
  public static final OnInstanceCmd removeParameterCmd = new OnInstanceCmd(_removeParameterCmd);
  public static final int _replaceParameterCmd = 114;
  public static final OnInstanceCmd replaceParameterCmd = new OnInstanceCmd(_replaceParameterCmd);
  public static final int _addExceptionCmd = 115;
  public static final OnInstanceCmd addExceptionCmd = new OnInstanceCmd(_addExceptionCmd);
  public static final int _removeExceptionCmd = 116;
  public static final OnInstanceCmd removeExceptionCmd = new OnInstanceCmd(_removeExceptionCmd);
  public static final int _replaceExceptionCmd = 117;
  public static final OnInstanceCmd replaceExceptionCmd = new OnInstanceCmd(_replaceExceptionCmd);
  public static final int _setCppSrcDirCmd = 118;
  public static final OnInstanceCmd setCppSrcDirCmd = new OnInstanceCmd(_setCppSrcDirCmd);
  public static final int _setCppHDirCmd = 119;
  public static final OnInstanceCmd setCppHDirCmd = new OnInstanceCmd(_setCppHDirCmd);
  public static final int _setCppNamespaceCmd = 120;
  public static final OnInstanceCmd setCppNamespaceCmd = new OnInstanceCmd(_setCppNamespaceCmd);
  public static final int _setJavaDirCmd = 121;
  public static final OnInstanceCmd setJavaDirCmd = new OnInstanceCmd(_setJavaDirCmd);
  public static final int _setJavaPackageCmd = 122;
  public static final OnInstanceCmd setJavaPackageCmd = new OnInstanceCmd(_setJavaPackageCmd);
  public static final int _setIdlDirCmd = 123;
  public static final OnInstanceCmd setIdlDirCmd = new OnInstanceCmd(_setIdlDirCmd);
  public static final int _setIdlModuleCmd = 124;
  public static final OnInstanceCmd setIdlModuleCmd = new OnInstanceCmd(_setIdlModuleCmd);
  public static final int _setRoleNameCmd = 125;
  public static final OnInstanceCmd setRoleNameCmd = new OnInstanceCmd(_setRoleNameCmd);
  public static final int _setMultiplicityCmd = 126;
  public static final OnInstanceCmd setMultiplicityCmd = new OnInstanceCmd(_setMultiplicityCmd);
  public static final int _setCppVirtualInheritanceCmd = 127;
  public static final OnInstanceCmd setCppVirtualInheritanceCmd = new OnInstanceCmd(_setCppVirtualInheritanceCmd);
  public static final int _setMarkedCmd = 128;
  public static final OnInstanceCmd setMarkedCmd = new OnInstanceCmd(_setMarkedCmd);
  public static final int _setUmlEntryBehaviorCmd = 129;
  public static final OnInstanceCmd setUmlEntryBehaviorCmd = new OnInstanceCmd(_setUmlEntryBehaviorCmd);
  public static final int _setUmlExitBehaviorCmd = 130;
  public static final OnInstanceCmd setUmlExitBehaviorCmd = new OnInstanceCmd(_setUmlExitBehaviorCmd);
  public static final int _setUmlActivityCmd = 131;
  public static final OnInstanceCmd setUmlActivityCmd = new OnInstanceCmd(_setUmlActivityCmd);
  public static final int _setCppEntryBehaviorCmd = 132;
  public static final OnInstanceCmd setCppEntryBehaviorCmd = new OnInstanceCmd(_setCppEntryBehaviorCmd);
  public static final int _setCppExitBehaviorCmd = 133;
  public static final OnInstanceCmd setCppExitBehaviorCmd = new OnInstanceCmd(_setCppExitBehaviorCmd);
  public static final int _setCppActivityCmd = 134;
  public static final OnInstanceCmd setCppActivityCmd = new OnInstanceCmd(_setCppActivityCmd);
  public static final int _setJavaEntryBehaviorCmd = 135;
  public static final OnInstanceCmd setJavaEntryBehaviorCmd = new OnInstanceCmd(_setJavaEntryBehaviorCmd);
  public static final int _setJavaExitBehaviorCmd = 136;
  public static final OnInstanceCmd setJavaExitBehaviorCmd = new OnInstanceCmd(_setJavaExitBehaviorCmd);
  public static final int _setJavaActivityCmd = 137;
  public static final OnInstanceCmd setJavaActivityCmd = new OnInstanceCmd(_setJavaActivityCmd);
  public static final int _setUmlTriggerCmd = 138;
  public static final OnInstanceCmd setUmlTriggerCmd = new OnInstanceCmd(_setUmlTriggerCmd);
  public static final int _setUmlGuardCmd = 139;
  public static final OnInstanceCmd setUmlGuardCmd = new OnInstanceCmd(_setUmlGuardCmd);
  public static final int _setCppTriggerCmd = 140;
  public static final OnInstanceCmd setCppTriggerCmd = new OnInstanceCmd(_setCppTriggerCmd);
  public static final int _setCppGuardCmd = 141;
  public static final OnInstanceCmd setCppGuardCmd = new OnInstanceCmd(_setCppGuardCmd);
  public static final int _setJavaGuardCmd = 142;
  public static final OnInstanceCmd setJavaGuardCmd = new OnInstanceCmd(_setJavaGuardCmd);
  public static final int _setJavaTriggerCmd = 143;
  public static final OnInstanceCmd setJavaTriggerCmd = new OnInstanceCmd(_setJavaTriggerCmd);
  public static final int _setDefCmd = 144;
  public static final OnInstanceCmd setDefCmd = new OnInstanceCmd(_setDefCmd);
  public static final int _moveAfterCmd = 145;
  public static final OnInstanceCmd moveAfterCmd = new OnInstanceCmd(_moveAfterCmd);
  public static final int _setJavaAnnotationCmd = 146;
  public static final OnInstanceCmd setJavaAnnotationCmd = new OnInstanceCmd(_setJavaAnnotationCmd);
  public static final int _setRelationAssocClassCmd = 147;
  public static final OnInstanceCmd setRelationAssocClassCmd = new OnInstanceCmd(_setRelationAssocClassCmd);
  public static final int _setReadOnlyCmd = 148;
  public static final OnInstanceCmd setReadOnlyCmd = new OnInstanceCmd(_setReadOnlyCmd);
  public static final int _setSingleExecutionCmd = 149;
  public static final OnInstanceCmd setSingleExecutionCmd = new OnInstanceCmd(_setSingleExecutionCmd);
  public static final int _setUnmarshallCmd = 150;
  public static final OnInstanceCmd setUnmarshallCmd = new OnInstanceCmd(_setUnmarshallCmd);
  public static final int _setTimeEventCmd = 151;
  public static final OnInstanceCmd setTimeEventCmd = new OnInstanceCmd(_setTimeEventCmd);
  public static final int _setFlagCmd = 152;
  public static final OnInstanceCmd setFlagCmd = new OnInstanceCmd(_setFlagCmd);
  public static final int _setUniqueCmd = 153;
  public static final OnInstanceCmd setUniqueCmd = new OnInstanceCmd(_setUniqueCmd);
  public static final int _setStreamCmd = 154;
  public static final OnInstanceCmd setStreamCmd = new OnInstanceCmd(_setStreamCmd);
  public static final int _setInStateCmd = 155;
  public static final OnInstanceCmd setInStateCmd = new OnInstanceCmd(_setInStateCmd);
  public static final int _setOrderingCmd = 156;
  public static final OnInstanceCmd setOrderingCmd = new OnInstanceCmd(_setOrderingCmd);
  public static final int _setCppFrozenCmd = 157;
  public static final OnInstanceCmd setCppFrozenCmd = new OnInstanceCmd(_setCppFrozenCmd);
  public static final int _setJavaFrozenCmd = 158;
  public static final OnInstanceCmd setJavaFrozenCmd = new OnInstanceCmd(_setJavaFrozenCmd);
  public static final int _setIdlFrozenCmd = 159;
  public static final OnInstanceCmd setIdlFrozenCmd = new OnInstanceCmd(_setIdlFrozenCmd);

  private int value;

  public int value() {
    return value;
  }

  public static OnInstanceCmd fromInt(int value) {
    switch (value) {
    case _parentCmd: return parentCmd;
    case _childrenCmd: return childrenCmd;
    case _getDefCmd: return getDefCmd;
    case _getUmlDefCmd: return getUmlDefCmd;
    case _getCppDefCmd: return getCppDefCmd;
    case _getJavaDefCmd: return getJavaDefCmd;
    case _getIdlDefCmd: return getIdlDefCmd;
    case _isWritableCmd: return isWritableCmd;
    case _supportFileCmd: return supportFileCmd;
    case _isOpenCmd: return isOpenCmd;
    case _setOpenCmd: return setOpenCmd;
    case _assocComponentCmd: return assocComponentCmd;
    case _assocArtifactCmd: return assocArtifactCmd;
    case _saveInCmd: return saveInCmd;
    case _formalsCmd: return formalsCmd;
    case _actualsCmd: return actualsCmd;
    case _cppBodyCmd: return cppBodyCmd;
    case _javaBodyCmd: return javaBodyCmd;
    case _applyCmd: return applyCmd;
    case _referencedByCmd: return referencedByCmd;
    case _sideCmd: return sideCmd;
    case _firstSetCmd: return firstSetCmd;
    case _createCmd: return createCmd;
    case _setCoupleValueCmd: return setCoupleValueCmd;
    case _setDescriptionCmd: return setDescriptionCmd;
    case _setNameCmd: return setNameCmd;
    case _setStereotypeCmd: return setStereotypeCmd;
    case _addAssocClassCmd: return addAssocClassCmd;
    case _removeAssocClassCmd: return removeAssocClassCmd;
    case _setAssocClassesCmd: return setAssocClassesCmd;
    case _setAssocDiagramCmd: return setAssocDiagramCmd;
    case _setAssocViewCmd: return setAssocViewCmd;
    case _addGetOperCmd: return addGetOperCmd;
    case _addSetOperCmd: return addSetOperCmd;
    case _setIsClassMemberCmd: return setIsClassMemberCmd;
    case _setVisibilityCmd: return setVisibilityCmd;
    case _setCppDeclCmd: return setCppDeclCmd;
    case _setCppDefCmd: return setCppDefCmd;
    case _setJavaDeclCmd: return setJavaDeclCmd;
    case _setIdlDeclCmd: return setIdlDeclCmd;
    case _setCppVisibilityCmd: return setCppVisibilityCmd;
    case _setIsReadOnlyCmd: return setIsReadOnlyCmd;
    case _setDefaultValueCmd: return setDefaultValueCmd;
    case _setTypeCmd: return setTypeCmd;
    case _setIsVolatileCmd: return setIsVolatileCmd;
    case _setIsCppMutableCmd: return setIsCppMutableCmd;
    case _setIsJavaTransientCmd: return setIsJavaTransientCmd;
    case _setIdlCaseCmd: return setIdlCaseCmd;
    case _setIsCppInlineCmd: return setIsCppInlineCmd;
    case _setIsAbstractCmd: return setIsAbstractCmd;
    case _setBaseTypeCmd: return setBaseTypeCmd;
    case _setIsCppExternalCmd: return setIsCppExternalCmd;
    case _setIsJavaExternalCmd: return setIsJavaExternalCmd;
    case _setIsIdlExternalCmd: return setIsIdlExternalCmd;
    case _setIsJavaPublicCmd: return setIsJavaPublicCmd;
    case _setIsJavaFinalCmd: return setIsJavaFinalCmd;
    case _setIsIdlLocalCmd: return setIsIdlLocalCmd;
    case _setIsIdlCustomCmd: return setIsIdlCustomCmd;
    case _setSwitchTypeCmd: return setSwitchTypeCmd;
    case _removeFormalCmd: return removeFormalCmd;
    case _addFormalCmd: return addFormalCmd;
    case _replaceFormalCmd: return replaceFormalCmd;
    case _replaceActualCmd: return replaceActualCmd;
    case _setCppHCmd: return setCppHCmd;
    case _setCppSrcCmd: return setCppSrcCmd;
    case _setJavaSrcCmd: return setJavaSrcCmd;
    case _setIdlSrcCmd: return setIdlSrcCmd;
    case _addAssocArtifactCmd: return addAssocArtifactCmd;
    case _removeAssocArtifactCmd: return removeAssocArtifactCmd;
    case _removeAllAssocArtifactsCmd: return removeAllAssocArtifactsCmd;
    case _setReturnTypeCmd: return setReturnTypeCmd;
    case _setIsCppConstCmd: return setIsCppConstCmd;
    case _setIsCppFriendCmd: return setIsCppFriendCmd;
    case _setIsCppVirtualCmd: return setIsCppVirtualCmd;
    case _setIsIdlTruncatableCmd: return setIsIdlTruncatableCmd;
    case _setCppBodyCmd: return setCppBodyCmd;
    case _setCppNameSpecCmd: return setCppNameSpecCmd;
    case _setJavaFinalCmd: return setJavaFinalCmd;
    case _setJavaSynchronizedCmd: return setJavaSynchronizedCmd;
    case _setJavaBodyCmd: return setJavaBodyCmd;
    case _setJavaNameSpecCmd: return setJavaNameSpecCmd;
    case _setIsIdlOnewayCmd: return setIsIdlOnewayCmd;
    case _setIdlNameSpecCmd: return setIdlNameSpecCmd;
    case _addParameterCmd: return addParameterCmd;
    case _removeParameterCmd: return removeParameterCmd;
    case _replaceParameterCmd: return replaceParameterCmd;
    case _addExceptionCmd: return addExceptionCmd;
    case _removeExceptionCmd: return removeExceptionCmd;
    case _replaceExceptionCmd: return replaceExceptionCmd;
    case _setCppSrcDirCmd: return setCppSrcDirCmd;
    case _setCppHDirCmd: return setCppHDirCmd;
    case _setCppNamespaceCmd: return setCppNamespaceCmd;
    case _setJavaDirCmd: return setJavaDirCmd;
    case _setJavaPackageCmd: return setJavaPackageCmd;
    case _setIdlDirCmd: return setIdlDirCmd;
    case _setIdlModuleCmd: return setIdlModuleCmd;
    case _setRoleNameCmd: return setRoleNameCmd;
    case _setMultiplicityCmd: return setMultiplicityCmd;
    case _setCppVirtualInheritanceCmd: return setCppVirtualInheritanceCmd;
    case _setMarkedCmd: return setMarkedCmd;
    case _setUmlEntryBehaviorCmd: return setUmlEntryBehaviorCmd;
    case _setUmlExitBehaviorCmd: return setUmlExitBehaviorCmd;
    case _setUmlActivityCmd: return setUmlActivityCmd;
    case _setCppEntryBehaviorCmd: return setCppEntryBehaviorCmd;
    case _setCppExitBehaviorCmd: return setCppExitBehaviorCmd;
    case _setCppActivityCmd: return setCppActivityCmd;
    case _setJavaEntryBehaviorCmd: return setJavaEntryBehaviorCmd;
    case _setJavaExitBehaviorCmd: return setJavaExitBehaviorCmd;
    case _setJavaActivityCmd: return setJavaActivityCmd;
    case _setUmlTriggerCmd: return setUmlTriggerCmd;
    case _setUmlGuardCmd: return setUmlGuardCmd;
    case _setCppTriggerCmd: return setCppTriggerCmd;
    case _setCppGuardCmd: return setCppGuardCmd;
    case _setJavaGuardCmd: return setJavaGuardCmd;
    case _setJavaTriggerCmd: return setJavaTriggerCmd;
    case _setDefCmd: return setDefCmd;
    case _moveAfterCmd: return moveAfterCmd;
    case _setJavaAnnotationCmd: return setJavaAnnotationCmd;
    case _setRelationAssocClassCmd: return setRelationAssocClassCmd;
    case _setReadOnlyCmd: return setReadOnlyCmd;
    case _setSingleExecutionCmd: return setSingleExecutionCmd;
    case _setUnmarshallCmd: return setUnmarshallCmd;
    case _setTimeEventCmd: return setTimeEventCmd;
    case _setFlagCmd: return setFlagCmd;
    case _setUniqueCmd: return setUniqueCmd;
    case _setStreamCmd: return setStreamCmd;
    case _setInStateCmd: return setInStateCmd;
    case _setOrderingCmd: return setOrderingCmd;
    case _setCppFrozenCmd: return setCppFrozenCmd;
    case _setJavaFrozenCmd: return setJavaFrozenCmd;
    case _setIdlFrozenCmd: return setIdlFrozenCmd;
    default: throw new Error();
    }
  }

  private OnInstanceCmd(int v) { value = v; }; 
}
