<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="src" nsURI="pathmap:/src platform:/resource/TestKermeta/src/MetaModel.ecore" nsPrefix="src">
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" eType="//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="//StateVertex" eOpposite="//StateVertex/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="//StateVertex" eOpposite="//StateVertex/incoming"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine" eSuperTypes="//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="top" eType="//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateVertex" eSuperTypes="//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="//CompositeState" eOpposite="//CompositeState/subvertex"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" ordered="false" upperBound="-1" eType="//Transition" eOpposite="//Transition/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" ordered="false" upperBound="-1" eType="//Transition" eOpposite="//Transition/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="//StateVertex"/>
  <eClassifiers xsi:type="ecore:EClass" name="PseudoState" eSuperTypes="//StateVertex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeState" eSuperTypes="//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subvertex" ordered="false" upperBound="-1" eType="//StateVertex" containment="true" eOpposite="//StateVertex/container"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleState" eSuperTypes="//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="FinalState" eSuperTypes="//State"/>
  <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
</ecore:EPackage>
