<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EAnnotation source="ModellingUnit">
    <details key="require" value="http://www.eclipse.org/emf/2002/Ecore|"/>
  </ecore:EAnnotation>
  <ecore:EPackage name="pattern" nsURI="platform:/resource/SmartAdapters/metamodel/domain/FSMMMPattern.ecore#/pattern"
      nsPrefix="pattern">
    <eSubpackages name="FSM" nsURI="platform:/resource/SmartAdapters/metamodel/domain/FSMMMPattern.ecore#/pattern/FSM"
        nsPrefix="FSM">
      <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="../../../fr.irisa.triskell.kermeta.patternmatching/src/kermeta/pattern/metamodel/PatternFramework.ecore#//PObject">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#/1/FSM/label">
          <eAnnotations source="kermeta">
            <details key="isComposite" value="true"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="../../../fr.irisa.triskell.kermeta.patternmatching/src/kermeta/pattern/metamodel/PatternFramework.ecore#//PObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#/1/FSM/State"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#/1/FSM/State"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Fsm" eSuperTypes="../../../fr.irisa.triskell.kermeta.patternmatching/src/kermeta/pattern/metamodel/PatternFramework.ecore#//PObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
            eType="#/1/FSM/State" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
            eType="#/1/FSM/Transition" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EDataType" name="label" instanceClassName="java.lang.String"/>
    </eSubpackages>
  </ecore:EPackage>
</xmi:XMI>
