package kermeta.kunit
trait KunitImplicitConversion {
 implicit def Aspect(v : kermeta.kunit.InvalidTestCaseNameException) = v.asInstanceOf[kermeta.kunit.InvalidTestCaseNameExceptionAspect]
 implicit def Aspect(v : kermeta.kunit.InvalidTestCaseNameExceptionAspect) = v.asInstanceOf[kermeta.kunit.InvalidTestCaseNameException]
 implicit def Aspect(v : kermeta.kunit.InvalidParameterException) = v.asInstanceOf[kermeta.kunit.InvalidParameterExceptionAspect]
 implicit def Aspect(v : kermeta.kunit.InvalidParameterExceptionAspect) = v.asInstanceOf[kermeta.kunit.InvalidParameterException]
 implicit def Aspect(v : kermeta.kunit.Fallible) = v.asInstanceOf[kermeta.kunit.FallibleAspect]
 implicit def Aspect(v : kermeta.kunit.FallibleAspect) = v.asInstanceOf[kermeta.kunit.Fallible]
 implicit def Aspect(v : kermeta.kunit.Log) = v.asInstanceOf[kermeta.kunit.LogAspect]
 implicit def Aspect(v : kermeta.kunit.LogAspect) = v.asInstanceOf[kermeta.kunit.Log]
 implicit def Aspect(v : kermeta.kunit.Failure) = v.asInstanceOf[kermeta.kunit.FailureAspect]
 implicit def Aspect(v : kermeta.kunit.FailureAspect) = v.asInstanceOf[kermeta.kunit.Failure]
 implicit def Aspect(v : kermeta.kunit.Error) = v.asInstanceOf[kermeta.kunit.ErrorAspect]
 implicit def Aspect(v : kermeta.kunit.ErrorAspect) = v.asInstanceOf[kermeta.kunit.Error]
 implicit def Aspect(v : kermeta.kunit.Test) = v.asInstanceOf[kermeta.kunit.TestAspect]
 implicit def Aspect(v : kermeta.kunit.TestAspect) = v.asInstanceOf[kermeta.kunit.Test]
 implicit def Aspect(v : kermeta.kunit.TestSuite) = v.asInstanceOf[kermeta.kunit.TestSuiteAspect]
 implicit def Aspect(v : kermeta.kunit.TestSuiteAspect) = v.asInstanceOf[kermeta.kunit.TestSuite]
 implicit def Aspect(v : kermeta.kunit.TestCase) = v.asInstanceOf[kermeta.kunit.TestCaseAspect]
 implicit def Aspect(v : kermeta.kunit.TestCaseAspect) = v.asInstanceOf[kermeta.kunit.TestCase]
 implicit def Aspect(v : kermeta.kunit.TestRunner) = v.asInstanceOf[kermeta.kunit.TestRunnerAspect]
 implicit def Aspect(v : kermeta.kunit.TestRunnerAspect) = v.asInstanceOf[kermeta.kunit.TestRunner]
 implicit def Aspect(v : kermeta.kunit.AbstractFallible) = v.asInstanceOf[kermeta.kunit.AbstractFallibleAspect]
 implicit def Aspect(v : kermeta.kunit.AbstractFallibleAspect) = v.asInstanceOf[kermeta.kunit.AbstractFallible]
 implicit def Aspect(v : kermeta.kunit.AssertionFailedError) = v.asInstanceOf[kermeta.kunit.AssertionFailedErrorAspect]
 implicit def Aspect(v : kermeta.kunit.AssertionFailedErrorAspect) = v.asInstanceOf[kermeta.kunit.AssertionFailedError]
 implicit def Aspect(v : kermeta.kunit.Assert) = v.asInstanceOf[kermeta.kunit.AssertAspect]
 implicit def Aspect(v : kermeta.kunit.AssertAspect) = v.asInstanceOf[kermeta.kunit.Assert]
}


object KunitConversions{
 implicit def Aspect(v : kermeta.kunit.InvalidTestCaseNameException) = v.asInstanceOf[kermeta.kunit.InvalidTestCaseNameExceptionAspect]
 implicit def Aspect(v : kermeta.kunit.InvalidTestCaseNameExceptionAspect) = v.asInstanceOf[kermeta.kunit.InvalidTestCaseNameException]
 implicit def Aspect(v : kermeta.kunit.InvalidParameterException) = v.asInstanceOf[kermeta.kunit.InvalidParameterExceptionAspect]
 implicit def Aspect(v : kermeta.kunit.InvalidParameterExceptionAspect) = v.asInstanceOf[kermeta.kunit.InvalidParameterException]
 implicit def Aspect(v : kermeta.kunit.Fallible) = v.asInstanceOf[kermeta.kunit.FallibleAspect]
 implicit def Aspect(v : kermeta.kunit.FallibleAspect) = v.asInstanceOf[kermeta.kunit.Fallible]
 implicit def Aspect(v : kermeta.kunit.Log) = v.asInstanceOf[kermeta.kunit.LogAspect]
 implicit def Aspect(v : kermeta.kunit.LogAspect) = v.asInstanceOf[kermeta.kunit.Log]
 implicit def Aspect(v : kermeta.kunit.Failure) = v.asInstanceOf[kermeta.kunit.FailureAspect]
 implicit def Aspect(v : kermeta.kunit.FailureAspect) = v.asInstanceOf[kermeta.kunit.Failure]
 implicit def Aspect(v : kermeta.kunit.Error) = v.asInstanceOf[kermeta.kunit.ErrorAspect]
 implicit def Aspect(v : kermeta.kunit.ErrorAspect) = v.asInstanceOf[kermeta.kunit.Error]
 implicit def Aspect(v : kermeta.kunit.Test) = v.asInstanceOf[kermeta.kunit.TestAspect]
 implicit def Aspect(v : kermeta.kunit.TestAspect) = v.asInstanceOf[kermeta.kunit.Test]
 implicit def Aspect(v : kermeta.kunit.TestSuite) = v.asInstanceOf[kermeta.kunit.TestSuiteAspect]
 implicit def Aspect(v : kermeta.kunit.TestSuiteAspect) = v.asInstanceOf[kermeta.kunit.TestSuite]
 implicit def Aspect(v : kermeta.kunit.TestCase) = v.asInstanceOf[kermeta.kunit.TestCaseAspect]
 implicit def Aspect(v : kermeta.kunit.TestCaseAspect) = v.asInstanceOf[kermeta.kunit.TestCase]
 implicit def Aspect(v : kermeta.kunit.TestRunner) = v.asInstanceOf[kermeta.kunit.TestRunnerAspect]
 implicit def Aspect(v : kermeta.kunit.TestRunnerAspect) = v.asInstanceOf[kermeta.kunit.TestRunner]
 implicit def Aspect(v : kermeta.kunit.AbstractFallible) = v.asInstanceOf[kermeta.kunit.AbstractFallibleAspect]
 implicit def Aspect(v : kermeta.kunit.AbstractFallibleAspect) = v.asInstanceOf[kermeta.kunit.AbstractFallible]
 implicit def Aspect(v : kermeta.kunit.AssertionFailedError) = v.asInstanceOf[kermeta.kunit.AssertionFailedErrorAspect]
 implicit def Aspect(v : kermeta.kunit.AssertionFailedErrorAspect) = v.asInstanceOf[kermeta.kunit.AssertionFailedError]
 implicit def Aspect(v : kermeta.kunit.Assert) = v.asInstanceOf[kermeta.kunit.AssertAspect]
 implicit def Aspect(v : kermeta.kunit.AssertAspect) = v.asInstanceOf[kermeta.kunit.Assert]

/*	 implicit def Aspect(v : kermeta.kunit.Main) = v.asInstanceOf[kermeta.kunit.Main]
 implicit def Aspect(v : kermeta.kunit.MainAspect) = v.asInstanceOf[kermeta.kunit.Main]
 implicit def Aspect(v : kermeta.kunit.InvalidTestCaseNameException) = v.asInstanceOf[kermeta.kunit.InvalidTestCaseNameException]
 implicit def Aspect(v : kermeta.kunit.InvalidTestCaseNameExceptionAspect) = v.asInstanceOf[kermeta.kunit.InvalidTestCaseNameException]
 implicit def Aspect(v : kermeta.kunit.InvalidParameterException) = v.asInstanceOf[kermeta.kunit.InvalidParameterException]
 implicit def Aspect(v : kermeta.kunit.InvalidParameterExceptionAspect) = v.asInstanceOf[kermeta.kunit.InvalidParameterException]
 implicit def Aspect(v : kermeta.kunit.Fallible) = v.asInstanceOf[kermeta.kunit.FallibleAspect]
 implicit def Aspect(v : kermeta.kunit.FallibleAspect) = v.asInstanceOf[kermeta.kunit.Fallible]
 implicit def Aspect(v : kermeta.kunit.Log) = v.asInstanceOf[kermeta.kunit.Log]
 implicit def Aspect(v : kermeta.kunit.LogAspect) = v.asInstanceOf[kermeta.kunit.Log]
 implicit def Aspect(v : kermeta.kunit.Failure) = v.asInstanceOf[kermeta.kunit.Failure]
 implicit def Aspect(v : kermeta.kunit.FailureAspect) = v.asInstanceOf[kermeta.kunit.Failure]
 implicit def Aspect(v : kermeta.kunit.Error) = v.asInstanceOf[kermeta.kunit.Error]
 implicit def Aspect(v : kermeta.kunit.ErrorAspect) = v.asInstanceOf[kermeta.kunit.Error]
 implicit def Aspect(v : kermeta.kunit.Test) = { v match {
	 case (ys : TestSuite) => 	  ys.asInstanceOf[kermeta.kunit.TestSuite]
	 case (ys : Test) =>  ys.asInstanceOf[kermeta.kunit.Test]
 	}
 }
 implicit def Aspect(v : kermeta.kunit.TestAspect) = v.asInstanceOf[kermeta.kunit.Test]
 implicit def Aspect(v : kermeta.kunit.TestSuite) = v.asInstanceOf[kermeta.kunit.TestSuite]
 implicit def Aspect(v : kermeta.kunit.TestSuiteAspect) = v.asInstanceOf[kermeta.kunit.TestSuite]
 implicit def Aspect(v : kermeta.kunit.TestCase) = v.asInstanceOf[kermeta.kunit.TestCase]
 implicit def Aspect(v : kermeta.kunit.TestCaseAspect) = v.asInstanceOf[kermeta.kunit.TestCase]
 implicit def Aspect(v : kermeta.kunit.TestRunner) = v.asInstanceOf[kermeta.kunit.TestRunner]
 implicit def Aspect(v : kermeta.kunit.TestRunnerAspect) = v.asInstanceOf[kermeta.kunit.TestRunner]
 implicit def Aspect(v : kermeta.kunit.AbstractFallible) = v.asInstanceOf[kermeta.kunit.AbstractFallible]
 implicit def Aspect(v : kermeta.kunit.AbstractFallibleAspect) = v.asInstanceOf[kermeta.kunit.AbstractFallible]
 implicit def Aspect(v : kermeta.kunit.AssertionFailedError) = v.asInstanceOf[kermeta.kunit.AssertionFailedError]
 implicit def Aspect(v : kermeta.kunit.AssertionFailedErrorAspect) = v.asInstanceOf[kermeta.kunit.AssertionFailedError]
 implicit def Aspect(v : kermeta.kunit.Assert) = v.asInstanceOf[kermeta.kunit.Assert]
 implicit def Aspect(v : kermeta.kunit.AssertAspect) = v.asInstanceOf[kermeta.kunit.Assert]
*/}

