package kermeta.kunit
trait KunitImplicitConversion {
 implicit def richAspect(v : kermeta.kunit.Main) = v.asInstanceOf[kermeta.kunit.RichMain]
 implicit def richAspect(v : kermeta.kunit.MainAspect) = v.asInstanceOf[kermeta.kunit.RichMain]
 implicit def richAspect(v : kermeta.kunit.InvalidTestCaseNameException) = v.asInstanceOf[kermeta.kunit.RichInvalidTestCaseNameException]
 implicit def richAspect(v : kermeta.kunit.InvalidTestCaseNameExceptionAspect) = v.asInstanceOf[kermeta.kunit.RichInvalidTestCaseNameException]
 implicit def richAspect(v : kermeta.kunit.InvalidParameterException) = v.asInstanceOf[kermeta.kunit.RichInvalidParameterException]
 implicit def richAspect(v : kermeta.kunit.InvalidParameterExceptionAspect) = v.asInstanceOf[kermeta.kunit.RichInvalidParameterException]
 implicit def richAspect(v : kermeta.kunit.Fallible) = v.asInstanceOf[kermeta.kunit.RichFallible]
 implicit def richAspect(v : kermeta.kunit.FallibleAspect) = v.asInstanceOf[kermeta.kunit.RichFallible]
 implicit def richAspect(v : kermeta.kunit.Log) = v.asInstanceOf[kermeta.kunit.RichLog]
 implicit def richAspect(v : kermeta.kunit.LogAspect) = v.asInstanceOf[kermeta.kunit.RichLog]
 implicit def richAspect(v : kermeta.kunit.Failure) = v.asInstanceOf[kermeta.kunit.RichFailure]
 implicit def richAspect(v : kermeta.kunit.FailureAspect) = v.asInstanceOf[kermeta.kunit.RichFailure]
 implicit def richAspect(v : kermeta.kunit.Error) = v.asInstanceOf[kermeta.kunit.RichError]
 implicit def richAspect(v : kermeta.kunit.ErrorAspect) = v.asInstanceOf[kermeta.kunit.RichError]
 implicit def richAspect(v : kermeta.kunit.Test) = v.asInstanceOf[kermeta.kunit.RichTest]
 implicit def richAspect(v : kermeta.kunit.TestAspect) = v.asInstanceOf[kermeta.kunit.RichTest]
 implicit def richAspect(v : kermeta.kunit.TestSuite) = v.asInstanceOf[kermeta.kunit.RichTestSuite]
 implicit def richAspect(v : kermeta.kunit.TestSuiteAspect) = v.asInstanceOf[kermeta.kunit.RichTestSuite]
 implicit def richAspect(v : kermeta.kunit.TestCase) = v.asInstanceOf[kermeta.kunit.RichTestCase]
 implicit def richAspect(v : kermeta.kunit.TestCaseAspect) = v.asInstanceOf[kermeta.kunit.RichTestCase]
 implicit def richAspect(v : kermeta.kunit.TestRunner) = v.asInstanceOf[kermeta.kunit.RichTestRunner]
 implicit def richAspect(v : kermeta.kunit.TestRunnerAspect) = v.asInstanceOf[kermeta.kunit.RichTestRunner]
 implicit def richAspect(v : kermeta.kunit.AbstractFallible) = v.asInstanceOf[kermeta.kunit.RichAbstractFallible]
 implicit def richAspect(v : kermeta.kunit.AbstractFallibleAspect) = v.asInstanceOf[kermeta.kunit.RichAbstractFallible]
 implicit def richAspect(v : kermeta.kunit.AssertionFailedError) = v.asInstanceOf[kermeta.kunit.RichAssertionFailedError]
 implicit def richAspect(v : kermeta.kunit.AssertionFailedErrorAspect) = v.asInstanceOf[kermeta.kunit.RichAssertionFailedError]
 implicit def richAspect(v : kermeta.kunit.Assert) = v.asInstanceOf[kermeta.kunit.RichAssert]
 implicit def richAspect(v : kermeta.kunit.AssertAspect) = v.asInstanceOf[kermeta.kunit.RichAssert]
}

object KunitConversions{
	 implicit def richAspect(v : kermeta.kunit.Main) = v.asInstanceOf[kermeta.kunit.RichMain]
 implicit def richAspect(v : kermeta.kunit.MainAspect) = v.asInstanceOf[kermeta.kunit.RichMain]
 implicit def richAspect(v : kermeta.kunit.InvalidTestCaseNameException) = v.asInstanceOf[kermeta.kunit.RichInvalidTestCaseNameException]
 implicit def richAspect(v : kermeta.kunit.InvalidTestCaseNameExceptionAspect) = v.asInstanceOf[kermeta.kunit.RichInvalidTestCaseNameException]
 implicit def richAspect(v : kermeta.kunit.InvalidParameterException) = v.asInstanceOf[kermeta.kunit.RichInvalidParameterException]
 implicit def richAspect(v : kermeta.kunit.InvalidParameterExceptionAspect) = v.asInstanceOf[kermeta.kunit.RichInvalidParameterException]
 implicit def richAspect(v : kermeta.kunit.Fallible) = v.asInstanceOf[kermeta.kunit.RichFallible]
 implicit def richAspect(v : kermeta.kunit.FallibleAspect) = v.asInstanceOf[kermeta.kunit.RichFallible]
 implicit def richAspect(v : kermeta.kunit.Log) = v.asInstanceOf[kermeta.kunit.RichLog]
 implicit def richAspect(v : kermeta.kunit.LogAspect) = v.asInstanceOf[kermeta.kunit.RichLog]
 implicit def richAspect(v : kermeta.kunit.Failure) = v.asInstanceOf[kermeta.kunit.RichFailure]
 implicit def richAspect(v : kermeta.kunit.FailureAspect) = v.asInstanceOf[kermeta.kunit.RichFailure]
 implicit def richAspect(v : kermeta.kunit.Error) = v.asInstanceOf[kermeta.kunit.RichError]
 implicit def richAspect(v : kermeta.kunit.ErrorAspect) = v.asInstanceOf[kermeta.kunit.RichError]
 implicit def richAspect(v : kermeta.kunit.Test) = v.asInstanceOf[kermeta.kunit.RichTest]
 implicit def richAspect(v : kermeta.kunit.TestAspect) = v.asInstanceOf[kermeta.kunit.RichTest]
 implicit def richAspect(v : kermeta.kunit.TestSuite) = v.asInstanceOf[kermeta.kunit.RichTestSuite]
 implicit def richAspect(v : kermeta.kunit.TestSuiteAspect) = v.asInstanceOf[kermeta.kunit.RichTestSuite]
 implicit def richAspect(v : kermeta.kunit.TestCase) = v.asInstanceOf[kermeta.kunit.RichTestCase]
 implicit def richAspect(v : kermeta.kunit.TestCaseAspect) = v.asInstanceOf[kermeta.kunit.RichTestCase]
 implicit def richAspect(v : kermeta.kunit.TestRunner) = v.asInstanceOf[kermeta.kunit.RichTestRunner]
 implicit def richAspect(v : kermeta.kunit.TestRunnerAspect) = v.asInstanceOf[kermeta.kunit.RichTestRunner]
 implicit def richAspect(v : kermeta.kunit.AbstractFallible) = v.asInstanceOf[kermeta.kunit.RichAbstractFallible]
 implicit def richAspect(v : kermeta.kunit.AbstractFallibleAspect) = v.asInstanceOf[kermeta.kunit.RichAbstractFallible]
 implicit def richAspect(v : kermeta.kunit.AssertionFailedError) = v.asInstanceOf[kermeta.kunit.RichAssertionFailedError]
 implicit def richAspect(v : kermeta.kunit.AssertionFailedErrorAspect) = v.asInstanceOf[kermeta.kunit.RichAssertionFailedError]
 implicit def richAspect(v : kermeta.kunit.Assert) = v.asInstanceOf[kermeta.kunit.RichAssert]
 implicit def richAspect(v : kermeta.kunit.AssertAspect) = v.asInstanceOf[kermeta.kunit.RichAssert]
}

