<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EAnnotation source="ModelingUnit">
    <details key="require" value="kermeta|"/>
    <details key="using" value="src|"/>
  </ecore:EAnnotation>
  <ecore:EPackage name="src" nsURI="http://SimpleMain" nsPrefix="src">
    <eClassifiers xsi:type="ecore:EClass" name="Main">
      <eSuperTypes href="platform:/resource/fr.irisa.triskell.kermeta.io/src/kermeta/kermeta_java.ecore#/1/language/structure/Object"/>
      <eOperations name="main">
        <eAnnotations source="kermeta">
          <details key="body" value="do&#xA;&#x9;stdio.writeln(&quot;-----------------------------------------&quot;)&#xA;&#x9;stdio.writeln(&quot;Start&quot;)&#xA;&#x9;stdio.writeln(&quot;-----------------------------------------&quot;)&#xA;&#x9;stdio.writeln(&quot;After Save&quot;)&#xA;end"/>
        </eAnnotations>
        <eType xsi:type="ecore:EClass" href="platform:/resource/fr.irisa.triskell.kermeta.io/src/kermeta/standard/primitive_types.ecore#/1/standard/Void"/>
      </eOperations>
      <eOperations name="truc" ordered="false">
        <eAnnotations source="kermeta">
          <details key="body" value="do&#xA;&#x9;var truc2 : kermeta::standard::String init &quot;dsdq&quot;&#xA;end"/>
        </eAnnotations>
        <eType xsi:type="ecore:EClass" href="platform:/resource/fr.irisa.triskell.kermeta.io/src/kermeta/standard/primitive_types.ecore#/1/standard/Void"/>
        <eParameters name="machin">
          <eType xsi:type="ecore:EClass" href="platform:/resource/fr.irisa.triskell.kermeta.io/src/kermeta/standard/primitive_types.ecore#/1/standard/String"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="_KermetaSpecialTypesAlias_" instanceClassName="java.lang.Object"/>
  </ecore:EPackage>
  <ecore:EAnnotation source="dependentResource"/>
</xmi:XMI>
