<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="art2adaptation"
    nsURI="http://art2adaptation/1.0" nsPrefix="art2adaptation">
  <eClassifiers xsi:type="ecore:EClass" name="AdaptationPrimitive"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdaptationModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adaptations" upperBound="-1"
        eType="#//AdaptationPrimitive" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentTypeAdaptation" eSuperTypes="#//AdaptationPrimitive">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="ecore:EClass ../../org.kermeta.art2.model/metamodel/art.ecore#//ComponentType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInstanceAdaptation" eSuperTypes="#//AdaptationPrimitive">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="ecore:EClass ../../org.kermeta.art2.model/metamodel/art.ecore#//ComponentInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddComponentType" eSuperTypes="#//ComponentTypeAdaptation"/>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveComponentType" eSuperTypes="#//ComponentTypeAdaptation"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddComponentInstance" eSuperTypes="#//ComponentInstanceAdaptation"/>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveComponentInstance" eSuperTypes="#//ComponentInstanceAdaptation"/>
</ecore:EPackage>
