<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kermeta"
    nsURI="" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="Zoo"/>
  <eSubpackages name="language">
    <eClassifiers xsi:type="ecore:EClass" name="Foo"/>
    <eSubpackages name="structure" nsURI="" nsPrefix="">
      <eClassifiers xsi:type="ecore:EClass" name="Nabab"/>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
