<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="diagnostic"
    nsURI="http://org.kermeta.diagnostic/1.0" nsPrefix="diagnostic">
  <eClassifiers xsi:type="ecore:EClass" name="DiagnosticModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagnostics" upperBound="-1"
        eType="#//ConstraintDiagnostic" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//Reference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintDiagnostic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="appliesTo" lowerBound="1"
        eType="#//Reference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="failedConstraint" lowerBound="1"
        eType="#//Constraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="InvariantProxy" eSuperTypes="#//Invariant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mmUri" lowerBound="1" eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaclassQualifiedName"
        lowerBound="1" eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invariantName" lowerBound="1"
        eType="#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="PostCondition" abstract="true" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Invariant" abstract="true" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="PreCondition" abstract="true" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelReference" eSuperTypes="#//Reference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedObject" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
</ecore:EPackage>
