package ScalaAspect.org.eclipse.emf.ecore
 class RichEAttribute extends org.eclipse.emf.ecore.impl.EAttributeImpl with ScalaAspect.org.eclipse.emf.ecore.EAttributeAspect with fr.irisa.triskell.kermeta.language.structureScalaAspect.aspect.DefaultObjectImplementation
 class RichEAnnotation extends org.eclipse.emf.ecore.impl.EAnnotationImpl with ScalaAspect.org.eclipse.emf.ecore.EAnnotationAspect with fr.irisa.triskell.kermeta.language.structureScalaAspect.aspect.DefaultObjectImplementation
 class RichEClass extends org.eclipse.emf.ecore.impl.EClassImpl with ScalaAspect.org.eclipse.emf.ecore.EClassAspect with fr.irisa.triskell.kermeta.language.structureScalaAspect.aspect.DefaultObjectImplementation
 abstract class RichEClassifier extends org.eclipse.emf.ecore.impl.EClassifierImpl with ScalaAspect.org.eclipse.emf.ecore.EClassifierAspect with fr.irisa.triskell.kermeta.language.structureScalaAspect.aspect.DefaultObjectImplementation
 class RichEDataType extends org.eclipse.emf.ecore.impl.EDataTypeImpl with ScalaAspect.org.eclipse.emf.ecore.EDataTypeAspect with fr.irisa.triskell.kermeta.language.structureScalaAspect.aspect.DefaultObjectImplementation
 class RichEEnum extends org.eclipse.emf.ecore.impl.EEnumImpl with ScalaAspect.org.eclipse.emf.ecore.EEnumAspect with fr.irisa.triskell.kermeta.language.structureScalaAspect.aspect.DefaultObjectImplementation
 class RichEEnumLiteral extends org.eclipse.emf.ecore.impl.EEnumLiteralImpl with ScalaAspect.org.eclipse.emf.ecore.EEnumLiteralAspect with fr.irisa.triskell.kermeta.language.structureScalaAspect.aspect.DefaultObjectImplementation
 class RichEFactory extends org.eclipse.emf.ecore.impl.EFactoryImpl with ScalaAspect.org.eclipse.emf.ecore.EFactoryAspect with fr.irisa.triskell.kermeta.language.structureScalaAspect.aspect.DefaultObjectImplementation
 abstract class RichEModelElement extends org.eclipse.emf.ecore.impl.EModelElementImpl with ScalaAspect.org.eclipse.emf.ecore.EModelElementAspect with fr.irisa.triskell.kermeta.language.structureScalaAspect.aspect.DefaultObjectImplementation
 abstract class RichENamedElement extends org.eclipse.emf.ecore.impl.ENamedElementImpl with ScalaAspect.org.eclipse.emf.ecore.ENamedElementAspect with fr.irisa.triskell.kermeta.language.structureScalaAspect.aspect.DefaultObjectImplementation
 class RichEObject extends org.eclipse.emf.ecore.impl.EObjectImpl with ScalaAspect.org.eclipse.emf.ecore.EObjectAspect with fr.irisa.triskell.kermeta.language.structureScalaAspect.aspect.DefaultObjectImplementation
 class RichEOperation extends org.eclipse.emf.ecore.impl.EOperationImpl with ScalaAspect.org.eclipse.emf.ecore.EOperationAspect with fr.irisa.triskell.kermeta.language.structureScalaAspect.aspect.DefaultObjectImplementation
 class RichEPackage extends org.eclipse.emf.ecore.impl.EPackageImpl with ScalaAspect.org.eclipse.emf.ecore.EPackageAspect with fr.irisa.triskell.kermeta.language.structureScalaAspect.aspect.DefaultObjectImplementation
 class RichEParameter extends org.eclipse.emf.ecore.impl.EParameterImpl with ScalaAspect.org.eclipse.emf.ecore.EParameterAspect with fr.irisa.triskell.kermeta.language.structureScalaAspect.aspect.DefaultObjectImplementation
 class RichEReference extends org.eclipse.emf.ecore.impl.EReferenceImpl with ScalaAspect.org.eclipse.emf.ecore.EReferenceAspect with fr.irisa.triskell.kermeta.language.structureScalaAspect.aspect.DefaultObjectImplementation
 abstract class RichEStructuralFeature extends org.eclipse.emf.ecore.impl.EStructuralFeatureImpl with ScalaAspect.org.eclipse.emf.ecore.EStructuralFeatureAspect with fr.irisa.triskell.kermeta.language.structureScalaAspect.aspect.DefaultObjectImplementation
 abstract class RichETypedElement extends org.eclipse.emf.ecore.impl.ETypedElementImpl with ScalaAspect.org.eclipse.emf.ecore.ETypedElementAspect with fr.irisa.triskell.kermeta.language.structureScalaAspect.aspect.DefaultObjectImplementation
 class RichEStringToStringMapEntry extends org.eclipse.emf.ecore.impl.EStringToStringMapEntryImpl with ScalaAspect.org.eclipse.emf.ecore.EStringToStringMapEntryAspect with fr.irisa.triskell.kermeta.language.structureScalaAspect.aspect.DefaultObjectImplementation
 class RichEGenericType extends org.eclipse.emf.ecore.impl.EGenericTypeImpl with ScalaAspect.org.eclipse.emf.ecore.EGenericTypeAspect with fr.irisa.triskell.kermeta.language.structureScalaAspect.aspect.DefaultObjectImplementation
 class RichETypeParameter extends org.eclipse.emf.ecore.impl.ETypeParameterImpl with ScalaAspect.org.eclipse.emf.ecore.ETypeParameterAspect with fr.irisa.triskell.kermeta.language.structureScalaAspect.aspect.DefaultObjectImplementation

