<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="framework"
    nsURI="http://org.osgi.framework/" nsPrefix="org.osgi.framework">
  <eClassifiers xsi:type="ecore:EClass" name="Framework">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bundles" upperBound="-1"
        eType="#//Bundle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bundle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragments" upperBound="-1"
        eType="#//Bundle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" lowerBound="1"
        eType="#//String" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manifest" lowerBound="1"
        eType="ecore:EClass manifest.ecore#//MANIFEST" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fragmentsReference" upperBound="-1"
        eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="#//long"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="folder" eType="ecore:EClass jar.ecore#//Folder"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" eType="ecore:EClass jar.ecore#//Package"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="long" instanceClassName="long"/>
</ecore:EPackage>
