/*
 * ConsolePanel.java
 *
 * Created on 2 décembre 2005, 16:10
 */

package fr.irisa.triskell.kermeta.standalone.console;

/**
 *
 * @author  franck
 */
public class ConsolePanel extends javax.swing.JPanel {
    
    protected KermetaConsole console;
    
    /** Creates new form ConsolePanel */
    public ConsolePanel() {
        console = new KermetaConsole();
        initComponents();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = console.getPanel();
        jPanel2 = console.getVarsPanel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(500);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(700, 300));
        jSplitPane1.setLeftComponent(jPanel1);

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
    
}
