<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EAnnotation source="ModellingUnit">
    <details key="require" value="http://www.eclipse.org/emf/2002/Ecore|"/>
  </ecore:EAnnotation>
  <ecore:EPackage name="src" nsURI="pathmap:/src platform:/resource/TestKermeta/src/MetaModel.ecore" nsPrefix="src">
    <eClassifiers xsi:type="ecore:EClass" name="ModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="/1/kermeta%3A%3Astandard%3A%3AString">
        <eAnnotations source="kermeta">
          <details key="isComposite" value="true"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="/1/ModelElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" eType="/1/Event"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="/1/StateVertex" eOpposite="/1/StateVertex/outgoing"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="/1/StateVertex" eOpposite="/1/StateVertex/incoming"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StateMachine" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="top" eType="/1/State" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StateVertex" eSuperTypes="/1/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="/1/CompositeState" eOpposite="/1/CompositeState/subvertex"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" ordered="false" upperBound="-1" eType="/1/Transition" eOpposite="/1/Transition/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" ordered="false" upperBound="-1" eType="/1/Transition" eOpposite="/1/Transition/target"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="/1/StateVertex"/>
    <eClassifiers xsi:type="ecore:EClass" name="PseudoState" eSuperTypes="/1/StateVertex">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="/1/kermeta%3A%3Astandard%3A%3AString">
        <eAnnotations source="kermeta">
          <details key="isComposite" value="true"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompositeState" eSuperTypes="/1/State">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subvertex" ordered="false" upperBound="-1" eType="/1/StateVertex" containment="true" eOpposite="/1/StateVertex/container"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleState" eSuperTypes="/1/State"/>
    <eClassifiers xsi:type="ecore:EClass" name="FinalState" eSuperTypes="/1/State"/>
    <eClassifiers xsi:type="ecore:EDataType" name="kermeta::standard::String" instanceClassName="java.lang.Object">
      <eAnnotations source="kermeta">
        <details key="alias" value="kermeta::standard::String"/>
      </eAnnotations>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EAnnotation source="dependentResource"/>
</xmi:XMI>
