/**
 * Copyright: IRISA/INRIA/Universite de Rennes 1 - License: EPL - Web site: http://www.kermeta.org
 *
 * $Id: EMFRepositoryValidator.java,v 1.1 2008-06-24 14:23:35 cfaucher Exp $
 */
package kermeta.persistence.validation;


/**
 * A sample validator interface for {@link kermeta.persistence.EMFRepository}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EMFRepositoryValidator
{
  boolean validate();

  boolean validateUseInterpreterInternalResources(boolean value);
  boolean validateIgnoreLoadErrors(boolean value);
}
