/**
 * Copyright: IRISA/INRIA/Universite de Rennes 1 - License: EPL - Web site: http://www.kermeta.org
 *
 * $Id: CallFeatureValidator.java,v 1.1 2008-06-24 14:23:13 cfaucher Exp $
 */
package kermeta.language.behavior.validation;

import kermeta.language.behavior.Expression;

import kermeta.language.structure.EnumerationLiteral;
import kermeta.language.structure.Operation;
import kermeta.language.structure.Property;

/**
 * A sample validator interface for {@link kermeta.language.behavior.CallFeature}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CallFeatureValidator
{
  boolean validate();

  boolean validateIsAtpre(boolean value);
  boolean validateStaticOperation(Operation value);
  boolean validateTarget(Expression value);
  boolean validateStaticEnumLiteral(EnumerationLiteral value);
  boolean validateStaticProperty(Property value);
}
