/**
 * Copyright: IRISA/INRIA/Universite de Rennes 1 - License: EPL - Web site: http://www.kermeta.org
 *
 * $Id: CallExpressionValidator.java,v 1.1 2008-06-24 14:23:14 cfaucher Exp $
 */
package kermeta.language.behavior.validation;

import kermeta.language.behavior.Expression;

import kermeta.language.structure.Type;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link kermeta.language.behavior.CallExpression}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CallExpressionValidator
{
  boolean validate();

  boolean validateStaticTypeVariableBindings(EList<Type> value);
  boolean validateName(String value);
  boolean validateParameters(EList<Expression> value);
}
