/**
 * Copyright: IRISA/INRIA/Universite de Rennes 1 - License: EPL - Web site: http://www.kermeta.org
 *
 * $Id: FSMValidator.java,v 1.1 2008-07-02 09:13:34 ftanguy Exp $
 */
package fsm.validation;

import fsm.State;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link fsm.FSM}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FSMValidator
{
  boolean validate();

  boolean validateOwnedState(EList<State> value);
  boolean validateCurrentState(State value);
  boolean validateInitialState(State value);
  boolean validateFinalState(EList<State> value);
}
