/**
 * Copyright: IRISA/INRIA/Universite de Rennes 1 - License: EPL - Web site: http://www.kermeta.org
 *
 * $Id: TransitionValidator.java,v 1.1 2008-07-02 09:13:34 ftanguy Exp $
 */
package fsm.validation;

import fsm.State;

/**
 * A sample validator interface for {@link fsm.Transition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransitionValidator
{
  boolean validate();

  boolean validateInput(String value);
  boolean validateSource(State value);
  boolean validateTarget(State value);
  boolean validateOutput(String value);
}
