/* $Id: Comp_assignment_test003__Main__main_Runner.java,v 1.2 2009-02-17 13:41:06 cfaucher Exp $
 * This file has been generated by the compiler of Kermeta (http://www.kermeta.org)
 */

package comp_assignment_test003.runner;

import comp_assignment_test003.Comp_assignment_test003Factory;

/**
 * A Stub of a Java Application Runner for a Kermeta runnable method
 *
 * @generated
 */
public class Comp_assignment_test003__Main__main_Runner {

	public static void main(String[] args) {
		Comp_assignment_test003Factory.eINSTANCE.createMain().main();
	}

}
