/**
 * <copyright>
 * </copyright>
 *
 * $Id: KTagElementValidator.java,v 1.1 2007-10-15 16:54:08 fmunoz Exp $
 */
package org.kermeta.trek.validation;


/**
 * A sample validator interface for {@link org.kermeta.trek.KTagElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface KTagElementValidator {
	boolean validate();

	boolean validateConcept(String value);
	boolean validateName(String value);
}
