/**
 * <copyright>
 * </copyright>
 *
 * $Id: KUseCaseValidator.java,v 1.1 2007-10-15 16:54:08 fmunoz Exp $
 */
package org.kermeta.trek.validation;

import org.eclipse.emf.common.util.EList;

import org.kermeta.trek.KTagElement;
import org.kermeta.trek.KTestCase;
import org.kermeta.trek.KUseCase;
import org.kermeta.trek.KUseLevel;
import org.kermeta.trek.KUserStory;

/**
 * A sample validator interface for {@link org.kermeta.trek.KUseCase}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface KUseCaseValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateId(String value);
	boolean validateSummary(String value);
	boolean validateShortSummary(String value);
	boolean validateUse(EList<KUseCase> value);
	boolean validateUsedBy(EList<KUseCase> value);
	boolean validateVerifiedBy(EList<KTestCase> value);
	boolean validateRefines(KUseCase value);
	boolean validateRefinedBy(EList<KUseCase> value);
	boolean validateCovers(EList<KUserStory> value);
	boolean validateLevel(KUseLevel value);
	boolean validateTags(EList<KTagElement> value);
}
