/**
 * <copyright>
 * </copyright>
 *
 * $Id: UseKaseModelValidator.java,v 1.1 2007-10-15 16:54:08 fmunoz Exp $
 */
package org.kermeta.trek.validation;

import org.eclipse.emf.common.util.EList;

import org.kermeta.trek.KTestCase;
import org.kermeta.trek.KUseCase;
import org.kermeta.trek.KUserStory;

/**
 * A sample validator interface for {@link org.kermeta.trek.UseKaseModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UseKaseModelValidator {
	boolean validate();

	boolean validateKuseCases(EList<KUseCase> value);
	boolean validateKtestCases(EList<KTestCase> value);
	boolean validateKtags(EList<KTestCase> value);
	boolean validateKuserStories(EList<KUserStory> value);
}
