<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="compiler"
    nsURI="http://www.kermeta.org/compiler" nsPrefix="compiler">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractCompiler" abstract="true">
    <eOperations name="run"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simkModel" eType="ecore:EClass ../../../org.kermeta.simk/model/ecore/simk.ecore#//SIMKModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genModels" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootGenModel" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KermetaCompiler" eSuperTypes="#//AbstractCompiler"/>
  <eClassifiers xsi:type="ecore:EClass" name="EcoreCompiler" eSuperTypes="#//AbstractCompiler"/>
</ecore:EPackage>
