<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="org"
    nsURI="http://www.kermeta.org/alf/1_0_0/" nsPrefix="org">
  <eSubpackages name="kermeta" nsURI="http://www.kermeta.org/alf/1_0_0/org/kermeta/"
      nsPrefix="org_kermeta">
    <eSubpackages name="alf" nsURI="http://www.kermeta.org/alf/1_0_0/org/kermeta/alf"
        nsPrefix="org_kermeta_alf">
      <eClassifiers xsi:type="ecore:EEnum" name="AssignmentOperator">
        <eLiterals name="ASSIGN" literal="="/>
        <eLiterals name="PLUSASSIGN" value="1" literal="+="/>
        <eLiterals name="MINUSASSIGN" value="2" literal="-="/>
        <eLiterals name="MULTASSIGN" value="3" literal="*="/>
        <eLiterals name="MODASSIGN" value="4" literal="%="/>
        <eLiterals name="DIVASSIGN" value="5" literal="/="/>
        <eLiterals name="ANDASSIGN" value="6" literal="&amp;="/>
        <eLiterals name="ORASSIGN" value="7" literal="|="/>
        <eLiterals name="XORASSIGN" value="8" literal="^="/>
        <eLiterals name="LSHIFTASSIGN" value="9" literal="&lt;&lt;="/>
        <eLiterals name="RSHIFTASSIGN" value="10" literal=">>="/>
        <eLiterals name="URSHIFTASSIGN" value="11" literal=">>>="/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CLASSSTRUCT">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="clsop" upperBound="-1"
            eType="#//kermeta/alf/CLASSOP" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CLASSOP">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="stat" upperBound="-1"
            eType="#//kermeta/alf/Statement" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LITERAL" eSuperTypes="#//kermeta/alf/ValueSpecification">
        <eStructuralFeatures xsi:type="ecore:EReference" name="suffix" eType="#//kermeta/alf/SuffixExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BOOLEAN_LITERAL" eSuperTypes="#//kermeta/alf/LITERAL">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//kermeta/alf/BooleanValue"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="BooleanValue">
        <eLiterals name="TRUE" literal="true"/>
        <eLiterals name="FALSE" value="1" literal="false"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="NUMBER_LITERAL" eSuperTypes="#//kermeta/alf/LITERAL">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="INTEGER_LITERAL" eSuperTypes="#//kermeta/alf/NUMBER_LITERAL"/>
      <eClassifiers xsi:type="ecore:EClass" name="UNLIMITED_LITERAL" eSuperTypes="#//kermeta/alf/NUMBER_LITERAL"/>
      <eClassifiers xsi:type="ecore:EClass" name="STRING_LITERAL" eSuperTypes="#//kermeta/alf/LITERAL">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="NameExpression" eSuperTypes="#//kermeta/alf/ValueSpecification #//kermeta/alf/NonLiteralValueSpecification">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefixOp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="#//kermeta/alf/QualifiedNamePath"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="invocationCompletion"
            eType="#//kermeta/alf/Tuple" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="sequenceConstructionCompletion"
            eType="#//kermeta/alf/SequenceConstructionOrAccessCompletion" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="postfixOp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="suffix" eType="#//kermeta/alf/SuffixExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="QualifiedNamePath">
        <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" upperBound="-1"
            eType="#//kermeta/alf/UnqualifiedName" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UnqualifiedName">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="templateBinding" eType="#//kermeta/alf/TemplateBinding"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TemplateBinding">
        <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
            eType="#//kermeta/alf/NamedTemplateBinding" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="NamedTemplateBinding">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="formal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="actual" eType="#//kermeta/alf/QualifiedNameWithBinding"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="QualifiedNameWithBinding">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="binding" eType="#//kermeta/alf/TemplateBinding"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="remaining" eType="#//kermeta/alf/QualifiedNameWithBinding"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Tuple">
        <eStructuralFeatures xsi:type="ecore:EReference" name="tupleElements" upperBound="-1"
            eType="#//kermeta/alf/TupleElement" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TupleElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="argument" eType="#//kermeta/alf/Expression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//kermeta/alf/SequenceElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="ConditionalTestExpression" eSuperTypes="#//kermeta/alf/Expression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="exp" eType="#//kermeta/alf/ConditionalOrExpression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="whenTrue" eType="#//kermeta/alf/ConditionalTestExpression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="whenFalse" eType="#//kermeta/alf/ConditionalTestExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ConditionalOrExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="exp" upperBound="-1"
            eType="#//kermeta/alf/ConditionalAndExpression" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ConditionalAndExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="exp" upperBound="-1"
            eType="#//kermeta/alf/InclusiveOrExpression" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InclusiveOrExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="exp" upperBound="-1"
            eType="#//kermeta/alf/ExclusiveOrExpression" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ExclusiveOrExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="exp" upperBound="-1"
            eType="#//kermeta/alf/AndExpression" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AndExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="exp" upperBound="-1"
            eType="#//kermeta/alf/EqualityExpression" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="EqualityExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="exp" upperBound="-1"
            eType="#//kermeta/alf/ClassificationExpression" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" unique="false"
            upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ClassificationExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="exp" eType="#//kermeta/alf/RelationalExpression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeName" eType="#//kermeta/alf/NameExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RelationalExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//kermeta/alf/ShiftExpression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//kermeta/alf/ShiftExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ShiftExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="exp" upperBound="-1"
            eType="#//kermeta/alf/AdditiveExpression" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AdditiveExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="exp" upperBound="-1"
            eType="#//kermeta/alf/MultiplicativeExpression" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" unique="false"
            upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="MultiplicativeExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="exp" upperBound="-1"
            eType="#//kermeta/alf/UnaryExpression" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" unique="false"
            upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="exp" eType="#//kermeta/alf/PrimaryExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PrimaryExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="prefix" eType="#//kermeta/alf/ValueSpecification"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SuffixExpression"/>
      <eClassifiers xsi:type="ecore:EClass" name="OperationCallExpression" eSuperTypes="#//kermeta/alf/SuffixExpression">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="tuple" eType="#//kermeta/alf/Tuple"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="suffix" eType="#//kermeta/alf/SuffixExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="OperationCallExpressionWithoutDot">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="tuple" eType="#//kermeta/alf/Tuple"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="suffix" eType="#//kermeta/alf/SuffixExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PropertyCallExpression" eSuperTypes="#//kermeta/alf/SuffixExpression">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="#//kermeta/alf/Expression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="suffix" eType="#//kermeta/alf/SuffixExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LinkOperationExpression" eSuperTypes="#//kermeta/alf/SuffixExpression">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//kermeta/alf/LinkOperationKind"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="tuple" eType="#//kermeta/alf/LinkOperationTuple"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LinkOperationTuple">
        <eStructuralFeatures xsi:type="ecore:EReference" name="linkOperationTupleElement"
            upperBound="-1" eType="#//kermeta/alf/LinkOperationTupleElement" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LinkOperationTupleElement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectOrRole" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="roleIndex" eType="#//kermeta/alf/Expression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="object" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="LinkOperationKind">
        <eLiterals name="CREATE" literal="createLink"/>
        <eLiterals name="DESTROY" value="1" literal="destroyLink"/>
        <eLiterals name="CLEAR" value="2" literal="clearAssoc"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SequenceOperationExpression" eSuperTypes="#//kermeta/alf/SuffixExpression">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="tuple" eType="#//kermeta/alf/Tuple"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="suffix" eType="#//kermeta/alf/SuffixExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SequenceReductionExpression" eSuperTypes="#//kermeta/alf/SuffixExpression">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOrdered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" eType="#//kermeta/alf/QualifiedNameWithBinding"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="suffix" eType="#//kermeta/alf/SuffixExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SequenceExpansionExpression" eSuperTypes="#//kermeta/alf/SuffixExpression">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//kermeta/alf/Expression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="suffix" eType="#//kermeta/alf/SuffixExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SelectOrRejectOperation" eSuperTypes="#//kermeta/alf/SequenceExpansionExpression">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="#//kermeta/alf/SelectOrRejectOperator"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="SelectOrRejectOperator">
        <eLiterals name="SELECT" literal="select"/>
        <eLiterals name="REJECT" value="1" literal="reject"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CollectOrIterateOperation" eSuperTypes="#//kermeta/alf/SequenceExpansionExpression">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="#//kermeta/alf/CollectOrIterateOperator"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="CollectOrIterateOperator">
        <eLiterals name="COLLECT" literal="collect"/>
        <eLiterals name="ITERATE" value="1" literal="iterate"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ForAllOrExistsOrOneOperation" eSuperTypes="#//kermeta/alf/SequenceExpansionExpression">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="#//kermeta/alf/ForAllOrExistsOrOneOperator"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="ForAllOrExistsOrOneOperator">
        <eLiterals name="FORALL" literal="forAll"/>
        <eLiterals name="EXISTS" value="1" literal="exists"/>
        <eLiterals name="ONE" value="2" literal="one"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="IsUniqueOperation" eSuperTypes="#//kermeta/alf/SequenceExpansionExpression"/>
      <eClassifiers xsi:type="ecore:EClass" name="ValueSpecification"/>
      <eClassifiers xsi:type="ecore:EClass" name="NonLiteralValueSpecification"/>
      <eClassifiers xsi:type="ecore:EClass" name="ParenthesizedExpression" eSuperTypes="#//kermeta/alf/ValueSpecification #//kermeta/alf/NonLiteralValueSpecification">
        <eStructuralFeatures xsi:type="ecore:EReference" name="expOrTypeCast" eType="#//kermeta/alf/Expression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="casted" eType="#//kermeta/alf/NonLiteralValueSpecification"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="suffix" eType="#//kermeta/alf/SuffixExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="NullExpression" eSuperTypes="#//kermeta/alf/ValueSpecification"/>
      <eClassifiers xsi:type="ecore:EClass" name="ThisExpression" eSuperTypes="#//kermeta/alf/ValueSpecification #//kermeta/alf/NonLiteralValueSpecification">
        <eStructuralFeatures xsi:type="ecore:EReference" name="suffix" eType="#//kermeta/alf/SuffixExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SuperInvocationExpression" eSuperTypes="#//kermeta/alf/ValueSpecification #//kermeta/alf/NonLiteralValueSpecification">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="operationCallWithoutDot"
            eType="#//kermeta/alf/OperationCallExpressionWithoutDot" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="operationCall" eType="#//kermeta/alf/OperationCallExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InstanceCreationExpression" eSuperTypes="#//kermeta/alf/ValueSpecification #//kermeta/alf/NonLiteralValueSpecification">
        <eStructuralFeatures xsi:type="ecore:EReference" name="constructor" eType="#//kermeta/alf/QualifiedNameWithBinding"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="tuple" eType="#//kermeta/alf/Tuple"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="sequenceConstuctionCompletion"
            eType="#//kermeta/alf/SequenceConstructionCompletion" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="suffix" eType="#//kermeta/alf/SuffixExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SequenceConstructionOrAccessCompletion">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicityIndicator"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="accessCompletion" eType="#//kermeta/alf/AccessCompletion"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="sequenceCompletion"
            eType="#//kermeta/alf/PartialSequenceConstructionCompletion" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//kermeta/alf/SequenceConstructionExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AccessCompletion">
        <eStructuralFeatures xsi:type="ecore:EReference" name="accessIndex" eType="#//kermeta/alf/Expression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PartialSequenceConstructionCompletion">
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//kermeta/alf/SequenceConstructionExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SequenceConstructionCompletion">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicityIndicator"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//kermeta/alf/SequenceConstructionExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SequenceConstructionExpression"
          eSuperTypes="#//kermeta/alf/SequenceElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="sequenceElement" upperBound="-1"
            eType="#//kermeta/alf/SequenceElement" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="rangeUpper" eType="#//kermeta/alf/Expression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SequenceElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="ClassExtentExpression" eSuperTypes="#//kermeta/alf/SuffixExpression"/>
      <eClassifiers xsi:type="ecore:EClass" name="Block">
        <eStructuralFeatures xsi:type="ecore:EReference" name="sequence" eType="#//kermeta/alf/StatementSequence"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StatementSequence">
        <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
            eType="#//kermeta/alf/DocumentedStatement" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InlineStatement" eSuperTypes="#//kermeta/alf/Statement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="langageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AnnotatedStatement" eSuperTypes="#//kermeta/alf/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" eType="#//kermeta/alf/Annotation"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//kermeta/alf/Block"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DocumentedStatement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//kermeta/alf/Statement"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Statement"/>
      <eClassifiers xsi:type="ecore:EClass" name="Annotation">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//kermeta/alf/AnnotationKind"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="args" unique="false"
            upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="AnnotationKind">
        <eLiterals name="ISOLATED" literal="isolated"/>
        <eLiterals name="DETERMINED" value="1" literal="determined"/>
        <eLiterals name="ASSURED" value="2" literal="assured"/>
        <eLiterals name="PARALLEL" value="3" literal="parallel"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BlockStatement" eSuperTypes="#//kermeta/alf/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//kermeta/alf/Block"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="EmptyStatement" eSuperTypes="#//kermeta/alf/Statement"/>
      <eClassifiers xsi:type="ecore:EClass" name="LocalNameDeclarationStatement" eSuperTypes="#//kermeta/alf/Statement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="varName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//kermeta/alf/QualifiedNameWithBinding"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicityIndicator"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="init" eType="#//kermeta/alf/Expression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="#//kermeta/alf/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="sequentialClausses"
            eType="#//kermeta/alf/SequentialClauses" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="finalClause" eType="#//kermeta/alf/FinalClause"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SequentialClauses">
        <eStructuralFeatures xsi:type="ecore:EReference" name="conccurentClauses"
            upperBound="-1" eType="#//kermeta/alf/ConcurrentClauses" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ConcurrentClauses">
        <eStructuralFeatures xsi:type="ecore:EReference" name="nonFinalClause" upperBound="-1"
            eType="#//kermeta/alf/NonFinalClause" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="NonFinalClause">
        <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//kermeta/alf/Expression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//kermeta/alf/Block"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FinalClause">
        <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//kermeta/alf/Block"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SwitchStatement" eSuperTypes="#//kermeta/alf/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//kermeta/alf/Expression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="switchClause" upperBound="-1"
            eType="#//kermeta/alf/SwitchClause" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="defaultClause" eType="#//kermeta/alf/SwitchDefaultClause"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SwitchClause">
        <eStructuralFeatures xsi:type="ecore:EReference" name="switchCase" upperBound="-1"
            eType="#//kermeta/alf/SwitchCase" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="statementSequence"
            eType="#//kermeta/alf/NonEmptyStatementSequence" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SwitchCase">
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//kermeta/alf/Expression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SwitchDefaultClause">
        <eStructuralFeatures xsi:type="ecore:EReference" name="statementSequence"
            eType="#//kermeta/alf/NonEmptyStatementSequence" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="NonEmptyStatementSequence">
        <eStructuralFeatures xsi:type="ecore:EReference" name="statement" upperBound="-1"
            eType="#//kermeta/alf/DocumentedStatement" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="WhileStatement" eSuperTypes="#//kermeta/alf/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//kermeta/alf/Expression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//kermeta/alf/Block"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DoStatement" eSuperTypes="#//kermeta/alf/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//kermeta/alf/Block"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//kermeta/alf/Expression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ForStatement" eSuperTypes="#//kermeta/alf/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="control" eType="#//kermeta/alf/ForControl"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//kermeta/alf/Block"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ForControl">
        <eStructuralFeatures xsi:type="ecore:EReference" name="loopVariableDefinition"
            upperBound="-1" eType="#//kermeta/alf/LoopVariableDefinition" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LoopVariableDefinition">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression1" eType="#//kermeta/alf/Expression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression2" eType="#//kermeta/alf/Expression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//kermeta/alf/QualifiedNameWithBinding"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//kermeta/alf/Expression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BreakStatement" eSuperTypes="#//kermeta/alf/Statement"/>
      <eClassifiers xsi:type="ecore:EClass" name="ReturnStatement" eSuperTypes="#//kermeta/alf/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//kermeta/alf/Expression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AcceptStatement" eSuperTypes="#//kermeta/alf/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="clause" eType="#//kermeta/alf/AcceptClause"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="simpleAccept" eType="#//kermeta/alf/SimpleAcceptStatementCompletion"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="compoundAccept" eType="#//kermeta/alf/CompoundAcceptStatementCompletion"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SimpleAcceptStatementCompletion"/>
      <eClassifiers xsi:type="ecore:EClass" name="CompoundAcceptStatementCompletion">
        <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//kermeta/alf/Block"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="acceptBlock" upperBound="-1"
            eType="#//kermeta/alf/AcceptBlock" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AcceptBlock">
        <eStructuralFeatures xsi:type="ecore:EReference" name="clause" eType="#//kermeta/alf/AcceptClause"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//kermeta/alf/Block"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AcceptClause">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="qualifiedNameList"
            eType="#//kermeta/alf/QualifiedNameList" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ClassifyStatement" eSuperTypes="#//kermeta/alf/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//kermeta/alf/Expression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="clause" eType="#//kermeta/alf/ClassificationClause"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ClassificationClause">
        <eStructuralFeatures xsi:type="ecore:EReference" name="classifyFromClause"
            eType="#//kermeta/alf/ClassificationFromClause" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="classifyToClause" eType="#//kermeta/alf/ClassificationToClause"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="reclassyAllClause"
            eType="#//kermeta/alf/ReclassifyAllClause" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ClassificationFromClause">
        <eStructuralFeatures xsi:type="ecore:EReference" name="qualifiedNameList"
            eType="#//kermeta/alf/QualifiedNameList" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ClassificationToClause">
        <eStructuralFeatures xsi:type="ecore:EReference" name="qualifiedNameList"
            eType="#//kermeta/alf/QualifiedNameList" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ReclassifyAllClause"/>
      <eClassifiers xsi:type="ecore:EClass" name="QualifiedNameList">
        <eStructuralFeatures xsi:type="ecore:EReference" name="qualifiedName" upperBound="-1"
            eType="#//kermeta/alf/QualifiedNameWithBinding" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InvocationOrAssignementOrDeclarationStatement"
          eSuperTypes="#//kermeta/alf/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="typePart_OR_assignedPart_OR_invocationPart"
            eType="#//kermeta/alf/NameExpression" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="variableDeclarationCompletion"
            eType="#//kermeta/alf/VariableDeclarationCompletion" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="assignmentCompletion"
            eType="#//kermeta/alf/AssignmentCompletion" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SuperInvocationStatement" eSuperTypes="#//kermeta/alf/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="_super" eType="#//kermeta/alf/SuperInvocationExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ThisInvocationStatement" eSuperTypes="#//kermeta/alf/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="_this" eType="#//kermeta/alf/ThisExpression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="assignmentCompletion"
            eType="#//kermeta/alf/AssignmentCompletion" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InstanceCreationInvocationStatement"
          eSuperTypes="#//kermeta/alf/Statement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="_new" eType="#//kermeta/alf/InstanceCreationExpression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="VariableDeclarationCompletion">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicityIndicator"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="initValue" eType="#//kermeta/alf/AssignmentCompletion"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AssignmentCompletion">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="#//kermeta/alf/AssignmentOperator"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="rightHandSide" eType="#//kermeta/alf/Expression"
            containment="true"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
