<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="statemachine"
    nsURI="http://statemachine/1.0" nsPrefix="statemachine">
  <eSubpackages name="sm">
    <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
      <eOperations name="run"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
          eType="#//sm/State" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
          eType="#//sm/Transition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="currentState" eType="#//sm/State"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="State">
      <eStructuralFeatures xsi:type="ecore:EReference" name="out" upperBound="-1"
          eType="#//sm/Transition" eOpposite="#//sm/Transition/src"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Transition">
      <eOperations name="fire"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//sm/State"
          eOpposite="#//sm/State/out"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tar" lowerBound="1" eType="#//sm/State"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
