/**
 * <copyright>
 * </copyright>
 *
 * $Id: RuleValidator.java,v 1.2 2008-05-28 09:26:13 ftanguy Exp $
 */
package fr.irisa.triskell.kermeta.kpm.validation;

import org.eclipse.emf.common.util.EList;

import fr.irisa.triskell.kermeta.kpm.Event;
import fr.irisa.triskell.kermeta.kpm.Expression;
import fr.irisa.triskell.kermeta.kpm.Out;

/**
 * A sample validator interface for {@link fr.irisa.triskell.kermeta.kpm.Rule}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RuleValidator {
	boolean validate();

	boolean validateEvent(Event value);
	boolean validateOuts(EList value);
	boolean validateName(String value);

	boolean validatePrecondition(Expression value);

	boolean validatePreconditions(Expression value);
}
