/**
 * <copyright>
 * </copyright>
 *
 * $Id: UnitValidator.java,v 1.2 2008-05-28 09:26:13 ftanguy Exp $
 */
package fr.irisa.triskell.kermeta.kpm.validation;

import fr.irisa.triskell.kermeta.kpm.Dependency;
import fr.irisa.triskell.kermeta.kpm.Rule;
import fr.irisa.triskell.kermeta.kpm.Type;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link fr.irisa.triskell.kermeta.kpm.Unit}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UnitValidator {
	boolean validate();

	boolean validateType(Type value);
	boolean validateRules(EList value);
	boolean validateName(String value);
	boolean validateLastTimeModified(Date value);
	boolean validateValue(String value);
	boolean validateMasters(EList<Dependency> value);

	boolean validateDependencies(EList value);
	boolean validateDependents(EList value);
}
