/**
 * <copyright>
 * </copyright>
 *
 * $Id: FileDependencyTreeItemValidator.java,v 1.1 2007-08-08 12:58:39 dvojtise Exp $
 */
package fr.irisa.triskell.kermeta.ui.validation;


/**
 * A sample validator interface for {@link fr.irisa.triskell.kermeta.ui.FileDependencyTreeItem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FileDependencyTreeItemValidator {
	boolean validate();

}
