/**
 * <copyright>
 * </copyright>
 *
 * $Id: TreeItemValidator.java,v 1.1 2007-08-08 12:58:39 dvojtise Exp $
 */
package fr.irisa.triskell.kermeta.ui.validation;

import fr.irisa.triskell.kermeta.ui.TreeItem;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link fr.irisa.triskell.kermeta.ui.TreeItem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TreeItemValidator {
	boolean validate();

	boolean validateChildren(EList<TreeItem> value);
	boolean validateParent(TreeItem value);
	boolean validateValue(Object value);
}
