<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simulator">
  <eClassifiers xsi:type="ecore:EClass" name="Simulator">
    <eOperations name="displayFireableTransitions"/>
    <eOperations name="readChoicedTransition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="setInitialConfiguration">
      <eParameters name="initialSystem" eType="#//InitialConfiguration"/>
    </eOperations>
    <eOperations name="execTransition">
      <eParameters name="choicedTransition" eType="ecore:EDataType ../../src/ecore/rts.ecore#//Integer"/>
    </eOperations>
    <eOperations name="main"/>
    <eOperations name="displayCurrentState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentState" lowerBound="1"
        eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentFireableTransitions"
        lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" interface="true">
    <eOperations name="getFireableTransitions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialState" lowerBound="1"
        eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectsTable" lowerBound="1"
        upperBound="-1" eType="#//Instance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statesTable" lowerBound="1"
        upperBound="-1" eType="#//State"/>
  </eClassifiers>
</ecore:EPackage>
