<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="decomposition"
    nsURI="http://www.kermeta.org/decomposer" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="Decomposer">
    <eOperations name="dependsOn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="element" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="start"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="ecore:EClass ../../org.kermeta.kompose.model/model/kompose.ecore#//Mergeable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="ecore:EClass ../../org.kermeta.kompose.model/model/kompose.ecore#//Mergeable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="original" lowerBound="1"
        eType="ecore:EClass ../../org.kermeta.kompose.model/model/kompose.ecore#//Mergeable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processed" upperBound="-1"
        eType="ecore:EClass ../../org.kermeta.kompose.model/model/kompose.ecore#//Mergeable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toProcess" upperBound="-1"
        eType="ecore:EClass ../../org.kermeta.kompose.model/model/kompose.ecore#//Mergeable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dependants" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperationType">
    <eLiterals name="CLONE"/>
    <eLiterals name="ONESIDE" value="1"/>
    <eLiterals name="RENAME" value="2"/>
    <eLiterals name="RENAMEBEFORE" value="3" literal=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Named" eSuperTypes="../../org.kermeta.kompose.model/model/kompose.ecore#//Mergeable">
    <eOperations name="getName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="setName" lowerBound="1">
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule"/>
  <eClassifiers xsi:type="ecore:EClass" name="CProperty"/>
</ecore:EPackage>
