/* $Id: Comp_callResult_test001__Main__main_Runner.java,v 1.1 2007-11-19 09:44:44 cfaucher Exp $
 * This file has been generated by the compiler of Kermeta (http://www.kermeta.org)
 */

package comp_callResult_test001.runner;

import comp_callResult_test001.Comp_callResult_test001Factory;

/**
 * A Stub of a Java Application Runner for a Kermeta runnable method
 *
 * @generated
 */
public class Comp_callResult_test001__Main__main_Runner {

	public static void main(String[] args) {
		Comp_callResult_test001Factory.eINSTANCE.createMain().main();
	}

}
