<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="capturewitnessreport"
    nsURI="http://capturewitnessreport/1.0" nsPrefix="capturewitnessreport">
  <eSubpackages name="Cms">
    <eClassifiers xsi:type="ecore:EClass" name="BusinessProcesses">
      <eOperations name="captureWitnessReport" lowerBound="1">
        <eParameters name="in" eType="#//Cms/CaptureWitnessReportRequest"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Service">
      <eOperations name="assignEmergencyLvl">
        <eParameters name="" eType="#//Cms/AssignEmergencyLvlRequest"/>
      </eOperations>
      <eOperations name="buildCheckList" lowerBound="1" eType="#//Cms/BuildCheckListResponse">
        <eParameters name="in" eType="#//Cms/BuildCheckListRequest"/>
      </eOperations>
      <eOperations name="setWitness" lowerBound="1">
        <eParameters name="in" eType="#//Cms/SetWitnessRequest"/>
      </eOperations>
      <eOperations name="validateWitnessInfo" lowerBound="1" eType="#//Cms/ValidateWitnessInfoResponse">
        <eParameters name="in" eType="#//Cms/ValidateWitnessInfoRequest"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CaptureWitnessReportRequest">
      <eStructuralFeatures xsi:type="ecore:EReference" name="id" lowerBound="1" eType="#//Cms/CrisisIdentifier"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="coord" lowerBound="1"
          eType="#//Cms/CmsEmployee" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CrisisIdentifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="CmsEmployee"/>
    <eClassifiers xsi:type="ecore:EClass" name="Witness"/>
    <eClassifiers xsi:type="ecore:EClass" name="SetWitnessRequest">
      <eStructuralFeatures xsi:type="ecore:EReference" name="id" lowerBound="1" eType="#//Cms/CrisisIdentifier"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="wi" lowerBound="1" eType="#//Cms/Witness"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ValidateWitnessInfoRequest">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pi" lowerBound="1" eType="#//Cms/PhoneInformation"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="wi" lowerBound="1" eType="#//Cms/Witness"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ValidateWitnessInfoResponse">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="exact" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PhoneInformation"/>
    <eClassifiers xsi:type="ecore:EClass" name="PreliminaryInformation"/>
    <eClassifiers xsi:type="ecore:EClass" name="CrisisCheckList"/>
    <eClassifiers xsi:type="ecore:EClass" name="CrisisInformation"/>
    <eClassifiers xsi:type="ecore:EClass" name="BuildCheckListRequest">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ccl" lowerBound="1" eType="#//Cms/CrisisCheckList"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BuildCheckListResponse">
      <eStructuralFeatures xsi:type="ecore:EReference" name="i" lowerBound="1" eType="#//Cms/PreliminaryInformation"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssignEmergencyLvlRequest">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ci" lowerBound="1" eType="#//Cms/CrisisInformation"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="id" lowerBound="1" eType="#//Cms/CrisisIdentifier"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="UI">
    <eClassifiers xsi:type="ecore:EClass" name="Service">
      <eOperations name="promptCheckList"/>
      <eOperations name="promptPrelimInfo" lowerBound="1" eType="#//UI/PromptPrelimInfoResponse">
        <eParameters name="in" eType="#//UI/PromptPrelimInfoRequest"/>
      </eOperations>
      <eOperations name="promptWintessInfo" lowerBound="1" eType="#//UI/PromptWitnessInfoResponse">
        <eParameters name="in" eType="#//UI/PromptWitnessInfoRequest"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CmsEmployee"/>
    <eClassifiers xsi:type="ecore:EClass" name="Witness"/>
    <eClassifiers xsi:type="ecore:EClass" name="PromptWitnessInfoRequest">
      <eStructuralFeatures xsi:type="ecore:EReference" name="coord" lowerBound="1"
          eType="#//UI/CmsEmployee" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PromptWitnessInfoResponse">
      <eStructuralFeatures xsi:type="ecore:EReference" name="wi" lowerBound="1" eType="#//UI/Witness"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PromptPrelimInfoRequest">
      <eStructuralFeatures xsi:type="ecore:EReference" name="coord" lowerBound="1"
          eType="#//UI/CmsEmployee" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PromptPrelimInfoResponse">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pi" lowerBound="1" eType="#//UI/PreliminaryInformation"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PreliminaryInformation"/>
    <eClassifiers xsi:type="ecore:EClass" name="PromptCheckListRequest">
      <eStructuralFeatures xsi:type="ecore:EReference" name="coord" lowerBound="1"
          eType="#//UI/CmsEmployee" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="id" lowerBound="1" eType="#//UI/CrisisIdentifier"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ccl" lowerBound="1" eType="#//UI/CrisisCheckList"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PromptCheckListResponse">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ci" lowerBound="1" eType="#//UI/CrisisInformation"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CrisisIdentifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="CrisisCheckList"/>
    <eClassifiers xsi:type="ecore:EClass" name="CrisisInformation"/>
  </eSubpackages>
  <eSubpackages name="PhoneCie">
    <eClassifiers xsi:type="ecore:EClass" name="Service">
      <eOperations name="getInfo" lowerBound="1" eType="#//PhoneCie/GetInfoResponse">
        <eParameters name="" eType="#//PhoneCie/GetInfoRequest"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Witness">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PhoneInformation"/>
    <eClassifiers xsi:type="ecore:EClass" name="GetInfoRequest">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="witnessId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GetInfoResponse">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pi" lowerBound="1" eType="#//PhoneCie/PhoneInformation"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="MsgBus">
    <eClassifiers xsi:type="ecore:EClass" name="Service">
      <eOperations name="send">
        <eParameters name="in" eType="#//MsgBus/SendRequest"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CrisisIdentifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="SendRequest">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="anonymous_1" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="anonymous_2" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ci" lowerBound="1" eType="#//MsgBus/CrisisIdentifier"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
