<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hrc"
    nsURI="http:///hrc.ecore" nsPrefix="hrc">
  <eSubpackages name="level0" nsURI="http:///hrc/level0.ecore" nsPrefix="hrc.level0">
    <eSubpackages name="actionspecifications" nsURI="http:///hrc/level0/actionspecifications.ecore"
        nsPrefix="hrc.level0.actionspecifications">
      <eClassifiers xsi:type="ecore:EClass" name="ActionSpecification" abstract="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="CompositeAction" eSuperTypes="#//level0/actionspecifications/ActionSpecification">
        <eStructuralFeatures xsi:type="ecore:EReference" name="content" upperBound="-1"
            eType="#//level0/actionspecifications/ActionSpecification" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="declaredVariable" upperBound="-1"
            eType="#//level0/structures/Variable" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="declaredDataType" upperBound="-1"
            eType="#//level0/expressions/DataType" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ControlFlowAction" abstract="true"
          eSuperTypes="#//level0/actionspecifications/ActionSpecification"/>
      <eClassifiers xsi:type="ecore:EClass" name="JumpAction" abstract="true" eSuperTypes="#//level0/actionspecifications/ControlFlowAction"/>
      <eClassifiers xsi:type="ecore:EClass" name="IfAction" eSuperTypes="#//level0/actionspecifications/ConditionalAction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
            eType="#//level0/expressions/Expression" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="ifCase" lowerBound="1"
            eType="#//level0/actionspecifications/ActionSpecification" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="elseCase" eType="#//level0/actionspecifications/ActionSpecification"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LoopAction" abstract="true" eSuperTypes="#//level0/actionspecifications/ControlFlowAction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
            eType="#//level0/expressions/Expression" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="content" lowerBound="1"
            eType="#//level0/actionspecifications/ActionSpecification" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SwitchAction" eSuperTypes="#//level0/actionspecifications/ConditionalAction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="defaultAction" eType="#//level0/actionspecifications/ActionSpecification"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="switchExpression" lowerBound="1"
            eType="#//level0/expressions/Expression" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="case" upperBound="-1"
            eType="#//level0/actionspecifications/SwitchCase" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="WhileDoAction" eSuperTypes="#//level0/actionspecifications/LoopAction"/>
      <eClassifiers xsi:type="ecore:EClass" name="ForAction" eSuperTypes="#//level0/actionspecifications/LoopAction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="iteration" lowerBound="1"
            eType="#//level0/actionspecifications/ActionSpecification" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="initialization" lowerBound="1"
            eType="#//level0/actionspecifications/ActionSpecification" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ConditionalAction" abstract="true"
          eSuperTypes="#//level0/actionspecifications/ActionSpecification #//level0/actionspecifications/ControlFlowAction"/>
      <eClassifiers xsi:type="ecore:EClass" name="SwitchCase">
        <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
            eType="#//level0/expressions/Expression" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="caseAction" lowerBound="1"
            eType="#//level0/actionspecifications/ActionSpecification" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="#//level0/actionspecifications/ActionSpecification">
        <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
            eType="#//level0/expressions/Expression" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
            eType="#//level0/expressions/NavigationExpression" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Break" eSuperTypes="#//level0/actionspecifications/JumpAction"/>
      <eClassifiers xsi:type="ecore:EClass" name="Continue" eSuperTypes="#//level0/actionspecifications/JumpAction"/>
      <eClassifiers xsi:type="ecore:EClass" name="DoWhileAction" eSuperTypes="#//level0/actionspecifications/LoopAction"/>
      <eClassifiers xsi:type="ecore:EClass" name="InitializationCall" eSuperTypes="#//level0/expressions/Call #//level0/actionspecifications/ActionSpecification">
        <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
            eType="#//level0/structures/RichComponentProperty"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="behaviors" nsURI="http:///hrc/level0/behaviors.ecore" nsPrefix="hrc.level0.behaviors">
      <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
        <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1"
            upperBound="-1" eType="#//level0/behaviors/State" containment="true" eOpposite="#//level0/behaviors/State/stateMachine"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
            eType="#//level0/behaviors/Transition" containment="true" eOpposite="#//level0/behaviors/Transition/stateMachine"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="initialState" lowerBound="1"
            eType="#//level0/behaviors/State"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//level0/behaviors/HybridAutomatonBlock"
            transient="true" eOpposite="#//level0/behaviors/HybridAutomatonBlock/behavior"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="owningState" eType="#//level0/behaviors/State"
            transient="true" eOpposite="#//level0/behaviors/State/submachine"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//level0/structures/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" lowerBound="1"
            eType="#//level0/behaviors/StateMachine" transient="true" eOpposite="#//level0/behaviors/StateMachine/state"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
            eType="#//level0/behaviors/Transition" eOpposite="#//level0/behaviors/Transition/source"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
            eType="#//level0/behaviors/Transition" eOpposite="#//level0/behaviors/Transition/target"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="stateInvariant" eType="#//level0/expressions/Expression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="submachine" eType="#//level0/behaviors/StateMachine"
            containment="true" eOpposite="#//level0/behaviors/StateMachine/owningState"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Transition">
        <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" lowerBound="1"
            eType="#//level0/behaviors/StateMachine" transient="true" eOpposite="#//level0/behaviors/StateMachine/transition"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
            eType="#//level0/behaviors/State" eOpposite="#//level0/behaviors/State/outgoing"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
            eType="#//level0/behaviors/State" eOpposite="#//level0/behaviors/State/incoming"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="effect" eType="#//level0/actionspecifications/ActionSpecification"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="#//level0/expressions/Expression"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HRCBlock" abstract="true" eSuperTypes="#//level0/structures/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//level0/behaviors/CompositeBlock"
            transient="true" eOpposite="#//level0/behaviors/CompositeBlock/subBlock"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="assumingContract" eType="#//level0/behaviors/Contract"
            eOpposite="#//level0/behaviors/Contract/assumption"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="promisingContract"
            eType="#//level0/behaviors/Contract" eOpposite="#//level0/behaviors/Contract/promise"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
            eType="#//level0/structures/RichComponent" transient="true" eOpposite="#//level0/structures/RichComponent/block"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="pin" lowerBound="1"
            upperBound="-1" eType="#//level0/behaviors/BlockPin" containment="true"
            eOpposite="#//level0/behaviors/BlockPin/block"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="variable" upperBound="-1"
            eType="#//level0/structures/Variable" containment="true" eOpposite="#//level0/structures/Variable/block"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="implementation" eType="#//level0/behaviors/Implementation"
            eOpposite="#//level0/behaviors/Implementation/block"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CompositeBlock" eSuperTypes="#//level0/behaviors/HRCBlock">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//level0/behaviors/CompositionKind"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="pinLink" upperBound="-1"
            eType="#//level0/behaviors/PinLink" containment="true" eOpposite="#//level0/behaviors/PinLink/block"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="subBlock" lowerBound="1"
            upperBound="-1" eType="#//level0/behaviors/HRCBlock" containment="true"
            eOpposite="#//level0/behaviors/HRCBlock/owner"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Contract" eSuperTypes="#//level0/structures/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="assumption" lowerBound="1"
            eType="#//level0/behaviors/HRCBlock" eOpposite="#//level0/behaviors/HRCBlock/assumingContract"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="promise" lowerBound="1"
            eType="#//level0/behaviors/HRCBlock" eOpposite="#//level0/behaviors/HRCBlock/promisingContract"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
            eType="#//level0/structures/RichComponent" transient="true" eOpposite="#//level0/structures/RichComponent/contract"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="CompositionKind">
        <eLiterals name="conjunction"/>
        <eLiterals name="disjunction" value="1"/>
        <eLiterals name="parallel" value="2"/>
        <eLiterals name="negation" value="3"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Implementation">
        <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
            eType="#//level0/structures/RichComponent" transient="true" eOpposite="#//level0/structures/RichComponent/implementation"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//level0/behaviors/HRCBlock"
            eOpposite="#//level0/behaviors/HRCBlock/implementation"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="artifact" eType="#//level0/behaviors/Artifact"
            containment="true" eOpposite="#//level0/behaviors/Artifact/implementation"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Pin" abstract="true" eSuperTypes="#//level0/structures/NamedElement #//level0/expressions/NavigableFeature">
        <eStructuralFeatures xsi:type="ecore:EReference" name="pinLink" upperBound="-1"
            eType="#//level0/behaviors/PinLink" eOpposite="#//level0/behaviors/PinLink/pin"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BlockPin" eSuperTypes="#//level0/behaviors/Pin">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//level0/structures/DirectionKind"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//level0/structures/FlowKind"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="block" lowerBound="1"
            eType="#//level0/behaviors/HRCBlock" transient="true" eOpposite="#//level0/behaviors/HRCBlock/pin"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
            eType="#//level0/expressions/DataType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ReferencePin" eSuperTypes="#//level0/behaviors/Pin">
        <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1"
            eType="#//level0/structures/Port"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="flow" lowerBound="1"
            eType="#//level0/structures/Flow"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
            eType="#//level0/structures/RichComponent" transient="true" eOpposite="#//level0/structures/RichComponent/pin"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="role" eType="#//level0/structures/RichComponentProperty"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ProbabilisticBlock" eSuperTypes="#//level0/behaviors/HRCBlock">
        <eStructuralFeatures xsi:type="ecore:EReference" name="probability" lowerBound="1"
            eType="#//level0/expressions/FunctionCall" containment="true" eOpposite="#//level0/expressions/FunctionCall/block"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PinLink">
        <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//level0/behaviors/CompositeBlock"
            transient="true" eOpposite="#//level0/behaviors/CompositeBlock/pinLink"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="pin" lowerBound="2"
            upperBound="2" eType="#//level0/behaviors/Pin" eOpposite="#//level0/behaviors/Pin/pinLink"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//level0/structures/RichComponent"
            transient="true" eOpposite="#//level0/structures/RichComponent/pinLink"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HybridAutomatonBlock" eSuperTypes="#//level0/behaviors/HRCBlock">
        <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" lowerBound="1"
            eType="#//level0/behaviors/StateMachine" containment="true" eOpposite="#//level0/behaviors/StateMachine/block"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Artifact">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="implementation" lowerBound="1"
            eType="#//level0/behaviors/Implementation" transient="true" eOpposite="#//level0/behaviors/Implementation/artifact"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="expressions" nsURI="http:///hrc/level0/expressions.ecore"
        nsPrefix="hrc.level0.expressions">
      <eClassifiers xsi:type="ecore:EClass" name="BuiltinExpression" abstract="true"
          eSuperTypes="#//level0/expressions/Expression"/>
      <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteral" eSuperTypes="#//level0/expressions/LiteralSpecification">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="boolean-value"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="IntegerLiteral" eSuperTypes="#//level0/expressions/LiteralSpecification">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="integer-value"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RealLiteral" eSuperTypes="#//level0/expressions/LiteralSpecification">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="real-value"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LiteralSpecification" abstract="true"
          eSuperTypes="#//level0/expressions/Expression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="constant-expression"/>
        </eAnnotations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//level0/expressions/LiteralSpecification">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="string-value"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="expression"/>
        </eAnnotations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RecordNavigation" eSuperTypes="#//level0/expressions/DataNavigation">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Operator: ."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="field" lowerBound="1"
            eType="#//level0/expressions/Field"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ArrayNavigation" eSuperTypes="#//level0/expressions/DataNavigation">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Operator: []"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="index" lowerBound="1"
            eType="#//level0/expressions/Expression" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="NavigationExpression" abstract="true"
          eSuperTypes="#//level0/expressions/Expression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Relates access operators for composite types"/>
        </eAnnotations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" eSuperTypes="#//level0/expressions/BuiltinExpression">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//level0/expressions/UnaryOperator"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1"
            eType="#//level0/expressions/Expression" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" eSuperTypes="#//level0/expressions/BuiltinExpression">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//level0/expressions/BinaryOperator"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1"
            eType="#//level0/expressions/Expression" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1"
            eType="#//level0/expressions/Expression" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="UnaryOperator">
        <eLiterals name="negative"/>
        <eLiterals name="positive" value="1"/>
        <eLiterals name="bitwise_complement" value="2"/>
        <eLiterals name="logical_not" value="3"/>
        <eLiterals name="derivative" value="4"/>
        <eLiterals name="defined" value="5"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="BinaryOperator">
        <eLiterals name="addition"/>
        <eLiterals name="substraction" value="1"/>
        <eLiterals name="multiplication" value="2"/>
        <eLiterals name="division" value="3"/>
        <eLiterals name="modulus" value="4"/>
        <eLiterals name="bitwise_left" value="5"/>
        <eLiterals name="bitwise_right" value="6"/>
        <eLiterals name="bitwise_and" value="7"/>
        <eLiterals name="bitwise_or" value="8"/>
        <eLiterals name="equality" value="9"/>
        <eLiterals name="inequality" value="10"/>
        <eLiterals name="less_than" value="11"/>
        <eLiterals name="greater_than" value="12"/>
        <eLiterals name="less_than_or_equal" value="13"/>
        <eLiterals name="greater_than_or_equal" value="14"/>
        <eLiterals name="logical_and" value="15"/>
        <eLiterals name="logical_or" value="16"/>
        <eLiterals name="logical_implication" value="17"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Field" eSuperTypes="#//level0/structures/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
            eType="#//level0/expressions/DataType"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="record" lowerBound="1"
            eType="#//level0/expressions/Record" transient="true" eOpposite="#//level0/expressions/Record/field"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Record" eSuperTypes="#//level0/expressions/DataType">
        <eStructuralFeatures xsi:type="ecore:EReference" name="field" upperBound="-1"
            eType="#//level0/expressions/Field" containment="true" eOpposite="#//level0/expressions/Field/record"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" eSuperTypes="#//level0/expressions/DataType"/>
      <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#//level0/expressions/DataType">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Added constraint: self.ownedLiteral->notEmpty()"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="literal" lowerBound="1"
            upperBound="-1" eType="#//level0/expressions/EnumerationLiteral" containment="true"
            eOpposite="#//level0/expressions/EnumerationLiteral/enumeration"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="EnumerationLiteral" eSuperTypes="#//level0/structures/NamedElement #//level0/expressions/LiteralSpecification">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Ignored: inherits from InstanceSpecification -> PackageableElement"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="enumeration" lowerBound="1"
            eType="#//level0/expressions/Enumeration" transient="true" eOpposite="#//level0/expressions/Enumeration/literal"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true" eSuperTypes="#//level0/structures/NamedElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="Array" eSuperTypes="#//level0/expressions/DataType">
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
            eType="#//level0/expressions/DataType"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="size" lowerBound="1"
            eType="#//level0/expressions/Expression" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RecordInstance" eSuperTypes="#//level0/expressions/InstanceSpecification">
        <eStructuralFeatures xsi:type="ecore:EReference" name="slot" lowerBound="1"
            upperBound="-1" eType="#//level0/expressions/RecordSlot" containment="true"
            eOpposite="#//level0/expressions/RecordSlot/recordInstance"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ArrayInstance" eSuperTypes="#//level0/expressions/InstanceSpecification">
        <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
            upperBound="-1" eType="#//level0/expressions/Expression" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RecordSlot">
        <eStructuralFeatures xsi:type="ecore:EReference" name="field" lowerBound="1"
            eType="#//level0/expressions/Field"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="recordInstance" lowerBound="1"
            eType="#//level0/expressions/RecordInstance" transient="true" eOpposite="#//level0/expressions/RecordInstance/slot"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
            eType="#//level0/expressions/Expression" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DataNavigation" abstract="true"
          eSuperTypes="#//level0/expressions/NavigationExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
            eType="#//level0/expressions/NavigationExpression" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="NavigableFeature" abstract="true"
          eSuperTypes="#//level0/expressions/NavigationExpression"/>
      <eClassifiers xsi:type="ecore:EClass" name="InstanceSpecification" abstract="true"
          eSuperTypes="#//level0/expressions/Expression"/>
      <eClassifiers xsi:type="ecore:EClass" name="FunctionCall" eSuperTypes="#//level0/expressions/Call #//level0/expressions/Expression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//level0/behaviors/ProbabilisticBlock"
            transient="true" eOpposite="#//level0/behaviors/ProbabilisticBlock/probability"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="function" lowerBound="1"
            eType="#//level0/expressions/Function"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Call" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="argument" upperBound="-1"
            eType="#//level0/expressions/Expression" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//level0/structures/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1"
            eType="#//level0/structures/HRCModel" transient="true" eOpposite="#//level0/structures/HRCModel/function"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
            eType="#//level0/structures/Parameter" containment="true" eOpposite="#//level0/structures/Parameter/function"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" lowerBound="1"
            eType="#//level0/expressions/DataType"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="structures" nsURI="http:///hrc/level0/structures.ecore" nsPrefix="hrc.level0.structures">
      <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="#//level0/structures/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConjugated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
            eType="#//level0/structures/RichComponent" transient="true" eOpposite="#//level0/structures/RichComponent/port"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
            eType="#//level0/structures/PortSpecification"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="bindingEnd" upperBound="-1"
            eType="#//level0/structures/BindingEnd" eOpposite="#//level0/structures/BindingEnd/port"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RichComponent" eSuperTypes="#//level0/structures/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="contract" upperBound="-1"
            eType="#//level0/behaviors/Contract" containment="true" eOpposite="#//level0/behaviors/Contract/context"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="implementation" eType="#//level0/behaviors/Implementation"
            containment="true" eOpposite="#//level0/behaviors/Implementation/context"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="block" upperBound="-1"
            eType="#//level0/behaviors/HRCBlock" containment="true" eOpposite="#//level0/behaviors/HRCBlock/context"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="pinLink" upperBound="-1"
            eType="#//level0/behaviors/PinLink" containment="true" eOpposite="#//level0/behaviors/PinLink/context"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="pin" upperBound="-1"
            eType="#//level0/behaviors/ReferencePin" containment="true" eOpposite="#//level0/behaviors/ReferencePin/context"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="initializer" eType="#//level0/structures/Initializer"
            containment="true" eOpposite="#//level0/structures/Initializer/context"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="port" upperBound="-1"
            eType="#//level0/structures/Port" containment="true" eOpposite="#//level0/structures/Port/context"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="innerBinding" upperBound="-1"
            eType="#//level0/structures/Binding" containment="true" eOpposite="#//level0/structures/Binding/context"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" upperBound="-1"
            eType="#//level0/structures/Variable" containment="true" eOpposite="#//level0/structures/Variable/richComponent"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="part" upperBound="-1"
            eType="#//level0/structures/RichComponentProperty" containment="true"
            eOpposite="#//level0/structures/RichComponentProperty/context"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="refinedComponent" upperBound="-1"
            eType="#//level0/structures/RichComponent" eOpposite="#//level0/structures/RichComponent/refiningComponent"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="refiningComponent"
            upperBound="-1" eType="#//level0/structures/RichComponent" eOpposite="#//level0/structures/RichComponent/refinedComponent"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1"
            eType="#//level0/structures/HRCModel" transient="true" eOpposite="#//level0/structures/HRCModel/richComponent"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="DirectionKind">
        <eLiterals name="in"/>
        <eLiterals name="out" value="1"/>
        <eLiterals name="inout" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="FlowKind">
        <eLiterals name="discrete"/>
        <eLiterals name="continuous" value="1"/>
        <eLiterals name="event" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Initializer">
        <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
            eType="#//level0/structures/RichComponent" transient="true" eOpposite="#//level0/structures/RichComponent/initializer"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
            eType="#//level0/structures/Parameter" containment="true" eOpposite="#//level0/structures/Parameter/initializer"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
            eType="#//level0/actionspecifications/ActionSpecification" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Binding">
        <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="2"
            upperBound="-1" eType="#//level0/structures/BindingEnd" containment="true"
            eOpposite="#//level0/structures/BindingEnd/binding"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
            eType="#//level0/structures/RichComponent" transient="true" eOpposite="#//level0/structures/RichComponent/innerBinding"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BindingEnd">
        <eStructuralFeatures xsi:type="ecore:EReference" name="binding" lowerBound="1"
            eType="#//level0/structures/Binding" transient="true" eOpposite="#//level0/structures/Binding/end"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="role" eType="#//level0/structures/RichComponentProperty"
            eOpposite="#//level0/structures/RichComponentProperty/bindingEnd"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="flow" lowerBound="1"
            eType="#//level0/structures/Flow" eOpposite="#//level0/structures/Flow/bindingEnd"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1"
            eType="#//level0/structures/Port" eOpposite="#//level0/structures/Port/bindingEnd"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Flow" eSuperTypes="#//level0/structures/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//level0/structures/DirectionKind"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//level0/structures/FlowKind"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="portSpecification"
            lowerBound="1" eType="#//level0/structures/PortSpecification" transient="true"
            eOpposite="#//level0/structures/PortSpecification/flow"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
            eType="#//level0/expressions/DataType"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="bindingEnd" upperBound="-1"
            eType="#//level0/structures/BindingEnd" eOpposite="#//level0/structures/BindingEnd/flow"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//level0/structures/NamedElement #//level0/expressions/NavigableFeature">
        <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//level0/behaviors/HRCBlock"
            transient="true" eOpposite="#//level0/behaviors/HRCBlock/variable"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="richComponent" eType="#//level0/structures/RichComponent"
            transient="true" eOpposite="#//level0/structures/RichComponent/attribute"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
            eType="#//level0/expressions/DataType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RichComponentProperty" eSuperTypes="#//level0/structures/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
            eType="#//level0/structures/RichComponent" transient="true" eOpposite="#//level0/structures/RichComponent/part"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="bindingEnd" upperBound="-1"
            eType="#//level0/structures/BindingEnd" eOpposite="#//level0/structures/BindingEnd/role"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
            eType="#//level0/structures/RichComponent"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PortSpecification" eSuperTypes="#//level0/structures/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="flow" lowerBound="1"
            upperBound="-1" eType="#//level0/structures/Flow" containment="true" eOpposite="#//level0/structures/Flow/portSpecification"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1"
            eType="#//level0/structures/HRCModel" transient="true" eOpposite="#//level0/structures/HRCModel/portSpecification"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//level0/structures/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//level0/expressions/Function"
            transient="true" eOpposite="#//level0/expressions/Function/parameter"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="initializer" eType="#//level0/structures/Initializer"
            transient="true" eOpposite="#//level0/structures/Initializer/parameter"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
            eType="#//level0/expressions/DataType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HRCModel" eSuperTypes="#//level0/structures/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="function" upperBound="-1"
            eType="#//level0/expressions/Function" containment="true" eOpposite="#//level0/expressions/Function/model"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="portSpecification"
            upperBound="-1" eType="#//level0/structures/PortSpecification" containment="true"
            eOpposite="#//level0/structures/PortSpecification/model"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="richComponent" lowerBound="1"
            upperBound="-1" eType="#//level0/structures/RichComponent" containment="true"
            eOpposite="#//level0/structures/RichComponent/model"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//level0/structures/RichComponent"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
