<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EAnnotation source="ModellingUnit">
    <details key="require" value="kermeta|"/>
    <details key="using" value="kermeta::language::structure|comp_assignment_test004|"/>
  </ecore:EAnnotation>
  <ecore:EPackage name="comp_assignment_test004" nsURI="toto" nsPrefix="comp_assignment_test004">
    <eClassifiers xsi:type="ecore:EClass" name="Main">
      <eOperations name="main" ordered="false">
        <eAnnotations source="kermeta">
          <details key="body" value="do&#xA;&#x9;var a : comp_assignment_test004::A init comp_assignment_test004::A.new&#xA;&#x9;a.name := &quot;Assignment of a feature&quot;&#xA;&#x9;var b1 : comp_assignment_test004::B init comp_assignment_test004::B.new&#xA;&#x9;var b2 : comp_assignment_test004::B init comp_assignment_test004::B.new&#xA;&#x9;a.b.add(b1)&#xA;&#x9;a.b.add(b2)&#xA;&#x9;stdio.writeln(&quot;a.name: &quot;.plus(a.name))&#xA;&#x9;a.b.each{eeeee | stdio.writeln(&quot;a.b: &quot;.plus(eeeee.toString))}&#xA;end"/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="&#x9;comp_assignment_test004.A a = comp_assignment_test004.Comp_assignment_test004Factory.eINSTANCE.createA();&#xA;&#x9;setA.name()(&quot;Assignment of a feature&quot;);&#xA;&#x9;comp_assignment_test004.B b1 = comp_assignment_test004.Comp_assignment_test004Factory.eINSTANCE.createB();&#xA;&#x9;comp_assignment_test004.B b2 = comp_assignment_test004.Comp_assignment_test004Factory.eINSTANCE.createB();&#xA;&#x9;a.b();.add(b1)&#xA;&#x9;a.b();.add(b2)&#xA;&#x9;System.out.println(&quot;a.name: &quot;.plus(a.name();))&#xA;&#x9;a.b();.each&#xA;"/>
        </eAnnotations>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="A">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="/1/String">
        <eAnnotations source="kermeta">
          <details key="isComposite" value="true"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="b" upperBound="-1" eType="/1/B" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="B"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="_KermetaSpecialTypesAlias_" instanceClassName="java.lang.Object"/>
  </ecore:EPackage>
  <ecore:EAnnotation source="dependentResource"/>
</xmi:XMI>
