<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ex"
    nsURI="platform:/resource/org.kermeta.ki.pruning.examples/src/kermeta/mapping/MappingModel.ecore#/"
    nsPrefix="ex">
  <eSubpackages name="mappingModel" nsURI="platform:/resource/org.kermeta.ki.pruning.examples/src/kermeta/mapping/MappingModel.ecore#/ex/mappingModel"
      nsPrefix="mappingModel">
    <eClassifiers xsi:type="ecore:EClass" name="MappingModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
          eType="#//mappingModel/Mapping" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="src" eType="ecore:EClass ClassModel.ecore#//classModel/ClassModel"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass ClassModel.ecore#//classModel/ClassModel"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Mapping">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="srcs" lowerBound="1"
          upperBound="-1" eType="ecore:EClass ClassModel.ecore#//classModel/Clazz"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targets" lowerBound="1"
          upperBound="-1" eType="ecore:EClass ClassModel.ecore#//classModel/Clazz"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
