/**
 * <copyright>
 * </copyright>
 *
 * $Id: ComposerValidator.java,v 1.2 2009-01-22 20:26:53 mclavreu Exp $
 */
package kompose.validation;

import kompose.ElementDirective;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link kompose.Composer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComposerValidator {
	boolean validate();

	boolean validatePredirectivesPM(EList value);
	boolean validatePostdirectives(EList value);
	boolean validatePrimaryModelURI(String value);
	boolean validateAspectModelURI(String value);
	boolean validateComposedModelURI(String value);
	boolean validatePredirectivesAM(EList value);
}
