<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="Ecore"/>
  <ecore:EClass name="EPackage"/>
  <ecore:EObject/>
  <ecore:EClass name="ENamedElement" abstract="true"/>
  <ecore:EClass name="EClassifier" abstract="true"/>
  <ecore:EClass name="Extend"/>
  <ecore:EObject/>
  <ecore:EEnum name="ContentKind"/>
  <ecore:EClass name="EClass"/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EClass name="EDataType"/>
  <ecore:EObject/>
  <ecore:EClass name="EEnum"/>
  <ecore:EObject/>
  <ecore:EClass name="EEnumLiteral"/>
  <ecore:EObject/>
  <ecore:EClass name="EOperation"/>
  <ecore:EObject/>
  <ecore:EClass name="EParameter"/>
  <ecore:EObject/>
  <ecore:EEnum name="FeatureKind"/>
  <ecore:EClass name="EStructuralFeature" abstract="true"/>
  <ecore:EClass name="EAttribute"/>
  <ecore:EObject/>
  <ecore:EClass name="EReference"/>
  <ecore:EObject/>
  <ecore:EEnum name="VisibilityKind"/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EEnumLiteral name="Unspecified"/>
  <ecore:EEnumLiteral name="Empty"/>
  <ecore:EEnumLiteral name="Simple"/>
  <ecore:EEnumLiteral name="Mixed"/>
  <ecore:EEnumLiteral name="ElementOnly"/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EEnumLiteral name="Unspecified"/>
  <ecore:EEnumLiteral name="Simple"/>
  <ecore:EEnumLiteral name="Attribute"/>
  <ecore:EEnumLiteral name="Element"/>
  <ecore:EEnumLiteral name="AttributeWildcard"/>
  <ecore:EEnumLiteral name="ElementWildcard"/>
  <ecore:EEnumLiteral name="Group"/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EObject/>
  <ecore:EEnumLiteral name="Unspecified"/>
  <ecore:EEnumLiteral name="None"/>
  <ecore:EEnumLiteral name="ReadOnly"/>
  <ecore:EEnumLiteral name="ReadWrite"/>
  <ecore:EEnumLiteral name="ReadOnlyUnsettable"/>
  <ecore:EEnumLiteral name="ReadWriteUnsettable"/>
</xmi:XMI>
