/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package org.kermeta.kp.editor.grammar;

/**
 * This class provides the follow sets for all terminals of the grammar. These
 * sets are used during code completion.
 */
public class KpFollowSetProvider {
	
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_0 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_0_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_1 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_0_0_0_1);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_2 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_0_0_0_2);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_3 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_0_0_0_4_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_4 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_0_0_0_5_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_5 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_0_0_0_6);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_6 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_0_0_0_4_0_0_1);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_7 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_0_0_0_4_0_0_2);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_8 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_0_0_0_5_0_0_1);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_9 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_0_0_0_5_0_0_2);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_10 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_1_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_11 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_2_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_12 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_3_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_13 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_4_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_14 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_5_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_15 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_6_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_16 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_6_0_1_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_17 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_8_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_18 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_7_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_19 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_0_0_0_9);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_20 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_0_0_0_11);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_21 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_0_0_0_12);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_22 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_11_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_23 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_0_0_0_15);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_24 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_1_0_0_1);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_25 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_1_0_0_2);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_26 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_2_0_0_1);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_27 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_2_0_0_2_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_28 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_2_0_0_2_0_1_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_29 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_3_0_0_1);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_30 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_3_0_0_2_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_31 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_3_0_0_2_0_1_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_32 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_4_0_0_1);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_33 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_4_0_0_2);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_34 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_4_0_0_3_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_35 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_4_0_0_3_0_0_1);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_36 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_5_0_0_1);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_37 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_5_0_0_2);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_38 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_5_0_0_3_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_39 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_5_0_0_3_0_0_1);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_40 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_5_0_0_3_0_0_2_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_41 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_5_0_0_3_0_0_2_0_0_1);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_42 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_5_0_0_3_0_0_2_0_0_2);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_43 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_6_0_0_1);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_44 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_6_0_0_2);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_45 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_6_0_0_3);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_46 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_6_0_0_4);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_47 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_6_0_1_1);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_48 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_6_0_1_2);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_49 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_6_0_1_3);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_50 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_6_0_1_4);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_51 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_6_0_1_5);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_52 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_7_0_0_1);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_53 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_7_0_0_2);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_54 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_9_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_55 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_10_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_56 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_8_0_0_1);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_57 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_8_0_0_2);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_58 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_8_0_0_3);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_59 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_10_0_0_3);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_60 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_11_0_0_1);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_61 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_11_0_0_2);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_62 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_11_0_0_3_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_63 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_11_0_0_4_0_0_0);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_64 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_11_0_0_3_0_0_1);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_65 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_11_0_0_3_0_0_2);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_66 = new org.kermeta.kp.editor.mopp.KpExpectedStructuralFeature(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_11_0_0_4_0_0_1);
	public final static org.kermeta.kp.editor.IKpExpectedElement TERMINAL_67 = new org.kermeta.kp.editor.mopp.KpExpectedCsString(org.kermeta.kp.editor.grammar.KpGrammarInformationProvider.KP_11_0_0_4_0_0_2);
	
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_0 = org.kermeta.kp.KpPackage.eINSTANCE.getKermetaProject().getEStructuralFeature(org.kermeta.kp.KpPackage.KERMETA_PROJECT__SOURCES);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_1 = org.kermeta.kp.KpPackage.eINSTANCE.getKermetaProject().getEStructuralFeature(org.kermeta.kp.KpPackage.KERMETA_PROJECT__DEPENDENCIES);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_2 = org.kermeta.kp.KpPackage.eINSTANCE.getKermetaProject().getEStructuralFeature(org.kermeta.kp.KpPackage.KERMETA_PROJECT__OPTIONS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_3 = org.kermeta.kp.KpPackage.eINSTANCE.getKermetaProject().getEStructuralFeature(org.kermeta.kp.KpPackage.KERMETA_PROJECT__WEAVE_DIRECTIVES);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_4 = org.kermeta.kp.KpPackage.eINSTANCE.getKermetaProject().getEStructuralFeature(org.kermeta.kp.KpPackage.KERMETA_PROJECT__REF);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_5 = org.kermeta.kp.KpPackage.eINSTANCE.getWeaveDirective().getEStructuralFeature(org.kermeta.kp.KpPackage.WEAVE_DIRECTIVE__MIX);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_6 = org.kermeta.kp.KpPackage.eINSTANCE.getWeaveDirective().getEStructuralFeature(org.kermeta.kp.KpPackage.WEAVE_DIRECTIVE__TARGET);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_7 = org.kermeta.kp.KpPackage.eINSTANCE.getMixExpression().getEStructuralFeature(org.kermeta.kp.KpPackage.MIX_EXPRESSION__LEFT);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_8 = org.kermeta.kp.KpPackage.eINSTANCE.getMixExpression().getEStructuralFeature(org.kermeta.kp.KpPackage.MIX_EXPRESSION__RIGHT);
	
	public final static org.eclipse.emf.ecore.EStructuralFeature[] EMPTY_FEATURE_ARRAY = new org.eclipse.emf.ecore.EStructuralFeature[0];
	
	public static void wire0() {
		TERMINAL_0.addFollower(TERMINAL_1, EMPTY_FEATURE_ARRAY);
		TERMINAL_1.addFollower(TERMINAL_2, EMPTY_FEATURE_ARRAY);
		TERMINAL_2.addFollower(TERMINAL_3, EMPTY_FEATURE_ARRAY);
		TERMINAL_2.addFollower(TERMINAL_4, EMPTY_FEATURE_ARRAY);
		TERMINAL_2.addFollower(TERMINAL_5, EMPTY_FEATURE_ARRAY);
		TERMINAL_3.addFollower(TERMINAL_6, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_7, EMPTY_FEATURE_ARRAY);
		TERMINAL_7.addFollower(TERMINAL_4, EMPTY_FEATURE_ARRAY);
		TERMINAL_7.addFollower(TERMINAL_5, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_8, EMPTY_FEATURE_ARRAY);
		TERMINAL_8.addFollower(TERMINAL_9, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_5, EMPTY_FEATURE_ARRAY);
		TERMINAL_5.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_5.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_5.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_5.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_5.addFollower(TERMINAL_14, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_5.addFollower(TERMINAL_15, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_5.addFollower(TERMINAL_16, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_5.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_5.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_5.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_19.addFollower(TERMINAL_20, EMPTY_FEATURE_ARRAY);
		TERMINAL_20.addFollower(TERMINAL_21, EMPTY_FEATURE_ARRAY);
		TERMINAL_21.addFollower(TERMINAL_22, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_21.addFollower(TERMINAL_23, EMPTY_FEATURE_ARRAY);
		TERMINAL_10.addFollower(TERMINAL_24, EMPTY_FEATURE_ARRAY);
		TERMINAL_24.addFollower(TERMINAL_25, EMPTY_FEATURE_ARRAY);
		TERMINAL_25.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_25.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_25.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_25.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_25.addFollower(TERMINAL_14, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_25.addFollower(TERMINAL_15, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_25.addFollower(TERMINAL_16, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_25.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_25.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_25.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_11.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_26.addFollower(TERMINAL_27, EMPTY_FEATURE_ARRAY);
		TERMINAL_26.addFollower(TERMINAL_28, EMPTY_FEATURE_ARRAY);
		TERMINAL_27.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_27.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_27.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_27.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_27.addFollower(TERMINAL_14, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_27.addFollower(TERMINAL_15, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_27.addFollower(TERMINAL_16, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_27.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_27.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_27.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_28.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_28.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_28.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_28.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_28.addFollower(TERMINAL_14, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_28.addFollower(TERMINAL_15, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_28.addFollower(TERMINAL_16, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_28.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_28.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_28.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_12.addFollower(TERMINAL_29, EMPTY_FEATURE_ARRAY);
		TERMINAL_29.addFollower(TERMINAL_30, EMPTY_FEATURE_ARRAY);
		TERMINAL_29.addFollower(TERMINAL_31, EMPTY_FEATURE_ARRAY);
		TERMINAL_30.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_30.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_30.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_30.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_30.addFollower(TERMINAL_14, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_30.addFollower(TERMINAL_15, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_30.addFollower(TERMINAL_16, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_30.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_30.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_30.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_31.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_31.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_31.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_31.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_31.addFollower(TERMINAL_14, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_31.addFollower(TERMINAL_15, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_31.addFollower(TERMINAL_16, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_31.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_31.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_31.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_13.addFollower(TERMINAL_32, EMPTY_FEATURE_ARRAY);
		TERMINAL_32.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
		TERMINAL_33.addFollower(TERMINAL_34, EMPTY_FEATURE_ARRAY);
		TERMINAL_33.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_33.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_33.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_33.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_33.addFollower(TERMINAL_14, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_33.addFollower(TERMINAL_15, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_33.addFollower(TERMINAL_16, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_33.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_33.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_33.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_34.addFollower(TERMINAL_35, EMPTY_FEATURE_ARRAY);
		TERMINAL_35.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_35.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_35.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_35.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_35.addFollower(TERMINAL_14, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_35.addFollower(TERMINAL_15, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_35.addFollower(TERMINAL_16, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_35.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_35.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_35.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_36, EMPTY_FEATURE_ARRAY);
		TERMINAL_36.addFollower(TERMINAL_37, EMPTY_FEATURE_ARRAY);
		TERMINAL_37.addFollower(TERMINAL_38, EMPTY_FEATURE_ARRAY);
		TERMINAL_37.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_37.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_37.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_37.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_37.addFollower(TERMINAL_14, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_37.addFollower(TERMINAL_15, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_37.addFollower(TERMINAL_16, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_37.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_37.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_37.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_38.addFollower(TERMINAL_39, EMPTY_FEATURE_ARRAY);
		TERMINAL_39.addFollower(TERMINAL_40, EMPTY_FEATURE_ARRAY);
		TERMINAL_39.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_39.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_39.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_39.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_39.addFollower(TERMINAL_14, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_39.addFollower(TERMINAL_15, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_39.addFollower(TERMINAL_16, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_39.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_39.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_39.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_40.addFollower(TERMINAL_41, EMPTY_FEATURE_ARRAY);
		TERMINAL_41.addFollower(TERMINAL_42, EMPTY_FEATURE_ARRAY);
		TERMINAL_42.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_42.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_42.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_42.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_42.addFollower(TERMINAL_14, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_42.addFollower(TERMINAL_15, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_42.addFollower(TERMINAL_16, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_42.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_42.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_42.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_15.addFollower(TERMINAL_43, EMPTY_FEATURE_ARRAY);
		TERMINAL_43.addFollower(TERMINAL_44, EMPTY_FEATURE_ARRAY);
		TERMINAL_44.addFollower(TERMINAL_45, EMPTY_FEATURE_ARRAY);
		TERMINAL_45.addFollower(TERMINAL_46, EMPTY_FEATURE_ARRAY);
		TERMINAL_46.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_46.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_46.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_46.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_46.addFollower(TERMINAL_14, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_46.addFollower(TERMINAL_15, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_46.addFollower(TERMINAL_16, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_46.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_46.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_46.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_16.addFollower(TERMINAL_47, EMPTY_FEATURE_ARRAY);
		TERMINAL_47.addFollower(TERMINAL_48, EMPTY_FEATURE_ARRAY);
		TERMINAL_48.addFollower(TERMINAL_49, EMPTY_FEATURE_ARRAY);
		TERMINAL_49.addFollower(TERMINAL_50, EMPTY_FEATURE_ARRAY);
		TERMINAL_49.addFollower(TERMINAL_51, EMPTY_FEATURE_ARRAY);
		TERMINAL_49.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_49.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_49.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_49.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_49.addFollower(TERMINAL_14, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_49.addFollower(TERMINAL_15, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_49.addFollower(TERMINAL_16, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_49.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_49.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_49.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_50.addFollower(TERMINAL_51, EMPTY_FEATURE_ARRAY);
		TERMINAL_50.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_50.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_50.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_50.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_50.addFollower(TERMINAL_14, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_50.addFollower(TERMINAL_15, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_50.addFollower(TERMINAL_16, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_50.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_50.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_50.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_51.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_51.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_51.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_51.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_51.addFollower(TERMINAL_14, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_51.addFollower(TERMINAL_15, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_51.addFollower(TERMINAL_16, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_51.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_51.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_51.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_18.addFollower(TERMINAL_52, EMPTY_FEATURE_ARRAY);
		TERMINAL_18.addFollower(TERMINAL_53, EMPTY_FEATURE_ARRAY);
		TERMINAL_52.addFollower(TERMINAL_53, EMPTY_FEATURE_ARRAY);
		TERMINAL_53.addFollower(TERMINAL_54, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_53.addFollower(TERMINAL_55, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_17.addFollower(TERMINAL_56, EMPTY_FEATURE_ARRAY);
		TERMINAL_17.addFollower(TERMINAL_57, EMPTY_FEATURE_ARRAY);
		TERMINAL_56.addFollower(TERMINAL_57, EMPTY_FEATURE_ARRAY);
		TERMINAL_57.addFollower(TERMINAL_58, EMPTY_FEATURE_ARRAY);
		TERMINAL_58.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_58.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_58.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_58.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_58.addFollower(TERMINAL_14, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_58.addFollower(TERMINAL_15, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_58.addFollower(TERMINAL_16, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_58.addFollower(TERMINAL_17, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_58.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_58.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_54.addFollower(TERMINAL_54, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_54.addFollower(TERMINAL_55, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_55.addFollower(TERMINAL_54, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_55.addFollower(TERMINAL_55, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_59.addFollower(TERMINAL_54, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_59.addFollower(TERMINAL_55, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_22.addFollower(TERMINAL_60, EMPTY_FEATURE_ARRAY);
		TERMINAL_60.addFollower(TERMINAL_61, EMPTY_FEATURE_ARRAY);
		TERMINAL_61.addFollower(TERMINAL_62, EMPTY_FEATURE_ARRAY);
		TERMINAL_61.addFollower(TERMINAL_63, EMPTY_FEATURE_ARRAY);
		TERMINAL_61.addFollower(TERMINAL_22, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_61.addFollower(TERMINAL_23, EMPTY_FEATURE_ARRAY);
		TERMINAL_62.addFollower(TERMINAL_64, EMPTY_FEATURE_ARRAY);
		TERMINAL_64.addFollower(TERMINAL_65, EMPTY_FEATURE_ARRAY);
		TERMINAL_65.addFollower(TERMINAL_63, EMPTY_FEATURE_ARRAY);
		TERMINAL_65.addFollower(TERMINAL_22, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_65.addFollower(TERMINAL_23, EMPTY_FEATURE_ARRAY);
		TERMINAL_63.addFollower(TERMINAL_66, EMPTY_FEATURE_ARRAY);
		TERMINAL_66.addFollower(TERMINAL_67, EMPTY_FEATURE_ARRAY);
		TERMINAL_67.addFollower(TERMINAL_22, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_67.addFollower(TERMINAL_23, EMPTY_FEATURE_ARRAY);
	}
	// wire the terminals
	static {
		wire0();
	}
}
