<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EAnnotation source="ModellingUnit">
    <details key="require" value="http://www.eclipse.org/emf/2002/Ecore|kermeta|"/>
    <details key="using" value="kermeta::standard|test|"/>
  </ecore:EAnnotation>
  <ecore:EPackage name="test" nsURI="http://testTypeVariable" nsPrefix="test">
    <eClassifiers xsi:type="ecore:EClass" name="Main">
      <eTypeParameters name="G"/>
      <eOperations name="test_op1" ordered="false">
        <eAnnotations source="kermeta">
          <details key="body" value="do&#xA;end"/>
        </eAnnotations>
        <eParameters name="elt">
          <eGenericType eTypeParameter="/1/Main/G"/>
        </eParameters>
      </eOperations>
      <eOperations name="test_op2" ordered="false">
        <eAnnotations source="kermeta">
          <details key="body" value="do&#xA;end"/>
        </eAnnotations>
        <eTypeParameters name="F"/>
        <eParameters name="elt">
          <eGenericType eTypeParameter="/1/Main/test_op2/F"/>
        </eParameters>
      </eOperations>
      <eOperations name="test_op3">
        <eAnnotations source="kermeta">
          <details key="body" value="do&#xA;&#x9;result := void&#xA;end"/>
        </eAnnotations>
        <eGenericType eTypeParameter="/1/Main/G"/>
      </eOperations>
      <eOperations name="test_op4">
        <eAnnotations source="kermeta">
          <details key="body" value="do&#xA;&#x9;result := void&#xA;end"/>
        </eAnnotations>
        <eGenericType eTypeParameter="/1/Main/test_op4/F"/>
        <eTypeParameters name="F"/>
      </eOperations>
      <eOperations name="test_op5" ordered="false">
        <eAnnotations source="kermeta">
          <details key="body" value="do&#xA;end"/>
        </eAnnotations>
        <eTypeParameters name="F">
          <eBounds eTypeParameter="/1/Main/G"/>
        </eTypeParameters>
        <eParameters name="elt" eType="/1/AClass"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parametrizedAttr" containment="true">
        <eGenericType eTypeParameter="/1/Main/G"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AClass"/>
    <eClassifiers xsi:type="ecore:EDataType" name="_KermetaSpecialTypesAlias_" instanceClassName="java.lang.Object"/>
  </ecore:EPackage>
  <ecore:EAnnotation source="dependentResource"/>
</xmi:XMI>
