/**
 * <copyright>
 * </copyright>
 *
 * $Id: AbstractStepValidator.java,v 1.2 2008-02-14 07:12:49 uid21732 Exp $
 */
package org.kermeta.io.loader.validation;

import org.eclipse.emf.common.util.EList;

import org.kermeta.io.loader.LoadingStep;

/**
 * A sample validator interface for {@link org.kermeta.io.loader.AbstractStep}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractStepValidator {
	boolean validate();

	boolean validateSteps(EList<LoadingStep> value);
	boolean validateCurrentStep(LoadingStep value);
}
