/**
 * <copyright>
 * </copyright>
 *
 * $Id: EcoreLoaderValidator.java,v 1.2 2008-02-14 07:12:49 uid21732 Exp $
 */
package org.kermeta.io.loader.validation;


/**
 * A sample validator interface for {@link org.kermeta.io.loader.EcoreLoader}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EcoreLoaderValidator {
	boolean validate();

}
