/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.irisa.triskell.osgi.introspector.manifest.node;

import fr.irisa.triskell.osgi.introspector.manifest.analysis.*;

@SuppressWarnings("nls")
public final class ABundleDescriptionEntryManifestentry extends PManifestentry {
	private PBundleDescriptionEntry _bundleDescriptionEntry_;

	public ABundleDescriptionEntryManifestentry() {
		// Constructor
	}

	public ABundleDescriptionEntryManifestentry(@SuppressWarnings("hiding")
	PBundleDescriptionEntry _bundleDescriptionEntry_) {
		// Constructor
		setBundleDescriptionEntry(_bundleDescriptionEntry_);

	}

	@Override
	public Object clone() {
		return new ABundleDescriptionEntryManifestentry(
				cloneNode(this._bundleDescriptionEntry_));
	}

	public void apply(Switch sw) {
		((Analysis) sw).caseABundleDescriptionEntryManifestentry(this);
	}

	public PBundleDescriptionEntry getBundleDescriptionEntry() {
		return this._bundleDescriptionEntry_;
	}

	public void setBundleDescriptionEntry(PBundleDescriptionEntry node) {
		if (this._bundleDescriptionEntry_ != null) {
			this._bundleDescriptionEntry_.parent(null);
		}

		if (node != null) {
			if (node.parent() != null) {
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		this._bundleDescriptionEntry_ = node;
	}

	@Override
	public String toString() {
		return "" + toString(this._bundleDescriptionEntry_);
	}

	@Override
	void removeChild(@SuppressWarnings("unused")
	Node child) {
		// Remove child
		if (this._bundleDescriptionEntry_ == child) {
			this._bundleDescriptionEntry_ = null;
			return;
		}

		throw new RuntimeException("Not a child.");
	}

	@Override
	void replaceChild(@SuppressWarnings("unused")
	Node oldChild, @SuppressWarnings("unused")
	Node newChild) {
		// Replace child
		if (this._bundleDescriptionEntry_ == oldChild) {
			setBundleDescriptionEntry((PBundleDescriptionEntry) newChild);
			return;
		}

		throw new RuntimeException("Not a child.");
	}
}
