/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.irisa.triskell.osgi.introspector.manifest.node;

import fr.irisa.triskell.osgi.introspector.manifest.analysis.*;

@SuppressWarnings("nls")
public final class AImportPackageDirectiveImportPackageParameter extends
		PImportPackageParameter {
	private TSemicolon _semicolon_;
	private PImportPackageDirective _importPackageDirective_;

	public AImportPackageDirectiveImportPackageParameter() {
		// Constructor
	}

	public AImportPackageDirectiveImportPackageParameter(
			@SuppressWarnings("hiding")
			TSemicolon _semicolon_, @SuppressWarnings("hiding")
			PImportPackageDirective _importPackageDirective_) {
		// Constructor
		setSemicolon(_semicolon_);

		setImportPackageDirective(_importPackageDirective_);

	}

	@Override
	public Object clone() {
		return new AImportPackageDirectiveImportPackageParameter(
				cloneNode(this._semicolon_),
				cloneNode(this._importPackageDirective_));
	}

	public void apply(Switch sw) {
		((Analysis) sw).caseAImportPackageDirectiveImportPackageParameter(this);
	}

	public TSemicolon getSemicolon() {
		return this._semicolon_;
	}

	public void setSemicolon(TSemicolon node) {
		if (this._semicolon_ != null) {
			this._semicolon_.parent(null);
		}

		if (node != null) {
			if (node.parent() != null) {
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		this._semicolon_ = node;
	}

	public PImportPackageDirective getImportPackageDirective() {
		return this._importPackageDirective_;
	}

	public void setImportPackageDirective(PImportPackageDirective node) {
		if (this._importPackageDirective_ != null) {
			this._importPackageDirective_.parent(null);
		}

		if (node != null) {
			if (node.parent() != null) {
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		this._importPackageDirective_ = node;
	}

	@Override
	public String toString() {
		return "" + toString(this._semicolon_)
				+ toString(this._importPackageDirective_);
	}

	@Override
	void removeChild(@SuppressWarnings("unused")
	Node child) {
		// Remove child
		if (this._semicolon_ == child) {
			this._semicolon_ = null;
			return;
		}

		if (this._importPackageDirective_ == child) {
			this._importPackageDirective_ = null;
			return;
		}

		throw new RuntimeException("Not a child.");
	}

	@Override
	void replaceChild(@SuppressWarnings("unused")
	Node oldChild, @SuppressWarnings("unused")
	Node newChild) {
		// Replace child
		if (this._semicolon_ == oldChild) {
			setSemicolon((TSemicolon) newChild);
			return;
		}

		if (this._importPackageDirective_ == oldChild) {
			setImportPackageDirective((PImportPackageDirective) newChild);
			return;
		}

		throw new RuntimeException("Not a child.");
	}
}
