/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.irisa.triskell.osgi.introspector.manifest.node;

import fr.irisa.triskell.osgi.introspector.manifest.analysis.*;

@SuppressWarnings("nls")
public final class AOsnameWindows95OsnameValue extends POsnameValue {
	private TOsnameWindows95 _osnameWindows95_;

	public AOsnameWindows95OsnameValue() {
		// Constructor
	}

	public AOsnameWindows95OsnameValue(@SuppressWarnings("hiding")
	TOsnameWindows95 _osnameWindows95_) {
		// Constructor
		setOsnameWindows95(_osnameWindows95_);

	}

	@Override
	public Object clone() {
		return new AOsnameWindows95OsnameValue(
				cloneNode(this._osnameWindows95_));
	}

	public void apply(Switch sw) {
		((Analysis) sw).caseAOsnameWindows95OsnameValue(this);
	}

	public TOsnameWindows95 getOsnameWindows95() {
		return this._osnameWindows95_;
	}

	public void setOsnameWindows95(TOsnameWindows95 node) {
		if (this._osnameWindows95_ != null) {
			this._osnameWindows95_.parent(null);
		}

		if (node != null) {
			if (node.parent() != null) {
				node.parent().removeChild(node);
			}

			node.parent(this);
		}

		this._osnameWindows95_ = node;
	}

	@Override
	public String toString() {
		return "" + toString(this._osnameWindows95_);
	}

	@Override
	void removeChild(@SuppressWarnings("unused")
	Node child) {
		// Remove child
		if (this._osnameWindows95_ == child) {
			this._osnameWindows95_ = null;
			return;
		}

		throw new RuntimeException("Not a child.");
	}

	@Override
	void replaceChild(@SuppressWarnings("unused")
	Node oldChild, @SuppressWarnings("unused")
	Node newChild) {
		// Replace child
		if (this._osnameWindows95_ == oldChild) {
			setOsnameWindows95((TOsnameWindows95) newChild);
			return;
		}

		throw new RuntimeException("Not a child.");
	}
}
