/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.irisa.triskell.osgi.introspector.manifest.node;

public abstract class PSymbolicnameOption extends Node {
	// Empty body
}
