<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EAnnotation source="ModelingUnit">
    <details key="require" value="kermeta|"/>
    <details key="using" value="testString|"/>
  </ecore:EAnnotation>
  <ecore:EAnnotation source="kermeta">
    <details key="mainClass" value="testString::Main"/>
  </ecore:EAnnotation>
  <ecore:EAnnotation source="kermeta">
    <details key="mainOperation" value="main"/>
  </ecore:EAnnotation>
  <ecore:EPackage name="testString" nsURI="http://TestString" nsPrefix="testString">
    <eClassifiers xsi:type="ecore:EClass" name="Main">
      <eAnnotations source="kermeta">
        <details key="documentation" value="/** This class is used to test the conversion of KMT 2 Ecore &#xA; *  Notice : when we declare &quot;using kermeta::language::structure&quot;, the alias String is used, instead of the real&#xA; *  Class String. This leads to a wrong Ecore conversion&#xA; */"/>
      </eAnnotations>
      <eSuperTypes href="platform:/resource/fr.irisa.triskell.kermeta.io/src/kermeta/kermeta_java.ecore#/1/language/structure/Object"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EAnnotation source="dependentResource"/>
</xmi:XMI>
