package fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect
 class RichPropertyConstraint extends org.eclipse.emf.ecore.impl.EObjectImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.PropertyConstraint with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.PropertyConstraintAspect 
 class RichProperty extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.PropertyImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.PropertyAspect 
 class RichClassDefinition extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.ClassDefinitionImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.ClassDefinitionAspect 
 class RichObject extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.ObjectImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.ObjectAspect 
 class RichModelType extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.ModelTypeImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.ModelTypeAspect 
 class RichClass extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.ClassImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.ClassAspect 
 class RichModel extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.ModelImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.ModelAspect 
 class RichType extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.TypeImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.TypeAspect 
 class RichNamedElement extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.NamedElementImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.NamedElementAspect 
 class RichEnumeration extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.EnumerationImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.EnumerationAspect 
 class RichFunctionType extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.FunctionTypeImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.FunctionTypeAspect 
 class RichOperation extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.OperationImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.OperationAspect 
 abstract class RichTypeContainer extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.TypeContainerImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.TypeContainerAspect 
 class RichEnumerationLiteral extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.EnumerationLiteralImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.EnumerationLiteralAspect 
 class RichTypeVariableBinding extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.TypeVariableBindingImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.TypeVariableBindingAspect 
 class RichMultiplicityElement extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.MultiplicityElementImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.MultiplicityElementAspect 
 abstract class RichTypedElement extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.TypedElementImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.TypedElementAspect 
 class RichTypeDefinition extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.TypeDefinitionImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.TypeDefinitionAspect 
 abstract class RichDataType extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.DataTypeImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.DataTypeAspect 
 class RichPackage extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.PackageImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.PackageAspect 
 class RichParameter extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.ParameterImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.ParameterAspect 
 class RichPrimitiveType extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.PrimitiveTypeImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.PrimitiveTypeAspect 
 class RichTag extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.TagImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.TagAspect 
 class RichConstraint extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.ConstraintImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.ConstraintAspect 
 abstract class RichGenericTypeDefinition extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.GenericTypeDefinitionImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.GenericTypeDefinitionAspect 
 abstract class RichParameterizedType extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.ParameterizedTypeImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.ParameterizedTypeAspect 
 abstract class RichTypeVariable extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.TypeVariableImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.TypeVariableAspect 
 class RichObjectTypeVariable extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.ObjectTypeVariableImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.ObjectTypeVariableAspect 
 class RichModelTypeVariable extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.ModelTypeVariableImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.ModelTypeVariableAspect 
 class RichVirtualType extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.VirtualTypeImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.VirtualTypeAspect 
 class RichModelingUnit extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.ModelingUnitImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.ModelingUnitAspect 
 class RichRequire extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.RequireImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.RequireAspect 
 class RichUsing extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.UsingImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.UsingAspect 
 class RichFilter extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.FilterImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.FilterAspect 
 class RichProductType extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.ProductTypeImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.ProductTypeAspect 
 class RichVoidType extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.VoidTypeImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.VoidTypeAspect 
 abstract class RichTypeDefinitionContainer extends fr.irisa.triskell.kermeta.scala.framework.language.structure.impl.TypeDefinitionContainerImpl with fr.irisa.triskell.kermeta.scala.framework.language.structureScalaAspect.TypeDefinitionContainerAspect 

