global java.util.List list;
global java.util.Map uniqueobjects;
rule "RulesName"
	 when 
$s2: art.type.Service(name == "tutorial.diva.cas.INotifier")
$s3: art.type.Port(name == "notifier",role == "client",service == $s2)
$s4: art.type.Service(name == "tutorial.diva.cas.ICalendar")
$s5: art.type.Port(name == "calendar",role == "server",service == $s4)
$s6: art.type.PrimitiveType(name == "tutorial.diva.cas.calendar",port contains $s3,port contains $s5)
$s7: art.instance.PrimitiveInstance(name == "Calendar",type == $s6)
$s8: art.type.Service(name == "tutorial.diva.cas.IAddressDB")
$s9: art.type.Port(name == "addressDB",role == "server",service == $s8)
$s10: art.type.PrimitiveType(name == "tutorial.diva.cas.addressDB",port contains $s9)
$s11: art.instance.PrimitiveInstance(name == "AddressDataBase",type == $s10)
$s1: art.instance.CompositeInstance(name == "CAS application",subComponent contains $s7,subComponent contains $s11)
$s0: art.System(root == $s1)
then
 	 java.util.HashMap m = new java.util.HashMap();
m.put("anySystem",$s0);
m.put("theRootComponent",$s1);
m.put("theCalendarComponent",$s7);
m.put("theCalendarNotifierClientPort",$s3);
m.put("theAddressDBComponent",$s11);
m.put("theAddressDBProvidedPort",$s9);
	 list.add(m);
 art.System s0 = art.ArtFactory.eINSTANCE.createSystem();
$s0.getServices().add(null);
$s0.getServices().add(null);
$s0.getServices().add(null);
$s0.getServices().add(null);
$s0.getServices().add(null);
$s0.getServices().add(null);
$s0.getServices().add(null);
$s0.getTypes().add(null);
$s0.getTypes().add(null);
$s0.getTypes().add(null);
$s1.getSubComponent().add(null);
$s1.getSubComponent().add(null);
$s1.getSubComponent().add(null);
$s7.getBinding().add(null);
null.setClient($s3);
null.setServer($s9);
null.setServerInstance($s11);
end