global java.util.List list;
global java.util.Map uniqueobjects;
rule "RulesName"
	 when 
$s2: art.type.Service(name == "tutorial.diva.cas.IRankingStrategy")
$s3: art.type.Port(name == "rankingStrategies",role == "client",service == $s2)
$s4: art.type.PrimitiveType(name == "tutorial.diva.cas.notifier",port contains $s3)
$s5: art.instance.PrimitiveInstance(type == $s4)
$s1: art.instance.CompositeInstance(name == "CAS application",subComponent contains $s5)
$s0: art.System(root == $s1)
then
 	 java.util.HashMap m = new java.util.HashMap();
m.put("theSystem",$s0);
m.put("theRootComponent",$s1);
m.put("anyNotifierComponent",$s5);
m.put("anyRequiredNotifierPort",$s3);
	 list.add(m);
 art.System s0 = art.ArtFactory.eINSTANCE.createSystem();
$s0.getServices().add(null);
$s0.getTypes().add(null);
$s1.getSubComponent().add(null);
$s5.getBinding().add(null);
null.setClient($s3);
end