<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aPackage">
  <eClassifiers xsi:type="ecore:EClass" name="aClass">
    <eOperations name="anOperation" eType="#//anEnum">
      <eParameters name="aParameter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aReference" upperBound="-1"
        eType="#//aClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="aDataType" instanceClassName="kermeta::standard::Object"/>
  <eClassifiers xsi:type="ecore:EEnum" name="anEnum">
    <eLiterals name="aEnemLiteral"/>
    <eLiterals name="anotherEnumLiteral" value="1"/>
  </eClassifiers>
</ecore:EPackage>
