/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package art.resource.artext.grammar;

/**
 * This class provides the follow sets for all terminals of the grammar. These
 * sets are used during code completion.
 */
public class ArtextFollowSetProvider {
	
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_0 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_0_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_1 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_0_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_2 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_0_0_0_3);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_3 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_2_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_4 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_15_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_5 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_16_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_6 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_11_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_7 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_12_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_8 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_1_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_9 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_20_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_10 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_21_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_11 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_1_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_12 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_1_0_0_3);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_13 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_2_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_14 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_2_0_0_3_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_15 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_2_0_0_4);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_16 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_2_0_0_3_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_17 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_2_0_0_3_0_0_4);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_18 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_3_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_19 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_4_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_20 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_2_0_0_8);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_21 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_3_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_22 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_3_0_0_4);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_23 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_3_0_0_6);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_24 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_3_0_0_8);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_25 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_3_0_0_10);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_26 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_3_0_0_12_0_0_1);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_27 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_3_0_0_14);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_28 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_18_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_29 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_19_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_30 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_7_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_31 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_8_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_32 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_5_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_33 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_3_0_0_17);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_34 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_6_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_35 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_4_0_0_17);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_36 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_4_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_37 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_4_0_0_4);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_38 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_4_0_0_6);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_39 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_4_0_0_8);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_40 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_4_0_0_10);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_41 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_4_0_0_12_0_0_1);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_42 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_4_0_0_14);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_43 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_5_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_44 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_5_0_0_4);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_45 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_5_0_0_6);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_46 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_5_0_0_7);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_47 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_5_0_0_8);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_48 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_5_0_0_9_0_0_1);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_49 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_5_0_0_9_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_50 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_5_0_0_9_0_0_4);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_51 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_5_0_0_9_0_0_6);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_52 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_5_0_0_9_0_0_7);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_53 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_6_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_54 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_6_0_0_4);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_55 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_6_0_0_6);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_56 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_6_0_0_7);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_57 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_6_0_0_8);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_58 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_6_0_0_9_0_0_1);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_59 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_6_0_0_9_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_60 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_6_0_0_9_0_0_4);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_61 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_6_0_0_9_0_0_6);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_62 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_6_0_0_9_0_0_7);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_63 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_7_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_64 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_7_0_0_4);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_65 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_8_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_66 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_9_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_67 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_10_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_68 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_8_0_0_4_0_0_1_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_69 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_9_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_70 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_9_0_0_4);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_71 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_9_0_0_6);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_72 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_9_0_0_8);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_73 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_10_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_74 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_10_0_0_4);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_75 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_10_0_0_6);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_76 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_10_0_0_8);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_77 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_11_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_78 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_11_0_0_4_0_0_1);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_79 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_11_0_0_6);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_80 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_22_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_81 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_17_0_0_1);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_82 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_27_0_0_1);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_83 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_23_0_0_1);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_84 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_24_0_0_1);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_85 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_11_0_0_9);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_86 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_12_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_87 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_12_0_0_4_0_0_1);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_88 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_12_0_0_6);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_89 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_12_0_0_9);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_90 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_13_0_0_1);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_91 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_13_0_0_3);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_92 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_13_0_0_4);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_93 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_14_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_94 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_13_0_0_6_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_95 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_13_0_0_7);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_96 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_13_0_0_8_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_97 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_13_0_0_9_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_98 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_15_0_0_9);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_99 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_16_0_0_9);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_100 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_14_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_101 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_15_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_102 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_15_0_0_4);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_103 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_15_0_0_6);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_104 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_16_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_105 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_16_0_0_4);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_106 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_16_0_0_6);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_107 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_17_0_0_3);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_108 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_17_0_0_5);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_109 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_17_0_0_7);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_110 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_17_0_0_9);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_111 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_17_0_0_11);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_112 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_17_0_0_12);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_113 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_17_0_0_13);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_114 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_17_0_0_14);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_115 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_17_0_0_15);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_116 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_17_0_0_16_0_0_1);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_117 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_17_0_0_17_0_0_1);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_118 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_17_0_0_16_0_0_3);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_119 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_17_0_0_16_0_0_5);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_120 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_17_0_0_17_0_0_3);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_121 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_17_0_0_17_0_0_5);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_122 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_18_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_123 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_18_0_0_3);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_124 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_18_0_0_5);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_125 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_18_0_0_7);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_126 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_18_0_0_9);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_127 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_18_0_0_11);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_128 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_18_0_0_13);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_129 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_18_0_0_14);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_130 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_19_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_131 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_19_0_0_4);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_132 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_20_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_133 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_20_0_0_4);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_134 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_20_0_0_5_0_0_1);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_135 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_20_0_0_8);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_136 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_20_0_0_5_0_0_3);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_137 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_20_0_0_5_0_0_5);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_138 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_20_0_0_5_0_0_6_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_139 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_20_0_0_5_0_0_6_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_140 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_21_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_141 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_21_0_0_4);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_142 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_21_0_0_5_0_0_1);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_143 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_21_0_0_8);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_144 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_21_0_0_5_0_0_3);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_145 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_21_0_0_5_0_0_5);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_146 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_21_0_0_5_0_0_6_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_147 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_21_0_0_5_0_0_6_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_148 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_23_0_0_3);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_149 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_23_0_0_5);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_150 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_23_0_0_7);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_151 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_23_0_0_8_0_0_1);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_152 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_23_0_0_8_0_0_3);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_153 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_24_0_0_3);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_154 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_24_0_0_5);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_155 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_24_0_0_6);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_156 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_24_0_0_7);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_157 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_24_0_0_9);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_158 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_24_0_0_11);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_159 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_24_0_0_12);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_160 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_24_0_0_13_0_0_1);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_161 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_24_0_0_13_0_0_3);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_162 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_25_0_0_1);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_163 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_24_0_0_13_0_0_6);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_164 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_25_0_0_3);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_165 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_25_0_0_5_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_166 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_25_0_0_7);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_167 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_25_0_0_5_0_0_2);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_168 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_26_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_169 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_27_0_0_13_0_0_0);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_170 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_27_0_0_14);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_171 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_27_0_0_3);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_172 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_27_0_0_5);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_173 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_27_0_0_7);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_174 = new art.resource.artext.mopp.ArtextExpectedStructuralFeature(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_27_0_0_9);
	public final static art.resource.artext.IArtextExpectedElement TERMINAL_175 = new art.resource.artext.mopp.ArtextExpectedCsString(art.resource.artext.grammar.ArtextGrammarInformationProvider.ARTEXT_27_0_0_11);
	
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_0 = art.ArtPackage.eINSTANCE.getSystem().getEStructuralFeature(art.ArtPackage.SYSTEM__NODES);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_1 = art.ArtPackage.eINSTANCE.getSystem().getEStructuralFeature(art.ArtPackage.SYSTEM__SERVICES);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_2 = art.ArtPackage.eINSTANCE.getSystem().getEStructuralFeature(art.ArtPackage.SYSTEM__TYPES);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_3 = art.ArtPackage.eINSTANCE.getSystem().getEStructuralFeature(art.ArtPackage.SYSTEM__DATA_TYPES);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_4 = art.ArtPackage.eINSTANCE.getSystem().getEStructuralFeature(art.ArtPackage.SYSTEM__GROUPS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_5 = art.distrib.DistribPackage.eINSTANCE.getNode().getEStructuralFeature(art.distrib.DistribPackage.NODE__COMPONENTS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_6 = art.instance.InstancePackage.eINSTANCE.getComponentInstance().getEStructuralFeature(art.instance.InstancePackage.COMPONENT_INSTANCE__IMPLEM);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_7 = art.instance.InstancePackage.eINSTANCE.getComponentInstance().getEStructuralFeature(art.instance.InstancePackage.COMPONENT_INSTANCE__ATTRIBUTE);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_8 = art.instance.InstancePackage.eINSTANCE.getComponentInstance().getEStructuralFeature(art.instance.InstancePackage.COMPONENT_INSTANCE__BINDING);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_9 = art.instance.InstancePackage.eINSTANCE.getCompositeInstance().getEStructuralFeature(art.instance.InstancePackage.COMPOSITE_INSTANCE__DELEGATION);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_10 = art.instance.InstancePackage.eINSTANCE.getCompositeInstance().getEStructuralFeature(art.instance.InstancePackage.COMPOSITE_INSTANCE__SUB_COMPONENT);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_11 = art.instance.InstancePackage.eINSTANCE.getDictionaryValuedAttribute().getEStructuralFeature(art.instance.InstancePackage.DICTIONARY_VALUED_ATTRIBUTE__ENTRIES);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_12 = art.type.TypePackage.eINSTANCE.getComponentType().getEStructuralFeature(art.type.TypePackage.COMPONENT_TYPE__IMPLEM);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_13 = art.type.TypePackage.eINSTANCE.getComponentType().getEStructuralFeature(art.type.TypePackage.COMPONENT_TYPE__PORT);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_14 = art.type.TypePackage.eINSTANCE.getComponentType().getEStructuralFeature(art.type.TypePackage.COMPONENT_TYPE__ATTRIBUTE);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_15 = art.type.TypePackage.eINSTANCE.getOperation().getEStructuralFeature(art.type.TypePackage.OPERATION__INPUT);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_16 = art.type.TypePackage.eINSTANCE.getService().getEStructuralFeature(art.type.TypePackage.SERVICE__OPERATION);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_17 = art.type.TypePackage.eINSTANCE.getOperation().getEStructuralFeature(art.type.TypePackage.OPERATION__OUTPUT);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_18 = art.group.GroupPackage.eINSTANCE.getTypeGroup().getEStructuralFeature(art.group.GroupPackage.TYPE_GROUP__SUB_GROUPS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_19 = art.group.GroupPackage.eINSTANCE.getInstanceGroup().getEStructuralFeature(art.group.GroupPackage.INSTANCE_GROUP__SUB_GROUPS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_20 = art.type.TypePackage.eINSTANCE.getDictionary().getEStructuralFeature(art.type.TypePackage.DICTIONARY__KEYS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_21 = art.type.TypePackage.eINSTANCE.getPortCollection().getEStructuralFeature(art.type.TypePackage.PORT_COLLECTION__IDS);
	
	public final static org.eclipse.emf.ecore.EStructuralFeature[] EMPTY_FEATURE_ARRAY = new org.eclipse.emf.ecore.EStructuralFeature[0];
	
	public static void wire0() {
		TERMINAL_0.addFollower(TERMINAL_1, EMPTY_FEATURE_ARRAY);
		TERMINAL_1.addFollower(TERMINAL_2, EMPTY_FEATURE_ARRAY);
		TERMINAL_2.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_2.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_2.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_2.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_2.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_2.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_2.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_2.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_8.addFollower(TERMINAL_11, EMPTY_FEATURE_ARRAY);
		TERMINAL_11.addFollower(TERMINAL_12, EMPTY_FEATURE_ARRAY);
		TERMINAL_12.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_12.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_12.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_12.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_12.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_12.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_12.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_12.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_3.addFollower(TERMINAL_13, EMPTY_FEATURE_ARRAY);
		TERMINAL_13.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_13.addFollower(TERMINAL_15, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_16, EMPTY_FEATURE_ARRAY);
		TERMINAL_16.addFollower(TERMINAL_17, EMPTY_FEATURE_ARRAY);
		TERMINAL_17.addFollower(TERMINAL_15, EMPTY_FEATURE_ARRAY);
		TERMINAL_15.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_15.addFollower(TERMINAL_19, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_15.addFollower(TERMINAL_20, EMPTY_FEATURE_ARRAY);
		TERMINAL_20.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_20.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_20.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_20.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_20.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_20.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_20.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_20.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_18.addFollower(TERMINAL_21, EMPTY_FEATURE_ARRAY);
		TERMINAL_21.addFollower(TERMINAL_22, EMPTY_FEATURE_ARRAY);
		TERMINAL_22.addFollower(TERMINAL_23, EMPTY_FEATURE_ARRAY);
		TERMINAL_23.addFollower(TERMINAL_24, EMPTY_FEATURE_ARRAY);
		TERMINAL_24.addFollower(TERMINAL_25, EMPTY_FEATURE_ARRAY);
		TERMINAL_25.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_25.addFollower(TERMINAL_27, EMPTY_FEATURE_ARRAY);
		TERMINAL_26.addFollower(TERMINAL_28, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_26.addFollower(TERMINAL_29, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_27.addFollower(TERMINAL_30, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_27.addFollower(TERMINAL_31, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_27.addFollower(TERMINAL_32, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_27.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
		TERMINAL_33.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_33.addFollower(TERMINAL_19, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_33.addFollower(TERMINAL_20, EMPTY_FEATURE_ARRAY);
		TERMINAL_33.addFollower(TERMINAL_30, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_33.addFollower(TERMINAL_31, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_33.addFollower(TERMINAL_32, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_33.addFollower(TERMINAL_34, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, });
		TERMINAL_33.addFollower(TERMINAL_35, EMPTY_FEATURE_ARRAY);
		TERMINAL_19.addFollower(TERMINAL_36, EMPTY_FEATURE_ARRAY);
		TERMINAL_36.addFollower(TERMINAL_37, EMPTY_FEATURE_ARRAY);
		TERMINAL_37.addFollower(TERMINAL_38, EMPTY_FEATURE_ARRAY);
		TERMINAL_38.addFollower(TERMINAL_39, EMPTY_FEATURE_ARRAY);
		TERMINAL_39.addFollower(TERMINAL_40, EMPTY_FEATURE_ARRAY);
		TERMINAL_40.addFollower(TERMINAL_41, EMPTY_FEATURE_ARRAY);
		TERMINAL_40.addFollower(TERMINAL_42, EMPTY_FEATURE_ARRAY);
		TERMINAL_41.addFollower(TERMINAL_28, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_41.addFollower(TERMINAL_29, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_42.addFollower(TERMINAL_30, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_42.addFollower(TERMINAL_31, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_42.addFollower(TERMINAL_32, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_42.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_42.addFollower(TERMINAL_19, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_42.addFollower(TERMINAL_34, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, });
		TERMINAL_42.addFollower(TERMINAL_35, EMPTY_FEATURE_ARRAY);
		TERMINAL_35.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_35.addFollower(TERMINAL_19, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_35.addFollower(TERMINAL_20, EMPTY_FEATURE_ARRAY);
		TERMINAL_35.addFollower(TERMINAL_30, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_35.addFollower(TERMINAL_31, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_35.addFollower(TERMINAL_32, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_35.addFollower(TERMINAL_34, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, });
		TERMINAL_35.addFollower(TERMINAL_35, EMPTY_FEATURE_ARRAY);
		TERMINAL_32.addFollower(TERMINAL_43, EMPTY_FEATURE_ARRAY);
		TERMINAL_43.addFollower(TERMINAL_44, EMPTY_FEATURE_ARRAY);
		TERMINAL_44.addFollower(TERMINAL_45, EMPTY_FEATURE_ARRAY);
		TERMINAL_45.addFollower(TERMINAL_46, EMPTY_FEATURE_ARRAY);
		TERMINAL_46.addFollower(TERMINAL_47, EMPTY_FEATURE_ARRAY);
		TERMINAL_47.addFollower(TERMINAL_48, EMPTY_FEATURE_ARRAY);
		TERMINAL_47.addFollower(TERMINAL_30, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_47.addFollower(TERMINAL_31, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_47.addFollower(TERMINAL_32, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_47.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
		TERMINAL_47.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_47.addFollower(TERMINAL_19, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_47.addFollower(TERMINAL_34, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, });
		TERMINAL_47.addFollower(TERMINAL_35, EMPTY_FEATURE_ARRAY);
		TERMINAL_48.addFollower(TERMINAL_49, EMPTY_FEATURE_ARRAY);
		TERMINAL_49.addFollower(TERMINAL_50, EMPTY_FEATURE_ARRAY);
		TERMINAL_50.addFollower(TERMINAL_51, EMPTY_FEATURE_ARRAY);
		TERMINAL_51.addFollower(TERMINAL_52, EMPTY_FEATURE_ARRAY);
		TERMINAL_52.addFollower(TERMINAL_30, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_52.addFollower(TERMINAL_31, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_52.addFollower(TERMINAL_32, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_52.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
		TERMINAL_52.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_52.addFollower(TERMINAL_19, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_52.addFollower(TERMINAL_34, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, });
		TERMINAL_52.addFollower(TERMINAL_35, EMPTY_FEATURE_ARRAY);
		TERMINAL_34.addFollower(TERMINAL_53, EMPTY_FEATURE_ARRAY);
		TERMINAL_53.addFollower(TERMINAL_54, EMPTY_FEATURE_ARRAY);
		TERMINAL_54.addFollower(TERMINAL_55, EMPTY_FEATURE_ARRAY);
		TERMINAL_55.addFollower(TERMINAL_56, EMPTY_FEATURE_ARRAY);
		TERMINAL_56.addFollower(TERMINAL_57, EMPTY_FEATURE_ARRAY);
		TERMINAL_57.addFollower(TERMINAL_58, EMPTY_FEATURE_ARRAY);
		TERMINAL_57.addFollower(TERMINAL_30, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_57.addFollower(TERMINAL_31, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_57.addFollower(TERMINAL_32, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_57.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_57.addFollower(TERMINAL_19, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_57.addFollower(TERMINAL_34, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, });
		TERMINAL_57.addFollower(TERMINAL_35, EMPTY_FEATURE_ARRAY);
		TERMINAL_58.addFollower(TERMINAL_59, EMPTY_FEATURE_ARRAY);
		TERMINAL_59.addFollower(TERMINAL_60, EMPTY_FEATURE_ARRAY);
		TERMINAL_60.addFollower(TERMINAL_61, EMPTY_FEATURE_ARRAY);
		TERMINAL_61.addFollower(TERMINAL_62, EMPTY_FEATURE_ARRAY);
		TERMINAL_62.addFollower(TERMINAL_30, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_62.addFollower(TERMINAL_31, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_62.addFollower(TERMINAL_32, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_62.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_62.addFollower(TERMINAL_19, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_62.addFollower(TERMINAL_34, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, });
		TERMINAL_62.addFollower(TERMINAL_35, EMPTY_FEATURE_ARRAY);
		TERMINAL_30.addFollower(TERMINAL_63, EMPTY_FEATURE_ARRAY);
		TERMINAL_63.addFollower(TERMINAL_64, EMPTY_FEATURE_ARRAY);
		TERMINAL_64.addFollower(TERMINAL_30, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_64.addFollower(TERMINAL_31, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_64.addFollower(TERMINAL_32, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_64.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
		TERMINAL_64.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_64.addFollower(TERMINAL_19, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_64.addFollower(TERMINAL_34, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, });
		TERMINAL_64.addFollower(TERMINAL_35, EMPTY_FEATURE_ARRAY);
		TERMINAL_31.addFollower(TERMINAL_65, EMPTY_FEATURE_ARRAY);
		TERMINAL_65.addFollower(TERMINAL_66, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, });
		TERMINAL_65.addFollower(TERMINAL_67, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, });
		TERMINAL_65.addFollower(TERMINAL_30, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_65.addFollower(TERMINAL_31, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_65.addFollower(TERMINAL_32, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_65.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
		TERMINAL_65.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_65.addFollower(TERMINAL_19, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_65.addFollower(TERMINAL_34, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, });
		TERMINAL_65.addFollower(TERMINAL_35, EMPTY_FEATURE_ARRAY);
		TERMINAL_68.addFollower(TERMINAL_66, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, });
		TERMINAL_68.addFollower(TERMINAL_67, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_11, });
		TERMINAL_66.addFollower(TERMINAL_69, EMPTY_FEATURE_ARRAY);
		TERMINAL_69.addFollower(TERMINAL_70, EMPTY_FEATURE_ARRAY);
		TERMINAL_70.addFollower(TERMINAL_71, EMPTY_FEATURE_ARRAY);
		TERMINAL_71.addFollower(TERMINAL_72, EMPTY_FEATURE_ARRAY);
		TERMINAL_72.addFollower(TERMINAL_68, EMPTY_FEATURE_ARRAY);
		TERMINAL_72.addFollower(TERMINAL_30, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_72.addFollower(TERMINAL_31, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_72.addFollower(TERMINAL_32, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_72.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
		TERMINAL_72.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_72.addFollower(TERMINAL_19, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_72.addFollower(TERMINAL_34, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, });
		TERMINAL_72.addFollower(TERMINAL_35, EMPTY_FEATURE_ARRAY);
		TERMINAL_67.addFollower(TERMINAL_73, EMPTY_FEATURE_ARRAY);
		TERMINAL_73.addFollower(TERMINAL_74, EMPTY_FEATURE_ARRAY);
		TERMINAL_74.addFollower(TERMINAL_75, EMPTY_FEATURE_ARRAY);
		TERMINAL_75.addFollower(TERMINAL_76, EMPTY_FEATURE_ARRAY);
		TERMINAL_76.addFollower(TERMINAL_68, EMPTY_FEATURE_ARRAY);
		TERMINAL_76.addFollower(TERMINAL_30, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_76.addFollower(TERMINAL_31, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_76.addFollower(TERMINAL_32, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_76.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
		TERMINAL_76.addFollower(TERMINAL_18, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_76.addFollower(TERMINAL_19, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_10, });
		TERMINAL_76.addFollower(TERMINAL_34, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, });
		TERMINAL_76.addFollower(TERMINAL_35, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_77, EMPTY_FEATURE_ARRAY);
		TERMINAL_77.addFollower(TERMINAL_78, EMPTY_FEATURE_ARRAY);
		TERMINAL_77.addFollower(TERMINAL_79, EMPTY_FEATURE_ARRAY);
		TERMINAL_78.addFollower(TERMINAL_80, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_12, });
		TERMINAL_79.addFollower(TERMINAL_81, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_79.addFollower(TERMINAL_82, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_79.addFollower(TERMINAL_83, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_79.addFollower(TERMINAL_84, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_79.addFollower(TERMINAL_85, EMPTY_FEATURE_ARRAY);
		TERMINAL_85.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_85.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_85.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_85.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_85.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_85.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_85.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_85.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_7.addFollower(TERMINAL_86, EMPTY_FEATURE_ARRAY);
		TERMINAL_86.addFollower(TERMINAL_87, EMPTY_FEATURE_ARRAY);
		TERMINAL_86.addFollower(TERMINAL_88, EMPTY_FEATURE_ARRAY);
		TERMINAL_87.addFollower(TERMINAL_80, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_12, });
		TERMINAL_88.addFollower(TERMINAL_81, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_88.addFollower(TERMINAL_82, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_88.addFollower(TERMINAL_83, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_88.addFollower(TERMINAL_84, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_88.addFollower(TERMINAL_89, EMPTY_FEATURE_ARRAY);
		TERMINAL_89.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_89.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_89.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_89.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_89.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_89.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_89.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_89.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_90.addFollower(TERMINAL_91, EMPTY_FEATURE_ARRAY);
		TERMINAL_91.addFollower(TERMINAL_92, EMPTY_FEATURE_ARRAY);
		TERMINAL_92.addFollower(TERMINAL_93, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_92.addFollower(TERMINAL_94, EMPTY_FEATURE_ARRAY);
		TERMINAL_92.addFollower(TERMINAL_95, EMPTY_FEATURE_ARRAY);
		TERMINAL_94.addFollower(TERMINAL_93, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_15, });
		TERMINAL_95.addFollower(TERMINAL_96, EMPTY_FEATURE_ARRAY);
		TERMINAL_95.addFollower(TERMINAL_97, EMPTY_FEATURE_ARRAY);
		TERMINAL_95.addFollower(TERMINAL_90, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_16, });
		TERMINAL_95.addFollower(TERMINAL_98, EMPTY_FEATURE_ARRAY);
		TERMINAL_95.addFollower(TERMINAL_99, EMPTY_FEATURE_ARRAY);
		TERMINAL_96.addFollower(TERMINAL_93, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_17, });
		TERMINAL_97.addFollower(TERMINAL_93, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_17, });
		TERMINAL_93.addFollower(TERMINAL_100, EMPTY_FEATURE_ARRAY);
		TERMINAL_100.addFollower(TERMINAL_94, EMPTY_FEATURE_ARRAY);
		TERMINAL_100.addFollower(TERMINAL_95, EMPTY_FEATURE_ARRAY);
		TERMINAL_4.addFollower(TERMINAL_101, EMPTY_FEATURE_ARRAY);
		TERMINAL_101.addFollower(TERMINAL_102, EMPTY_FEATURE_ARRAY);
		TERMINAL_102.addFollower(TERMINAL_103, EMPTY_FEATURE_ARRAY);
		TERMINAL_103.addFollower(TERMINAL_90, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_16, });
		TERMINAL_103.addFollower(TERMINAL_98, EMPTY_FEATURE_ARRAY);
		TERMINAL_98.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_98.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_98.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_98.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_98.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_98.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_98.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_98.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_5.addFollower(TERMINAL_104, EMPTY_FEATURE_ARRAY);
		TERMINAL_104.addFollower(TERMINAL_105, EMPTY_FEATURE_ARRAY);
		TERMINAL_105.addFollower(TERMINAL_106, EMPTY_FEATURE_ARRAY);
		TERMINAL_106.addFollower(TERMINAL_90, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_16, });
		TERMINAL_106.addFollower(TERMINAL_99, EMPTY_FEATURE_ARRAY);
		TERMINAL_99.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_99.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_99.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_99.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_99.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_99.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_99.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_99.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_81.addFollower(TERMINAL_107, EMPTY_FEATURE_ARRAY);
		TERMINAL_107.addFollower(TERMINAL_108, EMPTY_FEATURE_ARRAY);
		TERMINAL_108.addFollower(TERMINAL_109, EMPTY_FEATURE_ARRAY);
		TERMINAL_109.addFollower(TERMINAL_110, EMPTY_FEATURE_ARRAY);
		TERMINAL_110.addFollower(TERMINAL_111, EMPTY_FEATURE_ARRAY);
		TERMINAL_111.addFollower(TERMINAL_112, EMPTY_FEATURE_ARRAY);
		TERMINAL_112.addFollower(TERMINAL_113, EMPTY_FEATURE_ARRAY);
		TERMINAL_113.addFollower(TERMINAL_114, EMPTY_FEATURE_ARRAY);
		TERMINAL_114.addFollower(TERMINAL_115, EMPTY_FEATURE_ARRAY);
		TERMINAL_115.addFollower(TERMINAL_116, EMPTY_FEATURE_ARRAY);
		TERMINAL_115.addFollower(TERMINAL_117, EMPTY_FEATURE_ARRAY);
		TERMINAL_115.addFollower(TERMINAL_81, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_115.addFollower(TERMINAL_82, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_115.addFollower(TERMINAL_83, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_115.addFollower(TERMINAL_84, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_115.addFollower(TERMINAL_85, EMPTY_FEATURE_ARRAY);
		TERMINAL_115.addFollower(TERMINAL_89, EMPTY_FEATURE_ARRAY);
		TERMINAL_116.addFollower(TERMINAL_118, EMPTY_FEATURE_ARRAY);
		TERMINAL_118.addFollower(TERMINAL_119, EMPTY_FEATURE_ARRAY);
		TERMINAL_119.addFollower(TERMINAL_117, EMPTY_FEATURE_ARRAY);
		TERMINAL_119.addFollower(TERMINAL_81, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_119.addFollower(TERMINAL_82, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_119.addFollower(TERMINAL_83, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_119.addFollower(TERMINAL_84, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_119.addFollower(TERMINAL_85, EMPTY_FEATURE_ARRAY);
		TERMINAL_119.addFollower(TERMINAL_89, EMPTY_FEATURE_ARRAY);
		TERMINAL_117.addFollower(TERMINAL_120, EMPTY_FEATURE_ARRAY);
		TERMINAL_120.addFollower(TERMINAL_121, EMPTY_FEATURE_ARRAY);
		TERMINAL_121.addFollower(TERMINAL_81, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_121.addFollower(TERMINAL_82, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_121.addFollower(TERMINAL_83, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_121.addFollower(TERMINAL_84, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_121.addFollower(TERMINAL_85, EMPTY_FEATURE_ARRAY);
		TERMINAL_121.addFollower(TERMINAL_89, EMPTY_FEATURE_ARRAY);
		TERMINAL_28.addFollower(TERMINAL_122, EMPTY_FEATURE_ARRAY);
		TERMINAL_122.addFollower(TERMINAL_123, EMPTY_FEATURE_ARRAY);
		TERMINAL_123.addFollower(TERMINAL_124, EMPTY_FEATURE_ARRAY);
		TERMINAL_124.addFollower(TERMINAL_125, EMPTY_FEATURE_ARRAY);
		TERMINAL_125.addFollower(TERMINAL_126, EMPTY_FEATURE_ARRAY);
		TERMINAL_126.addFollower(TERMINAL_127, EMPTY_FEATURE_ARRAY);
		TERMINAL_127.addFollower(TERMINAL_128, EMPTY_FEATURE_ARRAY);
		TERMINAL_128.addFollower(TERMINAL_129, EMPTY_FEATURE_ARRAY);
		TERMINAL_129.addFollower(TERMINAL_27, EMPTY_FEATURE_ARRAY);
		TERMINAL_129.addFollower(TERMINAL_42, EMPTY_FEATURE_ARRAY);
		TERMINAL_29.addFollower(TERMINAL_130, EMPTY_FEATURE_ARRAY);
		TERMINAL_130.addFollower(TERMINAL_131, EMPTY_FEATURE_ARRAY);
		TERMINAL_131.addFollower(TERMINAL_27, EMPTY_FEATURE_ARRAY);
		TERMINAL_131.addFollower(TERMINAL_42, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_132, EMPTY_FEATURE_ARRAY);
		TERMINAL_132.addFollower(TERMINAL_133, EMPTY_FEATURE_ARRAY);
		TERMINAL_133.addFollower(TERMINAL_134, EMPTY_FEATURE_ARRAY);
		TERMINAL_133.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_18, });
		TERMINAL_133.addFollower(TERMINAL_135, EMPTY_FEATURE_ARRAY);
		TERMINAL_134.addFollower(TERMINAL_136, EMPTY_FEATURE_ARRAY);
		TERMINAL_136.addFollower(TERMINAL_137, EMPTY_FEATURE_ARRAY);
		TERMINAL_137.addFollower(TERMINAL_138, EMPTY_FEATURE_ARRAY);
		TERMINAL_137.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_18, });
		TERMINAL_137.addFollower(TERMINAL_135, EMPTY_FEATURE_ARRAY);
		TERMINAL_138.addFollower(TERMINAL_139, EMPTY_FEATURE_ARRAY);
		TERMINAL_139.addFollower(TERMINAL_138, EMPTY_FEATURE_ARRAY);
		TERMINAL_139.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_18, });
		TERMINAL_139.addFollower(TERMINAL_135, EMPTY_FEATURE_ARRAY);
		TERMINAL_135.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_135.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_135.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_135.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_135.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_135.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_135.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_135.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_135.addFollower(TERMINAL_135, EMPTY_FEATURE_ARRAY);
		TERMINAL_10.addFollower(TERMINAL_140, EMPTY_FEATURE_ARRAY);
		TERMINAL_140.addFollower(TERMINAL_141, EMPTY_FEATURE_ARRAY);
		TERMINAL_141.addFollower(TERMINAL_142, EMPTY_FEATURE_ARRAY);
		TERMINAL_141.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_19, });
		TERMINAL_141.addFollower(TERMINAL_143, EMPTY_FEATURE_ARRAY);
		TERMINAL_142.addFollower(TERMINAL_144, EMPTY_FEATURE_ARRAY);
		TERMINAL_144.addFollower(TERMINAL_145, EMPTY_FEATURE_ARRAY);
		TERMINAL_145.addFollower(TERMINAL_146, EMPTY_FEATURE_ARRAY);
		TERMINAL_145.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_19, });
		TERMINAL_145.addFollower(TERMINAL_143, EMPTY_FEATURE_ARRAY);
		TERMINAL_146.addFollower(TERMINAL_147, EMPTY_FEATURE_ARRAY);
		TERMINAL_147.addFollower(TERMINAL_146, EMPTY_FEATURE_ARRAY);
		TERMINAL_147.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_19, });
		TERMINAL_147.addFollower(TERMINAL_143, EMPTY_FEATURE_ARRAY);
		TERMINAL_143.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_0, });
		TERMINAL_143.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_143.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_143.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_143.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_143.addFollower(TERMINAL_8, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_143.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_143.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_143.addFollower(TERMINAL_143, EMPTY_FEATURE_ARRAY);
		TERMINAL_80.addFollower(TERMINAL_79, EMPTY_FEATURE_ARRAY);
		TERMINAL_80.addFollower(TERMINAL_88, EMPTY_FEATURE_ARRAY);
		TERMINAL_83.addFollower(TERMINAL_148, EMPTY_FEATURE_ARRAY);
		TERMINAL_148.addFollower(TERMINAL_149, EMPTY_FEATURE_ARRAY);
		TERMINAL_149.addFollower(TERMINAL_150, EMPTY_FEATURE_ARRAY);
		TERMINAL_150.addFollower(TERMINAL_151, EMPTY_FEATURE_ARRAY);
		TERMINAL_150.addFollower(TERMINAL_81, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_150.addFollower(TERMINAL_82, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_150.addFollower(TERMINAL_83, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_150.addFollower(TERMINAL_84, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_150.addFollower(TERMINAL_85, EMPTY_FEATURE_ARRAY);
		TERMINAL_150.addFollower(TERMINAL_89, EMPTY_FEATURE_ARRAY);
		TERMINAL_151.addFollower(TERMINAL_152, EMPTY_FEATURE_ARRAY);
		TERMINAL_152.addFollower(TERMINAL_81, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_152.addFollower(TERMINAL_82, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_152.addFollower(TERMINAL_83, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_152.addFollower(TERMINAL_84, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_152.addFollower(TERMINAL_85, EMPTY_FEATURE_ARRAY);
		TERMINAL_152.addFollower(TERMINAL_89, EMPTY_FEATURE_ARRAY);
		TERMINAL_84.addFollower(TERMINAL_153, EMPTY_FEATURE_ARRAY);
		TERMINAL_153.addFollower(TERMINAL_154, EMPTY_FEATURE_ARRAY);
		TERMINAL_154.addFollower(TERMINAL_155, EMPTY_FEATURE_ARRAY);
		TERMINAL_155.addFollower(TERMINAL_156, EMPTY_FEATURE_ARRAY);
		TERMINAL_156.addFollower(TERMINAL_157, EMPTY_FEATURE_ARRAY);
		TERMINAL_157.addFollower(TERMINAL_158, EMPTY_FEATURE_ARRAY);
		TERMINAL_158.addFollower(TERMINAL_159, EMPTY_FEATURE_ARRAY);
		TERMINAL_159.addFollower(TERMINAL_160, EMPTY_FEATURE_ARRAY);
		TERMINAL_159.addFollower(TERMINAL_81, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_159.addFollower(TERMINAL_82, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_159.addFollower(TERMINAL_83, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_159.addFollower(TERMINAL_84, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_159.addFollower(TERMINAL_85, EMPTY_FEATURE_ARRAY);
		TERMINAL_159.addFollower(TERMINAL_89, EMPTY_FEATURE_ARRAY);
		TERMINAL_160.addFollower(TERMINAL_161, EMPTY_FEATURE_ARRAY);
		TERMINAL_161.addFollower(TERMINAL_162, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_20, });
		TERMINAL_161.addFollower(TERMINAL_163, EMPTY_FEATURE_ARRAY);
		TERMINAL_163.addFollower(TERMINAL_81, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_163.addFollower(TERMINAL_82, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_163.addFollower(TERMINAL_83, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_163.addFollower(TERMINAL_84, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_163.addFollower(TERMINAL_85, EMPTY_FEATURE_ARRAY);
		TERMINAL_163.addFollower(TERMINAL_89, EMPTY_FEATURE_ARRAY);
		TERMINAL_162.addFollower(TERMINAL_164, EMPTY_FEATURE_ARRAY);
		TERMINAL_164.addFollower(TERMINAL_165, EMPTY_FEATURE_ARRAY);
		TERMINAL_164.addFollower(TERMINAL_166, EMPTY_FEATURE_ARRAY);
		TERMINAL_165.addFollower(TERMINAL_167, EMPTY_FEATURE_ARRAY);
		TERMINAL_167.addFollower(TERMINAL_166, EMPTY_FEATURE_ARRAY);
		TERMINAL_166.addFollower(TERMINAL_162, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_20, });
		TERMINAL_166.addFollower(TERMINAL_163, EMPTY_FEATURE_ARRAY);
		TERMINAL_168.addFollower(TERMINAL_169, EMPTY_FEATURE_ARRAY);
		TERMINAL_168.addFollower(TERMINAL_170, EMPTY_FEATURE_ARRAY);
		TERMINAL_82.addFollower(TERMINAL_171, EMPTY_FEATURE_ARRAY);
		TERMINAL_171.addFollower(TERMINAL_172, EMPTY_FEATURE_ARRAY);
		TERMINAL_172.addFollower(TERMINAL_173, EMPTY_FEATURE_ARRAY);
		TERMINAL_173.addFollower(TERMINAL_174, EMPTY_FEATURE_ARRAY);
		TERMINAL_174.addFollower(TERMINAL_175, EMPTY_FEATURE_ARRAY);
		TERMINAL_175.addFollower(TERMINAL_168, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_21, });
		TERMINAL_169.addFollower(TERMINAL_168, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_21, });
		TERMINAL_170.addFollower(TERMINAL_81, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_170.addFollower(TERMINAL_82, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_13, });
		TERMINAL_170.addFollower(TERMINAL_83, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_170.addFollower(TERMINAL_84, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_14, });
		TERMINAL_170.addFollower(TERMINAL_85, EMPTY_FEATURE_ARRAY);
		TERMINAL_170.addFollower(TERMINAL_89, EMPTY_FEATURE_ARRAY);
	}
	// wire the terminals
	static {
		wire0();
	}
}
