global java.util.List list;
global java.util.Map uniqueobjects;
rule "RulesName"
	 when 
$s2: art.type.Service(name == "org.slf4j.Logger")
$s3: art.type.Port(role == "client",service == $s2)
$s4: art.type.PrimitiveType(port contains $s3)
$s5: art.instance.PrimitiveInstance(type == $s4)
$s1: art.instance.CompositeInstance(subComponent contains $s5)
$s0: art.System(root == $s1)
then
 	 java.util.HashMap m = new java.util.HashMap();
m.put("systemRole",$s0);
m.put("rootRole",$s1);
m.put("loggerClientRole",$s5);
m.put("loggerClientPortRole",$s3);
	 list.add(m);
 art.System s0 = art.ArtFactory.eINSTANCE.createSystem();
art.instance.CompositeInstance s1 = art.instance.InstanceFactory.eINSTANCE.createCompositeInstance();
art.instance.PrimitiveInstance s2 = (art.instance.PrimitiveInstance) uniqueobjects.get("s2");
if ( s2 == null){
s2 = art.instance.InstanceFactory.eINSTANCE.createPrimitiveInstance();
uniqueobjects.put("s2",s2);
}
art.implem.OSGiComponent s3 = (art.implem.OSGiComponent) uniqueobjects.get("s3");
if ( s3 == null){
s3 = art.implem.ImplemFactory.eINSTANCE.createOSGiComponent();
uniqueobjects.put("s3",s3);
}
art.instance.PrimitiveInstance s4 = art.instance.InstanceFactory.eINSTANCE.createPrimitiveInstance();
art.instance.TransmissionBinding s5 = art.instance.InstanceFactory.eINSTANCE.createTransmissionBinding();
art.type.FunctionalService s6 = (art.type.FunctionalService) uniqueobjects.get("s6");
if ( s6 == null){
s6 = art.type.TypeFactory.eINSTANCE.createFunctionalService();
uniqueobjects.put("s6",s6);
}
art.type.PrimitiveType s7 = (art.type.PrimitiveType) uniqueobjects.get("s7");
if ( s7 == null){
s7 = art.type.TypeFactory.eINSTANCE.createPrimitiveType();
uniqueobjects.put("s7",s7);
}
art.type.Port s8 = (art.type.Port) uniqueobjects.get("s8");
if ( s8 == null){
s8 = art.type.TypeFactory.eINSTANCE.createPort();
uniqueobjects.put("s8",s8);
}
s0.setRoot(s1);
s0.getServices().add(s6);
s0.getTypes().add(s7);
s1.getSubComponent().add(s2);
s1.getSubComponent().add(s4);
s2.setName("DefaultLogger");
s2.setType(s7);
s2.setSuperComponent(s1);
s2.setImplem(s3);
s3.setImplementingClass("eu.diva.tis.log.DefaultLogger");
s4.setName("FakeLoggerClient");
s4.setSuperComponent(s1);
s4.getBinding().add(s5);
s5.setId("DefaultLogger");
s5.setServer(s8);
s5.setServerInstance(s2);
s6.setName("org.slf4j.Logger");
s7.setName("eu.diva.tis.log");
s7.getPort().add(s8);
s8.setIsOptional(false);
s8.setLower(1);
s8.setUpper(1);
s8.setRole("server");
s8.setName("logger");
s8.setService(s6);
$s0.getServices().add((art.type.Service)  uniqueobjects.get("s6"));
$s0.getTypes().add((art.type.ComponentType)  uniqueobjects.get("s7"));
$s1.getSubComponent().add((art.instance.ComponentInstance)  uniqueobjects.get("s2"));
s5.setClient($s3);
$s5.getBinding().add(s5);
end