global java.util.List list;
global java.util.Map uniqueobjects;
rule "RulesName"
	 when 
$s1: art.instance.CompositeInstance()
$s0: art.System(root == $s1)
then
 	 java.util.HashMap m = new java.util.HashMap();
m.put("systemRole",$s0);
m.put("rootRole",$s1);
	 list.add(m);
 art.System s0 = art.ArtFactory.eINSTANCE.createSystem();
art.instance.CompositeInstance s1 = art.instance.InstanceFactory.eINSTANCE.createCompositeInstance();
art.instance.PrimitiveInstance s2 = (art.instance.PrimitiveInstance) uniqueobjects.get("s2");
if ( s2 == null){
s2 = art.instance.InstanceFactory.eINSTANCE.createPrimitiveInstance();
uniqueobjects.put("s2",s2);
}
art.implem.OSGiComponent s3 = (art.implem.OSGiComponent) uniqueobjects.get("s3");
if ( s3 == null){
s3 = art.implem.ImplemFactory.eINSTANCE.createOSGiComponent();
uniqueobjects.put("s3",s3);
}
art.type.FunctionalService s4 = (art.type.FunctionalService) uniqueobjects.get("s4");
if ( s4 == null){
s4 = art.type.TypeFactory.eINSTANCE.createFunctionalService();
uniqueobjects.put("s4",s4);
}
art.type.FunctionalService s5 = (art.type.FunctionalService) uniqueobjects.get("s5");
if ( s5 == null){
s5 = art.type.TypeFactory.eINSTANCE.createFunctionalService();
uniqueobjects.put("s5",s5);
}
art.type.PrimitiveType s6 = (art.type.PrimitiveType) uniqueobjects.get("s6");
if ( s6 == null){
s6 = art.type.TypeFactory.eINSTANCE.createPrimitiveType();
uniqueobjects.put("s6",s6);
}
art.type.Port s7 = (art.type.Port) uniqueobjects.get("s7");
if ( s7 == null){
s7 = art.type.TypeFactory.eINSTANCE.createPort();
uniqueobjects.put("s7",s7);
}
art.type.Port s8 = (art.type.Port) uniqueobjects.get("s8");
if ( s8 == null){
s8 = art.type.TypeFactory.eINSTANCE.createPort();
uniqueobjects.put("s8",s8);
}
s2.setName("FireDeployer");
s2.setType(s6);
s2.setSuperComponent(s1);
s2.setImplem(s3);
s4.setName("eu.diva.tis.api.context.SensorDeployer");
s5.setName("org.slf4j.Logger");
s6.setName("eu.diva.tis.context.sensor.deployer");
s6.getPort().add(s7);
s6.getPort().add(s8);
s7.setLower(1);
s7.setUpper(1);
s7.setRole("server");
s7.setName("deployer");
s7.setService(s4);
s8.setLower(1);
s8.setUpper(1);
s8.setRole("client");
s8.setName("logger");
s8.setService(s5);
$s0.getServices().add((art.type.Service)  uniqueobjects.get("s4"));
$s0.getServices().add((art.type.Service)  uniqueobjects.get("s5"));
$s0.getTypes().add((art.type.ComponentType)  uniqueobjects.get("s6"));
$s1.getSubComponent().add((art.instance.ComponentInstance)  uniqueobjects.get("s2"));
end