/* $Id: Comp_callResult_test003__Main__main_Runner.java,v 1.1 2007-11-19 09:44:45 cfaucher Exp $
 * This file has been generated by the compiler of Kermeta (http://www.kermeta.org)
 */

package comp_callResult_test003.runner;

import comp_callResult_test003.Comp_callResult_test003Factory;

/**
 * A Stub of a Java Application Runner for a Kermeta runnable method
 *
 * @generated
 */
public class Comp_callResult_test003__Main__main_Runner {

	public static void main(String[] args) {
		Comp_callResult_test003Factory.eINSTANCE.createMain().main();
	}

}
