package fr.irisa.triskell.kermeta.compilo.scala.rich

import fr.irisa.triskell.kermeta.compilo.scala.rich._
import fr.irisa.triskell.kermeta.compilo.scala.rich.richAspect._
import scala.collection.JavaConversions._
import fr.irisa.triskell.kermeta.compilo.scala._
import fr.irisa.triskell.kermeta.language._
import fr.irisa.triskell.kermeta.language.structure._ 
import fr.irisa.triskell.kermeta.language.structure.impl._
import fr.irisa.triskell.kermeta.language.behavior._
import fr.irisa.triskell.kermeta.language.behavior.impl._


class AssignementView extends AssignmentImpl with GenerateScalaCodeAspect
class ModelingUnitView extends ModelingUnitImpl with ModelingUnitAspect
class PackageView extends PackageImpl with PackageAspect
class ClassView extends fr.irisa.triskell.kermeta.language.structure.impl.ClassImpl with GenerateScalaCodeAspect
class ClassDefinitionView extends ClassDefinitionImpl with ClassDefinitionAspect
class BlockView extends BlockImpl with GenerateScalaCodeAspect
class PrimitiveTypeView extends PrimitiveTypeImpl with GenerateScalaCodeAspect
class CallResultView extends CallResultImpl with GenerateScalaCodeAspect
class ObjectTypeVariableView extends ObjectTypeVariableImpl with GenerateScalaCodeAspect
class EnumerationView extends EnumerationImpl with GenerateScalaCodeAspect
class PropertyView extends PropertyImpl with GenerateScalaCodeAspect
class TypeReferenceView extends TypeReferenceImpl with GenerateScalaCodeAspect
class OperationView extends OperationImpl with GenerateScalaCodeAspect
class TypeLiteralView extends TypeLiteralImpl with GenerateScalaCodeAspect
class BooleanLiteralView extends BooleanLiteralImpl with GenerateScalaCodeAspect
class CallValueView extends CallValueImpl with GenerateScalaCodeAspect
class StringLiteralView extends StringLiteralImpl with GenerateScalaCodeAspect
class VoidLiteralView extends VoidLiteralImpl with GenerateScalaCodeAspect
class CallSuperOperationView extends CallSuperOperationImpl with GenerateScalaCodeAspect
class CallVariableView extends CallVariableImpl with GenerateScalaCodeAspect
class CallFeatureView extends CallFeatureImpl with GenerateScalaCodeAspect
class IntegerLiteralView extends IntegerLiteralImpl with GenerateScalaCodeAspect
class DataTypeView extends DataTypeImpl with GenerateScalaCodeAspect
class SelfExpressionView extends SelfExpressionImpl with GenerateScalaCodeAspect
class VariableDeclView extends VariableDeclImpl with GenerateScalaCodeAspect
class CallExpressionView extends CallExpressionImpl with GenerateScalaCodeAspect
class LambdaExpressionView extends LambdaExpressionImpl with GenerateScalaCodeAspect
class RaiseView extends RaiseImpl with GenerateScalaCodeAspect
class LoopView extends LoopImpl with GenerateScalaCodeAspect
class ConditionalView extends ConditionalImpl with GenerateScalaCodeAspect
class ObjectView extends fr.irisa.triskell.kermeta.language.structure.impl.ObjectImpl with GenerateScalaCodeAspect
class EnumerationLiteralView extends EnumerationLiteralImpl with GenerateScalaCodeAspect
class VoidTypeView extends VoidTypeImpl with GenerateScalaCodeAspect
class TypeVariableBindingView extends TypeVariableBindingImpl with GenerateScalaCodeAspect
class UsingView extends UsingImpl with GenerateScalaCodeAspect
class LambdaParameterView extends LambdaParameterImpl with GenerateScalaCodeAspect
class ExpressionView extends ExpressionImpl with GenerateScalaCodeAspect
//class TypeView extends TypeImpl with GenerateScalaCodeAspect


