/**
 * <copyright>
 * </copyright>
 *
 * $Id: ClassValidator.java,v 1.1 2008-07-02 09:43:41 ftanguy Exp $
 */
package kermeta.language.structure.validation;

import kermeta.language.structure.ClassDefinition;
import kermeta.language.structure.Operation;
import kermeta.language.structure.Property;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link kermeta.language.structure.Class}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClassValidator {
	boolean validate();

	boolean validateOwnedOperation(EList<Operation> value);
	boolean validateSuperClass(EList<kermeta.language.structure.Class> value);
	boolean validateIsAbstract(boolean value);
	boolean validateName(String value);
	boolean validateClassDefinition(ClassDefinition value);
	boolean validateOwnedAttribute(EList<Property> value);
}
