/**
 * <copyright>
 * </copyright>
 *
 * $Id: ConstraintValidator.java,v 1.1 2008-07-02 09:43:41 ftanguy Exp $
 */
package kermeta.language.structure.validation;

import kermeta.language.behavior.Expression;

import kermeta.language.structure.ClassDefinition;
import kermeta.language.structure.ConstraintLanguage;
import kermeta.language.structure.ConstraintType;
import kermeta.language.structure.Operation;

/**
 * A sample validator interface for {@link kermeta.language.structure.Constraint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConstraintValidator {
	boolean validate();

	boolean validateBody(Expression value);
	boolean validatePreOwner(Operation value);
	boolean validateStereotype(ConstraintType value);
	boolean validatePostOwner(Operation value);
	boolean validateLanguage(ConstraintLanguage value);
	boolean validateInvOwner(ClassDefinition value);
}
