/**
 * Copyright: IRISA/INRIA/Universite de Rennes 1 - License: EPL - Web site: http://www.kermeta.org
 *
 * $Id: EPackageValidator.java,v 1.1 2008-06-24 14:23:22 cfaucher Exp $
 */
package ecore.validation;

import ecore.EClassifier;
import ecore.EFactory;
import ecore.EPackage;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ecore.EPackage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EPackageValidator
{
  boolean validate();

  boolean validateNsURI(String value);
  boolean validateESubpackages(EList<EPackage> value);
  boolean validateESuperPackage(EPackage value);
  boolean validateNsPrefix(String value);
  boolean validateEClassifiers(EList<EClassifier> value);
  boolean validateEFactoryInstance(EFactory value);
}
