/**
 * Copyright: IRISA/INRIA/Universite de Rennes 1 - License: EPL - Web site: http://www.kermeta.org
 *
 * $Id: EStructuralFeatureValidator.java,v 1.1 2008-06-24 14:23:23 cfaucher Exp $
 */
package ecore.validation;

import ecore.EClass;

/**
 * A sample validator interface for {@link ecore.EStructuralFeature}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EStructuralFeatureValidator
{
  boolean validate();

  boolean validate_volatile(boolean value);
  boolean validateEContainingClass(EClass value);
  boolean validateDefaultValueLiteral(String value);
  boolean validate_transient(boolean value);
  boolean validateUnsettable(boolean value);
  boolean validateDerived(boolean value);
  boolean validateDefaultValue(Object value);
  boolean validateChangeable(boolean value);
}
