<?xml version="1.0" encoding="ISO-8859-1"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uml2kmClassDiagram" nsURI="http://uml2kmClassDiagram" nsPrefix="uml2kmClassDiagram">
  <eAnnotations source="http://www.topcased.org/uuid">
    <details key="uuid" value="11435483365650"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="KmModel">
    <eAnnotations source="http://www.topcased.org/uuid">
      <details key="uuid" value="114354899157577"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UmlModel">
    <eAnnotations source="http://www.topcased.org/uuid">
      <details key="uuid" value="114354899157779"/>
    </eAnnotations>
  </eClassifiers>
  <eSubpackages name="elements">
    <eAnnotations source="http://www.topcased.org/uuid">
      <details key="uuid" value="114355601350212"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="UmlClass" eSuperTypes="//visitors/UmlElement">
      <eAnnotations source="visitor.visit(this)">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="114354833657917"/>
        </eAnnotations>
      </eAnnotations>
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="114354833657816"/>
      </eAnnotations>
      <eOperations name="accept">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="114354833657918"/>
        </eAnnotations>
        <eParameters name="visitor" eType="//visitors/Visitor">
          <eAnnotations source="http://www.topcased.org/uuid">
            <details key="uuid" value="114354833658019"/>
          </eAnnotations>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UmlAssociation" eSuperTypes="//visitors/UmlElement">
      <eAnnotations source="visitor.visit(this)">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="114354833658221"/>
        </eAnnotations>
      </eAnnotations>
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="114354833658120"/>
      </eAnnotations>
      <eOperations name="accept">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="114354833658422"/>
        </eAnnotations>
        <eParameters name="visitor" eType="//visitors/Visitor">
          <eAnnotations source="http://www.topcased.org/uuid">
            <details key="uuid" value="114354833658523"/>
          </eAnnotations>
        </eParameters>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="visitors">
    <eAnnotations source="http://www.topcased.org/uuid">
      <details key="uuid" value="114355601350337"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Visitor" instanceClassName="" abstract="true">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="11435483365681"/>
      </eAnnotations>
      <eOperations name="visitUmlClass">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="11435483365692"/>
        </eAnnotations>
        <eParameters name="umlElement" eType="//elements/UmlClass">
          <eAnnotations source="http://www.topcased.org/uuid">
            <details key="uuid" value="11435486913019"/>
          </eAnnotations>
        </eParameters>
      </eOperations>
      <eOperations name="visitUmlAssociation">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="11435483365704"/>
        </eAnnotations>
        <eParameters name="umlElement" eType="//elements/UmlAssociation">
          <eAnnotations source="http://www.topcased.org/uuid">
            <details key="uuid" value="114354869130213"/>
          </eAnnotations>
        </eParameters>
      </eOperations>
      <eOperations name="visit[..]">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="11435483365716"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inputModel" lowerBound="1" eType="//UmlModel">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="114354899157321"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Uml2KmTranslator" eSuperTypes="//visitors/Visitor">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="11435483365727"/>
      </eAnnotations>
      <eOperations name="visitUmlClass">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="11435483365738"/>
        </eAnnotations>
        <eParameters name="umlElement" eType="//elements/UmlClass">
          <eAnnotations source="http://www.topcased.org/uuid">
            <details key="uuid" value="114354869130323"/>
          </eAnnotations>
        </eParameters>
      </eOperations>
      <eOperations name="visitUmlAssociation">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="114354833657410"/>
        </eAnnotations>
        <eParameters name="umlElement" eType="//elements/UmlAssociation">
          <eAnnotations source="http://www.topcased.org/uuid">
            <details key="uuid" value="114354869130327"/>
          </eAnnotations>
        </eParameters>
      </eOperations>
      <eOperations name="visit[..]">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="114354833657512"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outputModel" lowerBound="1" eType="//KmModel">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="114354899157440"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UmlElement" abstract="true">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="114354833657513"/>
      </eAnnotations>
      <eAnnotations source="abstraction of all UML2 models elements">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="114354843012842"/>
        </eAnnotations>
      </eAnnotations>
      <eOperations name="accept">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="114354833657614"/>
        </eAnnotations>
        <eParameters name="visitor" eType="//visitors/Visitor">
          <eAnnotations source="http://www.topcased.org/uuid">
            <details key="uuid" value="114354833657715"/>
          </eAnnotations>
        </eParameters>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="builders">
    <eAnnotations source="http://www.topcased.org/uuid">
      <details key="uuid" value="114355601350492"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Builder" abstract="true">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="114355214442090"/>
      </eAnnotations>
      <eOperations name="buildClass">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="1143556776363102"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="buildAssociation">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="1143556776364103"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="build[..]">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="1143556776365104"/>
        </eAnnotations>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="KmBuilder" eSuperTypes="//builders/Builder">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="1143556944841111"/>
      </eAnnotations>
      <eOperations name="buildClass">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="1143556944842112"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="buildAssociation">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="1143556944843113"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="build[..]">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="1143556944844114"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="product" lowerBound="1" eType="//KmModel">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="1143557422571123"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Director">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="1143557252865123"/>
      </eAnnotations>
      <eOperations name="construct">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="1143557252866124"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="builder" lowerBound="1" eType="//builders/Builder">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="1143557252867126"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UmlBuilder" eSuperTypes="//builders/Builder">
      <eAnnotations source="http://www.topcased.org/uuid">
        <details key="uuid" value="1143557969399132"/>
      </eAnnotations>
      <eAnnotations source="for reverse engineering (not yet implemented)">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="1143558173418135"/>
        </eAnnotations>
      </eAnnotations>
      <eOperations name="buildClass">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="1143557969402133"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="buildAssociation">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="1143557969402134"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="build[..]">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="1143557969403135"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="product" lowerBound="1" eType="//UmlModel">
        <eAnnotations source="http://www.topcased.org/uuid">
          <details key="uuid" value="1143557969404136"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
