<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test_MM_with_no_containment_tree" nsURI="050_MM_with_no_containment_tree.ecore" nsPrefix="test_MM_with_no_containment_tree">
  <eClassifiers xsi:type="ecore:EClass" name="C1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aC2" upperBound="-1" eType="//C2"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="C2">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aC3" eType="//C3"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="C3">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aC1" upperBound="-1" eType="//C1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="C1s" upperBound="-1" eType="//C1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="C2s" upperBound="-1" eType="//C2" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="C3s" upperBound="-1" eType="//C3" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="//String"/>
  </eClassifiers>
</ecore:EPackage>
