<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MDK" nsURI="platform:/resource/TransfoAadl/Test/TestEnum.kmt" nsPrefix="root_package">
  <eClassifiers xsi:type="ecore:EEnum" name="AccesVariableEnumeration">
    <eLiterals name="accPublic"/>
    <eLiterals name="accPrivate" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumTest">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="a" eType="//AccesVariableEnumeration"/>
  </eClassifiers>
</ecore:EPackage>
