<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EAnnotation source="ModelingUnit">
    <details key="require" value="kermeta|"/>
    <details key="using" value="comptest2|kermeta::standard|"/>
  </ecore:EAnnotation>
  <ecore:EAnnotation source="kermeta">
    <details key="mainClass" value="comptest2::Main"/>
  </ecore:EAnnotation>
  <ecore:EAnnotation source="kermeta">
    <details key="mainOperation" value="main"/>
  </ecore:EAnnotation>
  <ecore:EPackage name="comptest2" nsURI="http://comptest2" nsPrefix="">
    <eClassifiers xsi:type="ecore:EClass" name="Main">
      <eOperations name="main">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="{&#xA;&#x9;comptest2.ClassWithBehavior aPrinter /*VariableDecl with new*/  = comptest2.Comptest2Factory.eINSTANCE.createClassWithBehavior();&#xA;&#xA;&#x9;/*Block3*/ /*CallVariable*/ aPrinter. /*Block1*/&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;&#x9; print /*Block2*/ ();&#xA;&#xA;&#x9;/*Block3*/ /*Block3*/ /*CallVariable*/ aPrinter. /*Block1*/&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;&#x9; attr1(). /*Block1*/&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;&#x9; toString /*Block2*/ ();&#xA;&#xA;&#x9;comptest2.ClassWithBehavior aPrinter2 = null;&#xA;&#xA;&#x9;comptest2.ClassWithBehavior aPrinter3 /*VariableDecl with new*/  = comptest2.Comptest2Factory.eINSTANCE.createClassWithBehavior();&#xA;}"/>
        </eAnnotations>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ClassWithBehavior">
      <eOperations name="print">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="{&#xA;&#x9;java.lang.String text1 /*VariableDecl with new*/  = null;&#xA;&#xA;&#x9;java.lang.String text2 = null;&#xA;&#xA;&#x9;/*CallVariable*/ text2 = &quot;World&quot;;&#xA;&#xA;&#x9;/*Block3*/ /*CallVariable*/ System.out. /*Block1_*/ println /*Block2*/ (/*Block3*/ /*CallVariable*/ text1. /*Block1*/&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;&#x9; plus);&#xA;&#xA;&#x9;if( (1) == (1) /*Block1*/&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;&#x9; equals) {&#xA;{&#xA;&#x9;/*Block3*/ /*CallVariable*/ System.out. /*Block1_*/ println /*Block2*/ (&quot;conditional&quot;);&#xA;}&#xA;}&#xA;}"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="attr1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InheritedClassWithBehavior" eSuperTypes="#/3/ClassWithBehavior #/3/EmptyClass">
      <eOperations name="test" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="&#xA;java.lang.String result = null;&#xA;{&#xA;&#x9;//TODO Assignment[kermeta::language::behavior::Assignment:133545]&#xA;getAttr1&#xA;&#xA;&#x9;java.lang.String _return = null;&#xA;&#xA;&#x9;/*CallVariable*/ _return =  /*Block1*/&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;&#x9; attr1;&#xA;&#xA;&#x9;result = /*CallVariable*/ _return;&#xA;}&#xA;return result;&#xA;"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="print">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="{&#xA;&#x9;//IP content of the current CallSuperOperation&#xA;super&#xA;}"/>
        </eAnnotations>
        <eAnnotations source="kermeta">
          <details key="superOperation" value="comptest2::ClassWithBehavior"/>
        </eAnnotations>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EmptyClass"/>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterizedEmptyClass">
      <eTypeParameters name="A"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterizedClass">
      <eTypeParameters name="B"/>
      <eOperations name="test2">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="body" value="{}"/>
        </eAnnotations>
        <eTypeParameters name="B"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attr1">
        <eGenericType eClassifier="#/3/ParameterizedClass">
          <eTypeArguments/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testString" eType="#/3/TestString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="TestString" instanceClassName="java.lang.String"/>
  </ecore:EPackage>
</xmi:XMI>
