<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EAnnotation source="ModelingUnit">
    <details key="require" value="kermeta|"/>
    <details key="using" value="root_package|kermeta::standard|"/>
  </ecore:EAnnotation>
  <ecore:EAnnotation source="kermeta">
    <details key="mainClass" value="root_package::Main"/>
  </ecore:EAnnotation>
  <ecore:EAnnotation source="kermeta">
    <details key="mainOperation" value="main"/>
  </ecore:EAnnotation>
  <ecore:EPackage name="root_package" nsURI="platform:/resource/org.kermeta.compiler.kmt/models/new_file.ecore#/"
      nsPrefix="root_package">
    <eClassifiers xsi:type="ecore:EClass" name="Main" eSuperTypes="platform:/plugin/fr.irisa.triskell.kermeta.io/src/kermeta/kermeta_java.ecore#/1/language/structure/Object">
      <eOperations name="eachOwnedElement">
        <eAnnotations source="kermeta">
          <details key="body" value="do&#xA;&#x9;self.ownedTags.each{o | do&#xA;&#x9;&#x9;&#x9;func0(o)&#xA;&#x9;&#x9;&#x9;func1(o)&#xA;&#x9;&#x9;end}&#xA;end"/>
        </eAnnotations>
        <eParameters name="func0" eType="#/3/_KermetaSpecialTypesAlias_">
          <eAnnotations source="kermeta.functionType">
            <details key="0" value="alias Object : kermeta::language::structure::Object;"/>
            <details key="1" value="alias Object : kermeta::language::structure::Object;"/>
          </eAnnotations>
        </eParameters>
        <eParameters name="func1" eType="#/3/_KermetaSpecialTypesAlias_">
          <eAnnotations source="kermeta.functionType">
            <details key="0" value="alias Object : kermeta::language::structure::Object;"/>
            <details key="1" value="alias Object : kermeta::language::structure::Object;"/>
          </eAnnotations>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="_KermetaSpecialTypesAlias_" instanceClassName="java.lang.Object"/>
  </ecore:EPackage>
  <ecore:EAnnotation source="dependentResource"/>
</xmi:XMI>
